### ISSUE TITLE
customised list modals and display templates are no longer working

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#1046]
e.g. walkin location, opat antimicrobial

**Comment by michaeledwardmarks** [comment]
???This is ??the meta issue for #1056 and maybe #1050 #1051

**Comment by michaeledwardmarks** [comment]
@fred this is still not working for me - still get the weirdness with the Other Subfields etc

**Comment by fredkingham** [comment]
@michaeledwardmarks so what I was aiming to fix with this ticket is that walkin have custom modals for e.g. location that's what I think is now fixed. While I was fixing it, I noticed #1050 so I fixed that, I think the other tickets are seperate. (I'll move #1050 over for review)

**Comment by michaeledwardmarks** [comment]
Ok. In that case that is fixed.

**Comment by michaeledwardmarks** [comment]
Is this still broken or now fixed?
