### ISSUE TITLE
Cant search by Properties of Episodes

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1049]
Location has OPAT dates but not Walk-In Dates

**Comment by davidmiller** [comment]
Walkin dates are actually stored on episode I think. The meta problem is that you can't search by properties of episodes themselves (also includes date of admisison/discharge etc)

**Comment by michaeledwardmarks** [comment]
This is an issue in particular for
- [ ] Date of Walk In Episode
- [ ] Date of Admission
- [ ] Date of Discharge

Unclear if this will be fixed by the ability to use the "Admission Identifier" fields once we have integration as those appear to include Dates of Admission/Discharge
