### ISSUE TITLE
Investigations Modal Broken

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1051]
Shows random combination of fields even before investigation type selected.
Fields dont change based on the test you select.

**Comment by michaeledwardmarks** [comment]
Presume fix not deployed as still looks broken.

**Comment by michaeledwardmarks** [comment]
Fixed in terms of what it does but GUI weirdness - like double drop down thing.
![screen shot 2016-05-17 at 11 59 09](https://cloud.githubusercontent.com/assets/4578105/15320139/d9ae53ae-1c26-11e6-82b6-d4d3b4579dab.png)

**Comment by davidmiller** [comment]
This is a Chrome thing. It's irritating. 

I looked at it briefly before - it's not related specifically to Investigations... can't remember how easy it was to fix

**Comment by michaeledwardmarks** [comment]
If chrome only then suggest close this issue?

**Comment by fredkingham** [comment]
its the native autocomplete if we've submitted a form before, I'd suggest
closing this issue, maybe create a new issue to turn off all native browser
auto complete by default

**Comment by davidmiller** [comment]
New issue !
We should stop this.
It's really irritating.

On Tue, 17 May 2016 at 12:14 Fred <notifications@github.com> wrote:

> its the native autocomplete if we've submitted a form before, I'd suggest
> closing this issue, maybe create a new issue to turn off all native browser
> auto complete by default
>
>
>
> On 17 May 2016 at 12:06, Michael Marks <notifications@github.com> wrote:
>
> > If chrome only then suggest close this issue?
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openhealthcare/elcid/issues/1051#issuecomment-219686745
> >
> >
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/1051#issuecomment-219688388>
>
-- 
Best regards

David Miller
Open Health Care
