### ISSUE TITLE
Discharged Last Week Broken on 0.6

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1052]
Discharged quite a few patients.
No one on DLW.

**Comment by michaeledwardmarks** [comment]
Do appear on Consultant Review Ward Round with a Discharge Date which means they should be on DLW

**Comment by davidmiller** [comment]
Just a thought but my first guess would be that the filter by team query
never got updated to tagging.value ...

**Comment by michaeledwardmarks** [comment]
Appears fixed.
