### ISSUE TITLE
Symptoms Modal Doesnt Remember what you entered if tagged to second list

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1053]
Create patient on tropical
Enter Symptom == Fever
Go to ID Inpatients
Enter Hospital Number
Patient tagged to ID Inpatients
Symptoms Modal Appears but is blank

Correct behaviour should either be:
1) Show the already entered data
2) Dont show the modal at all as patient already on a 'symptoms collecting list' (ID Inpatient/Tropical/Immune Inpatient)

**Comment by GabPoll** [comment]
linked to #1064 probably @fredkingham?

**Comment by michaeledwardmarks** [comment]
Fixed
