### ISSUE TITLE
Search by Name Not Working

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1055]
![screen shot 2016-04-17 at 15 30 52](https://cloud.githubusercontent.com/assets/4578105/14587796/70250fcc-04b1-11e6-84f9-02314714ccad.png)
![screen shot 2016-04-17 at 15 31 06](https://cloud.githubusercontent.com/assets/4578105/14587801/7dbb808a-04b1-11e6-97b0-20502274f497.png)

**Comment by michaeledwardmarks** [comment]
Doesnt work for first name or last name

**Comment by davidmiller** [comment]
There's another ticket for the first name part.... Would be nice if that
got looked at in 0.6 I think
