### ISSUE TITLE
OPAT Review Outcomes from old episodes show up incorrectly on new OPAT Episode Patient Details view

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1070]
Patient has episode 1:
I complete OPAT Review Data

Patient has episode 2:
I discharge them from  a second OPAT episode.

When I go to their page it shows the OPAT Review Outcome data from the first episode on the Patient Page for the current episode - this a) is incorrect and b) doesnt show a date qualifier which doubles confusion.

Seen in the wild.

**Comment by davidmiller** [comment]
We're re-using the 'copy to category' functionality here... 

What we need is a way to select subrecords that don't get copied over.
@fredkingham I suggest a model property - thoughts?

**Comment by fredkingham** [comment]
create an episode, pass from review to follow up, to the last step. Then click back to IV. This will then create a copy of the episode. This should not copy the opat outcome model

**Comment by michaeledwardmarks** [comment]
Fixed.
