### ISSUE TITLE
When adding new patient to OPAT referrals, they don't get added to list in real time

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1073]
Page needs refreshing or navigating away.

Instead when adding a new patient to an inpatient list, they appear on the list straight away.

**Comment by davidmiller** [comment]
@fredkingham I thought we looked at this and fixed it ?

**Comment by fredkingham** [comment]
I thought so too... might need another look

**Comment by GabPoll** [comment]
fixed.

BTW, anyone else find bug issue closing really satisfying?!
