### ISSUE TITLE
When accepting patient to OPAT Current, option to not have allergies should persist

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1074]
Currently it says - patient has no allergies entered, do they have none?
If you check the tick box, the option disappears. I think this is wrong in case tick entered erroneously.

**Comment by davidmiller** [comment]
I'd argue this is wrong because allergies are from ePMA now...

**Comment by GabPoll** [comment]
ok, i agree with you @davidmiller. Therefore, that question shouldn't even arise then?

**Comment by fredkingham** [comment]
hold up, quick review, we only show the no allergies in the modal if its from ePMA.

I think the difficulty with this comes when we have hybrid allergies, ie we have allergies coming from ePMA and have patients manually entered allergies.

Essentially I think we need to look at this when we're doing ePMA integration. Which is not v0.6.0 anymore, so I'm bumping...

**Comment by davidmiller** [comment]
I think this is no longer an issue - the 'no allergies' is only a temporary check to see if the patient can be added - allergies can still be added at any subsequent time.
