### ISSUE TITLE
Table Headers dont stay fixed

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1090]
when you scroll down you lose headins e.g demographics etc. Feel like this is a regression?

**Comment by fredkingham** [comment]
This has been (accidentally!) resolved by another ticket, it all looks good on elcid uch test now, please confirm

**Comment by michaeledwardmarks** [comment]
If fixed its not deployed (at least not on http://elcid-uch-test.openhealthcare.org.uk)

**Comment by fredkingham** [comment]
it was a bug that only happened after you logged in, pretty niche. So I thought it was fixed because refreshing the page showed it was fixed... Is actually now fixed and deployed, please check again.
