### ISSUE TITLE
Opat detail view doesn't have a link back to the list

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1096]
this is a regression

**Comment by GabPoll** [comment]
agree - before you could click on team name.

**Comment by michaeledwardmarks** [comment]
Still no link?

**Comment by fredkingham** [comment]
it is done, but clearly its a bit too sublte... David's going to have a UX think

**Comment by davidmiller** [comment]
@michaeledwardmarks The way to go to a list shouldn't be different for OPAT patients to the way it is for every other patient... I'm not sure this is actually done :)

**Comment by michaeledwardmarks** [comment]
leaving this to @davidmiller
