### ISSUE TITLE
OPAT episodes in patient detail should display a start and the stop date

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1099]
in the episode switcher down the side and in the episode header

**Comment by fredkingham** [comment]
this does actually work, e.g. http://elcid-uch-test.openhealthcare.org.uk/#/patient/35/37

**Comment by michaeledwardmarks** [comment]
![screen shot 2016-05-19 at 16 18 13](https://cloud.githubusercontent.com/assets/4578105/15398887/5aac4d8c-1ddd-11e6-90b1-04eedfa25a5f.png)


http://elcid-uch-test.openhealthcare.org.uk/#/patient/35/100

Add another episode. accept OPAT current. No date shown.

**Comment by michaeledwardmarks** [comment]
Still having issues:
http://elcid-uch-test.openhealthcare.org.uk/#/patient/33/71

**Comment by michaeledwardmarks** [comment]
works for old episodes but not the current OPAT episode

**Comment by michaeledwardmarks** [comment]
In fact it is true for all episode types that the current episode dates are not shown.

**Comment by michaeledwardmarks** [comment]
Still not working.
See https://elcid060.herokuapp.com/#/patient/108/110

**Comment by fredkingham** [comment]
so I think that wasn't working because of random data not creating the required dates, it seems work on elcidt with live data. Referrals don't create a date, which might be a problem (not sure as things like Haem, have an episode but its not necessarily used)
