### ISSUE TITLE
Changing OPAT Completed Therapy Outcome Data on Patient View changes stage to OPAT Review

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1118]

**Comment by michaeledwardmarks** [comment]
OPAT Outcome Modal has a sub_variable  (hidden from use) called OPAT Stage which can be Completed Therapy, Completed Follow-Up, OPAT Review

If on the Patient Detail Page you edit a Completed Therapy Outcome it now says OPAT Review

**Comment by fredkingham** [comment]
@michaeledwardmarks can you take a look at http://elcid055.herokuapp.com/ it should have the opat release fix for Monday (no other changes)
