### ISSUE TITLE
Make a Codebook for Extracts

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1137]

**Comment by michaeledwardmarks** [comment]
Version 1 done.

**Comment by michaeledwardmarks** [comment]
?Include codbebook as excel in any extract?

**Comment by GabPoll** [comment]
This is an excellent idea. Perhaps make the codebook file name CAPS to make it stand out?

**Comment by michaeledwardmarks** [comment]
https://docs.google.com/spreadsheets/d/1qX7vIUfes27czr0Sobgw-SxBoE9wbT600DokgoZyHYI/edit#gid=1577597242
