### ISSUE TITLE
Select CSV for extract 

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1141]
No idea how complicated this is.
I do a search.
When I come to download I tick the spreadsheets I want e.g
Travel, Diagnosis 
My extract is just those.

MB - no merging, no re-arranging or anything clever just sunsetting the CSVs 

Might help with the "there are lots of spreadsheets I don't need" issue

**Comment by davidmiller** [comment]
This is more or less where we ended up, closing this pending individual feature issues in Opal that will get us there !
