### ISSUE TITLE
fix add patient message

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1176]
at the moment there's an assumption we have gloss querying logic that is still pending

**Comment by michaeledwardmarks** [comment]
still get this message
![screen shot 2016-06-10 at 10 10 48](https://cloud.githubusercontent.com/assets/4578105/15959662/b73c656a-2ef3-11e6-84fd-2f8d83c47a01.png)

**Comment by davidmiller** [comment]
Fixed.
