### ISSUE TITLE
Do we want to tidy up the selection of fields that people can do a search on

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1194]
- e.g all those Details free text fields etc etc

**Comment by davidmiller** [comment]
@michaeledwardmarks Not sure really what you mean by this ?

**Comment by michaeledwardmarks** [comment]
There are lots of meta fields for example that I can't believe people would search based on.

**Comment by fredkingham** [comment]
we can remove fields from the interface fairly easily. For now we're thinking of leaving it as is.

@michaeledwardmarks @GabPoll if you want to give us some fields to remove, happy to remove them. Or we can close it, your call

**Comment by davidmiller** [comment]
Closing pending specific suggestions for removal.
