### ISSUE TITLE
We should make clearer what the fields are when doing an advanced search

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1195]
i.e diagnosis/issues vs Primary Diagnosis vs Primary Infective diagnosis

**Comment by GabPoll** [comment]
totally agree with this

**Comment by davidmiller** [comment]
This will be handled by these two plus the re-worked Opal extract interface: 

https://github.com/openhealthcare/opal/issues/987
https://github.com/openhealthcare/opal/issues/984
