### ISSUE TITLE
Should we try and write out what an advanced search is in english for the user

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1196]
e.g if the user selects drug , name == X AND drug, adverse event == Z
then IIUC what you get is someone where they had drug X and where they had adverse event Z but not necessarily someone who had drug X with adverse event Z 

Thats fine if you understand the search logic but people might not.
Not sure easy solution but worth a discussion

**Comment by davidmiller** [comment]
I've long thought this would be a useful and interesting experiment...

**Comment by michaeledwardmarks** [comment]
We should also think Bout how to handle that kind of logic e.g do we want to be able to specify I only want adverse event z in the context of drug x. 
Not sure that kind of thing would work
..

**Comment by davidmiller** [comment]
This is now being handled / implemented here: https://github.com/openhealthcare/opal/issues/983
