### ISSUE TITLE
weekend handover printout optimisation

### ISSUE THREAD

**Issue by drcjar** [openhealthcare/elcid#120]
weekend team would like to print out combined list with all pts on it

**Comment by michaeledwardmarks** [comment]
Flagged again by users

**Comment by davidmiller** [comment]
So, changes in 0.6 start to make this really easy.
Unfortunately we're some way off that just yet.
My hope would be that in say 0.7 this would be utterly trivial and we'll just do it.

If we want it before that I think we're into that project we keep talking about of cleaning up lots of the user requested enhancements that are just slightly too large and keep getting pushed back.

@fredkingham This is one of the places where a `PatientList` with a `queryset()` method would really work out... 

I think the steps are probably a get episodes for list API call and a re-think of how we do episodevisibility in the list controller on the front end. (Suspect we might actually be able to just delete that now.)

**Comment by michaeledwardmarks** [comment]
fair enough

**Comment by davidmiller** [comment]
Deployed to elcid062.herokuapp.com ready for review...

**Comment by GabPoll** [comment]
how do i review this? is there a separate button for weekday and weekend list to print?

**Comment by davidmiller** [comment]
It's a list called weekend in the lists dropdown. Should have everything tagged ID Inpatients, Immune Inpatients, Tropical on one list

**Comment by GabPoll** [comment]
looks fine. But we'll need to review on test server for final clearance (cos volume of patients. Keeping open for now.

**Comment by GabPoll** [comment]
also, it's a good solution, but is a little messy, in so much that it doesn't really stand out from other lists - it's not really a team per se. For a second review after 0.6.2

**Comment by michaeledwardmarks** [comment]
Suggest call it weekend HTD list. To make it clear it is a list for the inpatient teams.

**Comment by davidmiller** [comment]
Renamed on ELCIDT
