### ISSUE TITLE
Diagnosis specific additional data collection

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#124]
This is for a future iteration but we should start collecting  thoughts on this.

For research we would like to be able to have the ability to collect extra data on specific areas of interest.

In my brain the way I envisage this is being able to specify:
Between X and Y dates
If diagnosis = Z (+/- other features e.g age, etc)
Then bring up an additional modal with research specific questions: A B C

Ideally there would be an admin interface so that a research coordinator could define X/Y/Z and A/B/C

You can envisage having one or two of these projects running at any specific time

**Comment by michaeledwardmarks** [comment]
?Close this now we have the CEDAR repository

**Comment by GabPoll** [comment]
@michaeledwardmarks, i think we should keep this open. This issue is about capturing this extra information. Based on this being recorded on elCID, then CEDAR functionality can kick in.

**Comment by davidmiller** [comment]
Folks - I move to move this to opal-ideas as "wishlist/roadmap" rather than an open issue - thoughts?

**Comment by GabPoll** [comment]
Temporarily retired to https://github.com/openhealthcare/opal-ideas/issues/12
