### ISSUE TITLE
Haem referral doesn't progress beyond this page.

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1250]
![Uploading image.png…]()

Patient is still entered on system.

**Comment by GabPoll** [comment]
<img width="635" alt="image" src="https://cloud.githubusercontent.com/assets/4605661/17139563/f9380600-533c-11e6-866f-acc07b6916cd.png">

**Comment by michaeledwardmarks** [comment]
I get a 500 error and the following.
angular.js:9818 POST http://elcid061.herokuapp.com/api/v0.1/referral/micro_haematology/ 500 (Internal Server Error)(anonymous function) @ angular.js:9818sendReq @ angular.js:9619serverRequest @ angular.js:9335processQueue @ angular.js:13175(anonymous function) @ angular.js:13191$eval @ angular.js:14388$digest @ angular.js:14204$apply @ angular.js:14493(anonymous function) @ angular.js:21427dispatch @ jquery-1.11.3.js:4670elemData.handle @ jquery-1.11.3.js:4338

I am tethering so cant guarantee not my conneciton
