### ISSUE TITLE
Need consistency in OPAT rejection

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1267]
"refusal" used in button
"reject" used in modal.

I think we should stick with "refuse"

**Comment by davidmiller** [comment]
Great spot !

**Comment by davidmiller** [comment]
Deployed to elcid062.herokuapp.com ready for review...

**Comment by GabPoll** [comment]
![rejection](https://cloud.githubusercontent.com/assets/4605661/17336219/111d5c64-58d5-11e6-8b5d-4d7a60415500.png)

Afraid not there yet

**Comment by davidmiller** [comment]
Good spot @GabPoll - should be updated on the Heroku server now !

**Comment by GabPoll** [comment]
Accepting the refusal changes!
