### ISSUE TITLE
Date of admission option missing when adding a new patient

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1296]
Regression since 0.5

**Comment by davidmiller** [comment]
@fredkingham is this fixed ? If so in what branch ?

**Comment by fredkingham** [comment]
its fixed and merged on to https://github.com/openhealthcare/elcid/tree/v0.6.2.2

(we're currently on v0.6.2.1)

terribly named but v0.6.3 was the opal v0.8.0 release
