### ISSUE TITLE
UCH Release v0.6.2.3

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1319]
- [ ] CAB Form
 - [x] Deploy to Heroku
 - [x] Deploy to Test
 - [ ] Get Sign off
 - [ ] Deploy to prod
 - [ ] update py py for opal and opal-referral
 - [ ] do releases for all the packages that have changed

**Comment by fredkingham** [comment]
this is referring to v0.6.2.3, 
Its deployed to heroku here elcid0623.herokuapp.com and deployed to elcidt

we are waiting for a good window for when we can release it, we can't get clinical oversight this week so I'm bumping, and we are in the process of finding a good time that works for everyone.

**Comment by davidmiller** [comment]
6.2.3 is long gone !
