### ISSUE TITLE
Linking investigation results to diagnoses

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#132]
We've talked about this before - but it's a way for investigation results to code directly for diagnoses. 
For example, a further option on #131 could be: is C diff disease confirmed? Y/N - clicking Y, would automatically enter in the diagnosis modal "C diff" with today's date.

Not tagging specifically to micro because we may envisage this being useful for many conditions and would help quality of diagnosis data in the instances that these are driven by the investigation result.

**Comment by davidmiller** [comment]
Folks - do we think this is actionable in the short-medium term? 
What is the user need ?

**Comment by GabPoll** [comment]
now an OPAL-idea as at the moment there is not a specific development requirement. Can be re-opened if it becomes a formal request as part of development.
