### ISSUE TITLE
hiv point of care radio buttons in walkin

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1339]
add an hiv point of care on a walkin patient, try to click on the radio buttons, the first 3 don't work...

**Comment by fredkingham** [comment]
Radio buttons use the `name` attribute to dictate individual groups.

The opal `Investigations` form  and elcid `MicroBiologyTest` form both use the `result` field with multiple check boxes. Please add unique names to them all.

https://github.com/openhealthcare/elcid/blob/v0.7.1/elcid/templates/forms/microbiology_test_form.html
https://github.com/openhealthcare/opal/blob/v0.10.0/opal/templates/forms/investigation_form.html

**Comment by fredkingham** [comment]
@pacharanero 
for
https://github.com/openhealthcare/opal/blob/v0.10.0/opal/templates/forms/investigation_form.html
I think we need to change line 18 and actually line 541. I think that having multiple name attributes in the form even they aren't just radio buttons will confuse the browser.

**Comment by pacharanero** [comment]
this should now be closed by https://github.com/openhealthcare/opal/pull/1508
