### ISSUE TITLE
Tropical Liaison Tab

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#1346]

**Comment by fredkingham** [comment]
ping wozza to have a look

**Comment by fredkingham** [comment]
follow up on wozza's comments

clinical advice section be visible? Or if people want to print off to take for overnight oncall will they be able to see the plan in that section from colleagues?

[1:34]  
Also, the discharge liaison button didn't seem to work

[1:34]  
Also, I like the big contact details box- excellent

[1:37]  
If it is possible to have some form of flagging system e.g. Red is unwell patient needs to be actively chased/updated by team- HTD clinician concerned, green is patient stable to be aware, yellow is patient stable- awaiting further info/input- not urgent.
