### ISSUE TITLE
makeCopy runs continually for tagging in the detail view

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1351]

**Comment by davidmiller** [comment]
We use `hasTag('thing')` quite a lot for show/hide logic.

The implementation of `hasTag` calls `makeCopy` currently.

The display expressions are evaluated every time `$scope.digest()` happens.

Not sure this is a problem per se, but worth being aware of how many times it's going to fire when using show hide logic that calls functions.
