### ISSUE TITLE
pregnancy isn't showing up in the zika letter

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1357]
the pregnancy isn't showing up in the zika letter

**Comment by tom-parks** [comment]
In the Walkin service...

I can generate a Zika letter but I can’t see what to do it I can do with it. Am I meant to print it or send it?

I can't see how to change the pregnancy status which is crucially clinically. If I add pregnant to the “diagnosis/issues” the letter still says “not pregnant".

**Comment by tom-parks** [comment]
Related to this pregnancy test should appear on the list of Investigations.

There'd be an argument for making this an obligatory test (like HIV) for all women of child-bearing age -- at least while we continue to have a problem with ZIKA.

**Comment by GabPoll** [comment]
Is the Zika modal & letter being used now? I thought it had been ignored.

**Comment by davidmiller** [comment]
TBH we should probably remove this in the name of reducing complexity. 
Closing this issue pending clarification about whether it's still useful at all...
