### ISSUE TITLE
Patients are not appearing in the weekly coding meeting

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#1364]
- [x] Why are the specific cases we have not appearing
- [x] Strategy to prevent this
- [ ] Implement strategy

Theory is: 

Normal inpatient admit, discharge flow
Reappear, reopen old episode\
Discharge (not prompted for consultant)
Consultant based ward round, patient not on round

**Comment by fredkingham** [comment]
pending a response from wozza

**Comment by fredkingham** [comment]
went and spoke to Carmen, essentially if a patient is put in the dischared & pending results they remain added on the list and when you add the new patient, this episode is just reused.

The suggested fix is that we discharge the patient when they try and add them again
