### ISSUE TITLE
unable to remove patients from 'Mine'

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1373]
- [x] Is this still true?
- [x] On what versions ?
- [x] How will we fix

**Comment by fredkingham** [comment]
this came in with opal v0.6.0, the Tagging.build_field_schema started using a TaggedPatientList as 'mine' is not a tagged patient list it doesn't appear when you run 'item.makeCopy' on a tagging element. It does actually get get, it just never gets displayed and therefore can never be removed.

The solution is, honestly I'd hard code in 'Mine' its what we do elsewhere.

**Comment by GabPoll** [comment]
out of curiosity, do we have a feel for how much Mine list is used? Personally, when i go back to UCLH in Feb, i'd like to use it as much as possible.

**Comment by fredkingham** [comment]
According to our analytics its not used at all. I think the weekend list may have replaced it

**Comment by GabPoll** [comment]
weird why no one uses it - would seem such a useful CPD thing to do! Oh well.
