### ISSUE TITLE
Clinical advice Save button off the screen

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1381]
Obviously this is computer screen dependent, but for me on FF, 100%, Save button needs a scroll to be reached.

![image](https://cloud.githubusercontent.com/assets/4605661/23582528/20180bea-0124-11e7-9894-40c617b741ea.png)

**Comment by fredkingham** [comment]
@GabPoll I'm not sure this is a bug, its just a function of the size of the screen, is it so bad to have to scroll?

**Comment by davidmiller** [comment]
I guess we could change the time widget? TBH - for now at least I think we have to accept some scrolling... 
This won't  be the only place...
