### ISSUE TITLE
diagnosis in confirm diagnosis is rendering wrongly

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1396]
Has the message...

"" is not a valid condition, please choose a condition from the list below.

Alternatively email us at elcid@openhealthcare.org.uk with the correct diagnosis

despite not showing anything... Fix please

**Comment by davidmiller** [comment]
@fredkingham is this still an issue?

**Comment by davidmiller** [comment]
We're getting a steady drip of feedback on this anyway via Slack - closing this for now.
