### ISSUE TITLE
date of diagnosis doesn't work in haem referral

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1406]
if you enter it, it just blows up

**Comment by davidmiller** [comment]
Target next release queued on ELCIDT.

**Comment by fredkingham** [comment]
It no longer errors, the diagnosis does not appear to save however

**Comment by fredkingham** [comment]
- [x] add a menu item that only shows if you've got the micro haem role
- [x] tag an existing episode if it exists, otherwise create one
- [x] redirects to patient detail view
- [x] has a help text set up for walking through the referral
- [x] remove referral from requirements and installed apps
- [x] update stories to make sure the menu item only shows if the user is appropriately tagged
