### ISSUE TITLE
On multiple symptoms box, pressing down arrow on keyboard to select symptom did not work

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1452]
on elCID test

**Comment by davidmiller** [comment]
We're going to investigate the options of the widget we're using. If it's easy, we'll do this for 0.6.5 if not, in all honesty we might never implement this.

**Comment by GabPoll** [comment]
totally fine. the gut instinct is that use of the keyboard to select things is reserved for enthusiasts!

**Comment by fredkingham** [comment]
@GabPoll I just tried this on http://elcid0625.herokuapp.com/ and it works perfectly in both firefox and chrome... I'm not going to redeploy today... but I'll check it the next time I do

**Comment by fredkingham** [comment]
actually I did redeploy, just out curiousity and this now works, its a bit slow via VPN

**Comment by GabPoll** [comment]
Ok, sounds great. Just remind me, where did you deploy to? ElCID tesr? Can we close issue?

**Comment by fredkingham** [comment]
its on elcidt, so yeah we can close the issue
