### ISSUE TITLE
Meta-categories for Diagnosis

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#148]
@davidmiller 
Maddy and I discussed having meta-level categories into which multiple diagnoses fall
e.g Respiratory Infection

Linked to diagnoses but not actually entered by the user. e.g you enter diagnosis = CAP and in the background the system marks that as falling into the Respiratory Infection category

Then when you extract you could extract by that level - otherwise you would might end up needing a very long boolean list if you want to pull multiple diagnoses in one go

**Comment by davidmiller** [comment]
Do we think this is actionable ?
That moving to SNOMED CT is advisable?
Is there actually a user need for meta category diagnoses ? 
Honestly, I'm unsure what the user need is here !

**Comment by michaeledwardmarks** [comment]
I think this can be closed but may need revisiting as part of Maddy's thoughts on tightening up diagnosis and data-quality.
