### ISSUE TITLE
Button renaming on micro haem & oncology

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1490]
1) Change to "Save"
2) Change to "Add another diagnosis"
3) Change to "Add patient to Micro haem / oncology" (depending on service). Alternative, to keep simple "Add patient"

![image](https://user-images.githubusercontent.com/4605661/33256058-3ce07874-d348-11e7-952d-69db82ba9529.png)

**Comment by michaeledwardmarks** [comment]
Agree

**Comment by fredkingham** [comment]
unfortunately 'done' doesn't actually save it, it just shrinks it. This has been changed on elcidt, but was not changed on heroku...

**Comment by GabPoll** [comment]
@fredkingham i'm sorry, i don't follow

**Comment by fredkingham** [comment]
This is done and pushed to live
