### ISSUE TITLE
Workflow to add stewardship patients

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1492]
Is this correct?

For any patient on elCID (could be on another list, or a new micro advice referral), then go to stewardship list, click add patient, type in hospital number, all will be added on there.

**Comment by michaeledwardmarks** [comment]
See also #1510

**Comment by fredkingham** [comment]
Agreed on #1510, I don't understand @gabpol. What should happen?

**Comment by GabPoll** [comment]
I agree #1510 is ideal. However, say the patient is already on elCID for some reason, how does that patient get added onto the stewardship list? is it:

> go to stewardship list, click add patient, type in hospital number?

**Comment by fredkingham** [comment]
This has been done and deployed
