### ISSUE TITLE
Menu item rendering is dependent on there being a valid User.profile

### ISSUE THREAD

**Issue by pacharanero** [openhealthcare/elcid#1502]
In the process of working on #1494 it became apparent that menu rendering is dependent on there being a valid User.profile.

In the case of a non-logged-in User this causes 500 errors because the Django AnonymousUser does not have a .profile property.

**Comment by davidmiller** [comment]
### Acceptance criteria

- [ ] If we visit a page with the menu while not logged in, just show a link to the login page
- [ ] Write a test for this
