### ISSUE TITLE
Referral Page should show desired DOB format

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1508]
![screen shot 2017-12-10 at 11 21 36](https://user-images.githubusercontent.com/4578105/33804418-3a1c6af4-dd9c-11e7-8e9d-df9a46a4f2f1.png)

Looks like desired is DD/MM/YYYY - this should be shown in the field

**Comment by fredkingham** [comment]
We should show DD/MM/YYYY as place holder text in the field

**Comment by pacharanero** [comment]
This issue fixed upstream in Opal https://github.com/openhealthcare/opal/pull/1321
