### ISSUE TITLE
When doing Micro Referral should we add option to add to Bacteraemia and/or Stewardship lists

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1510]
Thoughts @GabPoll

**Comment by GabPoll** [comment]
ideally yes, i agree with you @michaeledwardmarks , i'd thought similarly. I held back as this was a v quick first pass and may involve some more work to put that link to teams, which currently we don't have elsewhere on (UCLH) elCID.

Thoughts @fredkingham ?

**Comment by fredkingham** [comment]
This is live
