### ISSUE TITLE
Antimicrobial form does not show the is not on antimicrobials button

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1511]
We have a field called not on antimicrobials that does not show in the form, but does show in the record. This leads to a patient saying they are not on antimicrobials even if they have been entered

[form](https://github.com/openhealthcare/elcid/blob/v0.7.0/elcid/templates/forms/antimicrobial_form.html)
[models](https://github.com/openhealthcare/elcid/blob/v0.7.0/elcid/models.py#L313)

**Comment by davidmiller** [comment]
Unlikely to add and deploy this to UCH medium term - closing this ticket.
