### ISSUE TITLE
can we change elcid.models.appointment_type to use choices?

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1521]
elcid.models.appointment_type could use the choices api. This will make the form more supportable.

- [x] change appointment_type to use the choices api
- [x] update the form to account for this
- [x] make and run migrations

**Comment by pacharanero** [comment]
Looks good. What are the options for appointment_type?

**Comment by pacharanero** [comment]
OK I found the options eventually

**Comment by fredkingham** [comment]
sorry, that would have been a good addition to the ticket...
