### ISSUE TITLE
Ignore discharged with follow up from the weekend list

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1525]
Issue 3. The weekend HTD list does not need people who have status discsharged with follow-up (means you print several unnecessary pages)

**Comment by davidmiller** [comment]
List is here: `/infectiousdiseases/patient_lists.py` 

Discharged with follow up is a possible value of the field `location.category`

**Comment by pacharanero** [comment]
Marcus notes:
* HTD = Hospital for Tropical Diseases
* add a patient to Virology
* Discharge that patient 'with followup'
* Print HTD list

**Comment by pacharanero** [comment]
this took slightly longer than anticipated.... 1) refamiliarising with Elcid etc 2) hit some upstream Opal bugs which have sorted out with @fredkingham

**Comment by GabPoll** [comment]
looks good
