### ISSUE TITLE
You can't generate a Walk-in letter from Patient details view

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1535]
not sure if it's a bug or a feature missing!

**Comment by GabPoll** [comment]
I just wanted to reiterate that this is really annoying :(
Genuinely can't believe no one has raised this before!

**Comment by fredkingham** [comment]
should be fixed by https://github.com/openhealthcare/elcid/pull/1549

**Comment by pacharanero** [comment]
![image](https://user-images.githubusercontent.com/2348385/37646833-9f76e9c2-2c22-11e8-9071-11430fe0435c.png)

@GabPoll this feature has been added, are you happy with the implementation?
Please close issue if happy

**Comment by fredkingham** [comment]
@GabPoll does this match requirements?

http://elcid-071.herokuapp.com/#/patient/2/2

**Comment by GabPoll** [comment]
Screenshot looks good. Could you also see #1565 as it's related to this. I.e. Remove zika button.

**Comment by GabPoll** [comment]
perfect, thx
