### ISSUE TITLE
Walkin review list displays full clinical advice entry

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1536]
Should only show minimal info, like OPAT current list, for example - i.e. date, name of person only. Then can click on entry to read content

**Comment by GabPoll** [comment]
Same for walkin doctor list. Takes too much space by displaying all the advice.

**Comment by GabPoll** [comment]
would be assisted if it went in hand in hand with #1535, as then you could scan a patient but then complete their letter and discharge them within in patient detail view

**Comment by pacharanero** [comment]
WIP on this ticket at https://github.com/openhealthcare/elcid/pull/1563

**Comment by davidmiller** [comment]
@GabPoll see the Heroku server https://elcid-marcus-test.herokuapp.com/ for the current implementation...

I have mixed feelings about the ellipsis - it's an entirely new patten for us...
Maybe try adding some realistic Clinical advice entries and seeing how they feel ?

**Comment by GabPoll** [comment]
personally i like the new implementation but there is an issue that i may have mentioned before but forgot to github. The nursing staff write a lot also in Symptoms Details box, which can have same effect. Could we implement in same way as clinical advice please?
![image](https://user-images.githubusercontent.com/4605661/37948655-0ee7a830-3189-11e8-9abd-f519847c2f45.png)

**Comment by GabPoll** [comment]
i checked and it seems fine, but i can be sure there is no truncation on patient details view? Seems to be only on list view to me

**Comment by GabPoll** [comment]
the ellipsis is a bit subtle, i have to be honest @davidmiller . It may not be obvious there is more to read
A more obvious "MORE" in bold, which is clickable?

**Comment by pacharanero** [comment]
We are currently blocked on deployment to Test because of problems with the VPN token, but the PR for this work has been merged https://github.com/openhealthcare/elcid/pull/1563
