### ISSUE TITLE
Walkin clinical discussion needs to be vertically longer. 

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1540]
Need to able to see more lines on screen. Would aid letter writing a lot. Plenty of space for modal to be taller.

**Comment by pacharanero** [comment]
@GabPoll is this fixed by WIP here: https://github.com/openhealthcare/elcid/pull/1563 ?

I've increased the height of the clinical advice textarea from 5 rows to 10 rows

**Comment by GabPoll** [comment]
looks better to me, thank you
