### ISSUE TITLE
RAID clinic needs to be on elCID

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1542]
No need for nurse triage tab, but otherwise identical to Walk-in.

Juniors very frustrated by lack of RAID clinic review list.

**Comment by GabPoll** [comment]
sorry, this is not a specific request, but opportunity to discuss user need, then can be pitched to consultants.

In essence this is a new outpatient clinic that has been setup in last couple of years.

**Comment by davidmiller** [comment]
Seems fairly unlikely to happen now - closing
