### ISSUE TITLE
The investigation "Respiratory virus PCR needs a new option

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1544]
as well as influenza A, etc...
It needs "Rhinovirus". Same options as other viruses (positive, negative, etc..)

Can't find on admin to fix.

**Comment by GabPoll** [comment]
@fredkingham could you point me in the direction on admin where i can change this. Just been an issue on a second patient.

**Comment by fredkingham** [comment]
@GabPoll sorry for the delay in getting back, this can't be changed in the admin.

For the dev who reads this we need to change
https://github.com/openhealthcare/elcid/blob/v0.7.0/elcid/models.py#L398

To include Rhinovirus and we need to change
https://github.com/openhealthcare/elcid/blob/v0.7.0/elcid/templates/forms/microbiology_test_form.html#L262
To add it in
We also need to change the record form.

**Comment by GabPoll** [comment]
thanks for getting back to me @fredkingham . Please let me know once this is fixed, thank you.

PS. in case you're wondering the reason is needed now is because UCLH have only recently started testing for Rhinovirus, so it was never a requirement when elCID was first conceived.

**Comment by fredkingham** [comment]
This is more complicated than initially hoped, it requires an opal change here

to 
https://github.com/openhealthcare/opal/blob/v0.10.0/opal/core/metadata.py

traditional model defaults don't work because of 
https://github.com/openhealthcare/opal/blob/v0.10.0/opal/static/js/opal/controllers/edit_item.js#L68
