### ISSUE TITLE
Walkin letter - copy to clipboard button doesn't work

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1546]
Just says "Failed" in red.

This is with Firefox, so not related to previous issue about walkin letter #1541

**Comment by GabPoll** [comment]
Truly weird - this actually works well via VPN!

**Comment by pacharanero** [comment]
I've not been able to replicate this bug in local testing. I'm using Chrome 65 and Firefox 58 for testing, and for both the Walkin Letter and the Zika Letter, clipboard copying succeeds and the contents of the clipboard are as expected when I paste them somewhere.

@GabPoll what browser and version are you using at UCH?

Also @GabPoll what was the VPN arrangement? Were you using a remote desktop access VNC/VDI (eg Citrix/GoToMyDesk-type thing) or were you accessing the remote server on your own machine through a true VPN connection? Between the two setups there is potentially a big difference in the browser that is being used.

**Comment by GabPoll** [comment]
@pacharanero it was the first - a remote client type thing. Not a true VPN.

I think we should close this issue - seems to be a computer specific issue at work. On some machines it works, others it doesn't. Even when doesn't work, it still selects the text you want copying, so nothing a quick CTRL-C can't solve. 

Thanks for looking into this.

**Comment by pacharanero** [comment]
OK thanks @GabPoll but if you find you are encountering the issue a lot in
the future then don't hesitate to re-open and we can bottom out the cause.
