### ISSUE TITLE
Update elCID requirements for new 0.10 updates

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#1551]
Particularly celery, but check everything

**Comment by pacharanero** [comment]
updated celery and django-celery to match requirements in Opal v0.10.0

**Comment by pacharanero** [comment]
PR #1562 pending

**Comment by pacharanero** [comment]
closed via https://github.com/openhealthcare/elcid/pull/1562 and https://github.com/openhealthcare/elcid/pull/1561
