### ISSUE TITLE
Do not show `Discharge Episode` on Mine

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1557]
- Add a patient to Virology
- Add the patient to Mine
- Discharge the patient from Virology
- Go to the Mine list, the patient now has the option to confirm discharge???!

Solution fixes
 - [x] Add a block around https://github.com/openhealthcare/opal/blob/v0.10.0/opal/templates/patient_lists/spreadsheet_list.html#L80
 - [x] Create a template for Mine that overrides this block
 - [x] The overridden template for the block should just plug in 
https://github.com/openhealthcare/elcid/blob/v0.7.1/elcid/templates/actions/mine.html
- [x] remove this from `actions` in the elcid/__init__.py as its now done in template logic.

**Comment by pacharanero** [comment]
I'm happy to do this with `{{ block episode_actions }} ... {{ endblock }}` or similar 
 - however I just noticed that the partial `_episode_actions.html` has an ng-hide flag for `hide_discharge_action == true`, which might well achieve the same effect...? And it's already there.

https://github.com/openhealthcare/opal/blob/ce41ce2b7f76d562dd59be0d25482ff4d97ab608/opal/templates/partials/_episode_actions.html#L3

**Comment by pacharanero** [comment]
As far as I can see that flag is not used anywhere else in the Opal codebase though (ie nowhere is currently setting that flag AFAICT)

**Comment by fredkingham** [comment]
I did not know that!

I can't find where it would ever be set...

I think what we want is not a block called mine something like 
```
{% block episode_actions %}{% endblock %}
```

**Comment by pacharanero** [comment]
also related:

https://github.com/openhealthcare/opal/issues/1468

**Comment by pacharanero** [comment]
Elcid:
https://github.com/openhealthcare/elcid/pull/1574

Opal:
https://github.com/openhealthcare/opal/pull/1473

**Comment by pacharanero** [comment]
the two above PRs have been merged and closed so I will close this ticket

**Comment by fredkingham** [comment]
👍
