### ISSUE TITLE
Remove zika letter button

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1565]
The outbreak is under control and sadly no one really used it. It's a shame was underused but as no one needs this button now, it just constitutes noise that we can remove.

**Comment by fredkingham** [comment]
- [x] remove the zika_letter from walkin/dischargesummaries.WalkinZikaLetter.
- [x] remove walkin/static/js/walkin/controllers/zika.js.
- [x] remove walkin/templates/actions/zika_patient.html.
- [x] remove the walkin zika action from walkin/plugin.py.
- [x] comment the model to state that this is no longer used.

We leave the model for the time being as there is data.

**Comment by GabPoll** [comment]
just noticed there are 2 zika buttons - letter and patient. Both need to go. Not sure this change up on heroku server yet this am
