### ISSUE TITLE
Change wording on walkin clinic letter template

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1577]
This should be easy fix as just words:

"On examination" chance to "Observations"

Remove "The most likely diagnosis was" - this is often unknown when the letter is written

"Advice Given in Clinic / Telephone Discussion:" change to "Clinic / Telephone Discussion"

**Comment by AndrewJanuary** [comment]
Hi @GabPol I'm happy to pick this issue up. I'm a first time contributor, looking for repos to contribute to.

**Comment by fredkingham** [comment]
fixed by #1579

**Comment by GabPoll** [comment]
can't see where this is fixed, sadly.

**Comment by fredkingham** [comment]
btw, https://github.com/openhealthcare/elcid/pull/1579 was not merged because we had unit test issues.

Unit test issues should have been resolved. I'll ping you a heroku once its merged
