### ISSUE TITLE
Slight misalignment of radio buttons in lab tests modals

### ISSUE THREAD

**Issue by pacharanero** [openhealthcare/elcid#1587]
In the example below, the Rhinovirus radio buttons are just slightly out of line with the others.

![image](https://user-images.githubusercontent.com/2348385/38821357-3468e596-4198-11e8-9cff-585a72105fa2.png)

As far as I can see this is because the Rhinovirus group is created using

`{% radio field="MicrobiologyTest.rhinovirus" %}`

whereas the others on that panel are being coded in HTML directly. There must be some small difference in how they are being handled, possibly just an extra space or missing space.

In the Inspector, all text in these radio buttons seems to have quite a lot of surrounding whitespace:

![image](https://user-images.githubusercontent.com/2348385/38821569-cc1b5748-4198-11e8-83b1-588598c86de5.png)
 
(it's the same for both kinds of radio button declaration)

**Comment by fredkingham** [comment]
@pacharanero great now that's one thing I'm never going to unsee.

We set radio buttons, essentially as float left with margin, ie they're independent. I'm not sure what the solution to this is.

I think it might be to move to bootstrap check boxes that we've been thinking about.

**Comment by davidmiller** [comment]
This is entirely valid, but pragmatically we're not going to fix this here any time soon - closing.
