### ISSUE TITLE
Merge Presenting complaint into symtoms

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#1595]
We have 2 models that are essentially the same.

https://github.com/openhealthcare/elcid/blob/v0.7.1/elcid/models.py#L149

https://github.com/openhealthcare/elcid/blob/v0.7.1/walkin/models.py#L36

This confuses users when they are extracting the data.

Can we merge these two models.

- [x] Add the onset field and make a migration
- [x] Add a data migration to walkin that depends on the migration in elcid that goes through all of the Symptoms and creates PresentingComplaints. Note we are _not_ deleting the PresentingComplaints at this stage as they contain reversion data.
 (https://docs.djangoproject.com/en/2.0/topics/migrations/#data-migrations, e.g. https://github.com/openhealthcare/elcid/blob/v0.7.1/elcid/migrations/0051_auto_20170523_0831.py although with different logic in run_python)
- [x] Add a template to https://github.com/openhealthcare/elcid/blob/v0.7.1/walkin/templates/walkin/modals/presenting_complaint.html that uses the term Symptoms rather than presenting complain.
- [x] Change the column in the walkin patient lists to use presenting complaint model but the display name 'Symptoms'
- [x] Change the detail view to use the PresentingComlaint Model but to pass in the title "Symptoms" https://github.com/openhealthcare/elcid/blob/v0.7.1/walkin/templates/detail/walkin.html

**Comment by pacharanero** [comment]
Should this:

> Note we are not deleting the PresentingComplaints at this stage as they contain reversion data.

read '...we are not deleting `Symptoms`...'

**Comment by fredkingham** [comment]
We are planning to avoid large db changes to elcid UCH at the moment because development is currently paused. If necessary we will handle these issues in a search rule.
