### ISSUE TITLE
Backlog Pruning

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#1658]
The backlog for elCID has grown unmanageably long :(

I'm proposing to close anything opened before Jun '17 - if it's that far down we are certainly not actively thinking about it, and unlikely to get that far down the backlog in the near future.

Anything reported fresh / again can then come in at the top.

**Comment by GabPoll** [comment]
Agree, good move
________________________________

**Comment by fredkingham** [comment]
This task has been done, closing.
