### ISSUE TITLE
Archive / separate "Mine" tag content

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#174]
Again, one of my slightly random thoughts.

The Mine list was created for 2 reasons in my mind:
1) allow doctors to track their own patients of interest - e.g. outstanding tests as an outpatient, etc...
2) allow doctors to keep a list of patients for their own portfolio.

I think these are good objectives, but in the long run, the lists may become unmanageable. Specifically, if one has a lot of lists for CPD / portfolio purposes, this may swamp / lose the patients being tracked for clinical reasons.

A solution could be to split the mine tag into something like "interesting patients" and "CPD patients". In addition, it may be nice to have a "archive all patients" button, perhaps useful after an annual appraisal session.

Appreciate some of the above may be resolved by searching "any patients tagged mine between these dates", but thought it was worth leaving for discussion.

Low priority. (not priority 0, as well explained by @davidmiller!)

**Comment by davidmiller** [comment]
I'm going to close this as 

a) not currently specifically actionable
b) superseded by openhealthcare/opal-ideas#3 

Should we do something more comprehensive for COPD then I believe that obviously we'll need more granularity than 'mine' !
