### ISSUE TITLE
Save and move to other modal buttons

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#195]
I thought this had been previously mentioned, but can't find it.

For each modal, would like a row of buttons called "Save & move to modal X", where modal X = investigations, antimicrobials, etc...
This way, can move from modal to modal on a single patient without needing to go in and out of modals. This way no need for eye to keep looking for next "add" link in each column (list view) or section (single view).

If widening modals as in #171, perhaps this could be added as column of links on right or left of modal.

**Comment by davidmiller** [comment]
@gabpoll Honestly, I am never going to implement "a row of buttons called "Save & move to modal X" ! ;)

I'm going to close this specific solution focussed ticket - but remain open as ever to discussing interface pain points, common user flows, and how we can better meet user needs

**Comment by GabPoll** [comment]
happy for this to be a closed issue that we can re-open if/when there is a need.

There is an undoubted requirement to speed up navigation & data entry. I don't mean page loads, but moving from one modal to another. If you speak to users who would need to do this in real time, they find it jarring to open one modal, save, open the next modal, etc..., Vanya included. However, I'm happy for this to remain closed pending these people formally raising it to you in a development plan / sprint.
