### ISSUE TITLE
Pull episode categories dynamically

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#217]
c.f. 
- https://github.com/openhealthcare/opal/blob/master/opal/static/js/opal/controllers.js#L669
- https://github.com/openhealthcare/opal/blob/master/opal/static/js/opal/controllers.js#L923
- https://github.com/openhealthcare/opal/blob/master/opal/static/js/opal/controllers.js#L1092

**Comment by michaeledwardmarks** [comment]
Is this still open?

**Comment by davidmiller** [comment]
We're probably 90% of the way there now, but a quick look suggests that we still have things like [this](https://github.com/openhealthcare/opal/blob/3d5d97e16a3af16dd3fbe376fc68d424cebd26ac/opal/static/js/opal/services_module.js#L2) which it would be nice to entirely get rid of.

**Comment by davidmiller** [comment]
This is done now - and probably should have been an Opal ticket all along ... !
