### ISSUE TITLE
Allergies - Clinical Safety edition

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#223]
Two possible features discussed today, feedback requested from all:

### Display in antimicrobials

Would it be helpful to display allergy information in the antimicrobials modal - to the right of the form. 
This is the clinically relevant time that you really need the information?

### Confirm conflicting allergy/antimicrobial

Allergies and antimicrobials come from the same lookup list - e.g. we have good understanding of equivalence. 
It would then be possible to answer the question

> Is this user allergic to this antimicrobial according to elCID

when a user saved an antimicrobial.
If the answer is yes, you can inform the user. 

Pings:
@michaeledwardmarks @GabPoll @drcjar @ollyharvey @7575colli @jonnylambourne

**Comment by michaeledwardmarks** [comment]
I'm not sure there is anything actionable here so closing.
