### ISSUE TITLE
In clinical advice modal, button / tick box / drop down options for commonly given advice

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#235]
This would only be a handful. Examples:
- "No Abx"
- "Continue earlier management plan"
- "NIPS" @Soniabhatt, please remind me what this stands for!

Related to #107 in aim to speed up clinical advice entry in real-time.

Thought needs to be given of where in modal this goes, though if widening modals (e.g. #171), then more screen to work with to the side of main clinical advice free text box.

**Comment by GabPoll** [comment]
@davidmiller , have you made this even better than before? If i now enter "#" i get drop down option of shorthand codes. I don't seem to remember this happening on first iteration but may have been Christmas fog! @michaeledwardmarks is this just me?

Related (and perhaps for separate discussion), i wonder if this macro beauty could help us towards #237. E.g. "D#" looks up diagnosis look up list, "A#" looks up antimicrobial look up list, etc...

**Comment by michaeledwardmarks** [comment]
I think this kicked in since we added more than just the "easter" macro

It is class!

**Comment by davidmiller** [comment]
@GabPoll The drop-down was always there, but it gets more useful when there are many things to complete :)

In theory you could have multiple completions available - perhaps one for 0.4/1.0 !

**Comment by GabPoll** [comment]
ok good to know. For sure for future iteration. Only raised for discussion.
