### ISSUE TITLE
Free text coding option

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#237]
A way to code diagnoses in middle of free text. Don't know how best to explain, but GitHub is an example example = adding # in front of number to link to coded issues.

Many permutations of how to do it, but not formally added as an issue yet and wanted to get ball rolling.

Perhaps even different symbols - # = diagnosis, * = antimicrobial. How that information is then entered is unclear - perhaps provide option to fill relevant modal for each condition / antimicrobial at end of free text box?

Advantage again is increased speed and fidelity of data entry - if only do it once, will do it better. Mainly relevant to real time elCID data entry, perhaps less so for inpatient lists. However, an entirely optional functionality - bit like keyboard shortcuts as an example.

**Comment by davidmiller** [comment]
Folks - is this still a thing ? ;)

**Comment by GabPoll** [comment]
Transferred to the conceptual world. Would love it back as an issue.
