### ISSUE TITLE
Keyboard navigation out of sync with page navigation

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#280]
Difficult to explain. 

Basically, if you use the keyboard keys to navigate through the different columns and rows, the page scrolling can get ahead of itself, such that the highlighted box is left behind at the top of the page.

Most easily demo-ed on single patient view, but can also be reproduced on list view.

Tested on IE11 touch version, so may be browser specific issue.

**Comment by michaeledwardmarks** [comment]
Seems not an issue on 0.4 so shutting.
