### ISSUE TITLE
Patient Flow: Entering the Walk-In Service Edition

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#298]
This remains a question at present.
If we think that nurses might do the initial data entry it would make sense to have a modified Add Record workflow for Walk-In patients.

This could capture
Demographics/Location/Travel/HIV POCT Result (From Walk-In-Tests Field)/??Symptoms Field

I think this will need serious discussion with nurses -practically speaking it may be easier just to leave the junior doctors to do all the data entry although that clearly misses out on many of the potential advantages of the system

**Comment by davidmiller** [comment]
I think this meta issue is basically obsolete now, pending latest deployment. Move to replace w. specific individual bug issues :)

**Comment by michaeledwardmarks** [comment]
Need access to patient flow buttons (see #562 ) to confirm but agree high probability this can be closed

**Comment by michaeledwardmarks** [comment]
Agree this is fixed bearing in mind
#562 
#542
#544
