### ISSUE TITLE
Investigations with bullet point options need "Not done" category adding

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#304]
I was sure I'd raised this before, but can't find it. Reminded by #293 

On serology tests where it has "pending, positive, negative, equivocal" (e.g. hepatitis A IgG), we need to add an option "not done". This has been requested by virology for a while.

**Comment by davidmiller** [comment]
Deployed to 0.4 Server

**Comment by michaeledwardmarks** [comment]
Perfecto!
