### ISSUE TITLE
As a user I would like autocompletion for multiple list entries in a single field

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#312]
Not sure if this is deliberate but you no longer seem to be able to string entries in the PMH or travel fields.
Occurs on elCID-Test (VPN, FF), elCID-Live (VPN, FF) elCID-Search (Mac, Chrome), elCID-OPAT (Mac,Chrome)

**Comment by michaeledwardmarks** [comment]
@davidmiller 
If there is any chance of getting this working again with the current update I think that would be excellent.
For example with presenting complaint - at present you type Cough (lookup list) but if the person has multiple symptoms (as they do) you can't string the entries.

**Comment by davidmiller** [comment]
Honestly, without #330, I don't think this is actually particularly useful. 

You take a situation where you would have had three coded diagnoses albeit with a slightly longer data entry time, and turn it into one where we spent less time typing, but it's much harder to analyse later on.

I'd vote that it's only worth doing if they happen together

If #330 is the behaviour we want, then yes multiple entries should obviously all autocomplete :)

**Comment by michaeledwardmarks** [comment]
I think this is valuable:
It lets me type multiple country names in one go for travel e.g

south africa, burkina faso, chad

Therefore saving me time and avoiding spelling mistakes
Even without #330 this is still helpful

It is fairly straightforward to then right a command in r/stata etc to search that string for specific countries.

**Comment by GabPoll** [comment]
have to admit, i'm with @michaeledwardmarks on this one. Can always get excel to split the string into separate columns.

**Comment by davidmiller** [comment]
I think advanced search would be mightily complicated (read slowed) by it though...

**Comment by michaeledwardmarks** [comment]
The quality of the data will be improved I think.
I imagine that actually advanced search is used relatively infrequently and mostly for specific research/audit questions in which case the loss of speed would be compensated by the improved quality.
Happy to discuss further.

**Comment by davidmiller** [comment]
At the minute we expect the user to make three entries though no? 
Surely there's no change to the quality of data?

**Comment by michaeledwardmarks** [comment]
Well I think probably people just make one long entry with a lookup list only for the first item.
e.g I think people do
South Africa, Ghana, America

not
South Africa (save)
Ghana (save)
America (save)

**Comment by GabPoll** [comment]
@davidmiller at the moment, not all field can be strung with multiple entries though. #481 is closed but would not be resolved by clicking save more often. I.e. for one investigation result with sensitive / resistant antibiotics, that field should have the ability to code more than one antibiotic - there's nowhere to put this.

**Comment by michaeledwardmarks** [comment]
That is a good example @GabPoll 
Presenting complaint is another one - only 1 entry can ever exist per patient

**Comment by michaeledwardmarks** [comment]
@davidmiller
I'm strongly in favour of stringing - for example for s
a) symptoms in walk-in.
b) presenting complaint
c) antibiotic sensitivities

These are all things where really there will only be "1 entry" but it needs to contain multiple coded bits of information

**Comment by GabPoll** [comment]
+1 with @michaeledwardmarks on this

**Comment by davidmiller** [comment]
@michaeledwardmarks But it's more complicated than that :) 

The thing that you want is not a free text field with multiple lookuplist entries stored-as-free-text. 

What if your patient presents with a 4-week cough and a 3 day fever. 
What you want is really not "only 1 entry" - it's the possibility for multiple presenting complaints per episode.
Just like you have in walk-in right now.

For antibiotic sensitivities (Investigations?), what you want is to be able to specify that some fields of records are lists of things, and that those lists of things sometimes are things that are from lookuplists.

e.g. an investigation can have N sensitive antibiotics, where each individual sensitive antibiotic is a Lookuplist-Or-Freetext.

I'm really strongly against implementing lists of things that end up as comma separated lists.

If we want lists of things as fields, let's do lists of things & do it properly.
Not for 0.4 though!

**Comment by michaeledwardmarks** [comment]
I'm going to close this but we could reconsider the use of the same approach used in symptoms for some of these fields if it comes up again.
