### ISSUE TITLE
Extract Page -  needs clear button

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#318]
Clear all extract terms
Otherwise painful to manually delete multiple terms etc etc

**Comment by davidmiller** [comment]
@michaeledwardmarks @GabPoll Can you take a look at the work on the advanced search interface that @fredkingham has been doing? 

It's deployed to http://elcid04-test.herokuapp.com/#/extract 

Originally we were going to simply add a clear button - but in the end we've re-designed the page - not a radical departure, but given some long-overdue love.

**Comment by michaeledwardmarks** [comment]
Looks really nice

**Comment by GabPoll** [comment]
Love it - neatly guides user, and just looks more professional. Good work @fredkingham & @davidmiller

**Comment by michaeledwardmarks** [comment]
Yes I think that this can be closed?
