### ISSUE TITLE
Downloading results can take time - message required

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#328]
The time taken for the zip file to be made to be downloaded appears proportional to the the number of records being extracted (fair enough).

This can take several minutes- as a one off, this is also fine, but user should be aware of this. At the moment, a separate tab opens and just spins round thinking, and then a "save as" option appears for the zip file.

**Comment by davidmiller** [comment]
While I agree - I'm not sure we need a separate issue to #329 ! :)
