### ISSUE TITLE
Server times out when downloading too much data from Extract

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#329]
There are 545 Microbiology records.
After about a minute, the tab that had opened has this message:

504 Gateway Time-out
nginx/1.2.6 (Ubuntu)

**Comment by michaeledwardmarks** [comment]
Yes this is definitely an issue.
Unable to extract all ID-Liaison patients for presentation tomorrow....

**Comment by davidmiller** [comment]
OK. 

Having played with this extensively on test & prod servers, the answer is to implement https://github.com/openhealthcare/opal/issues/250 . 

(@gabpoll @michaeledwardmarks that is also the blocking issue for e.g. auto-discharge.)

**Comment by michaeledwardmarks** [comment]
Cool.

**Comment by michaeledwardmarks** [comment]
This is a priority for me.
Timeouts now block any download for any team based data via extract
Applies to all the inpatient teams, liaison and micro-haem.

**Comment by michaeledwardmarks** [comment]
Also at least via VPN the search itself also times out now for larger searches, e.g team==tropical.

**Comment by davidmiller** [comment]
Fix to this is deployed to ELCIDT...

**Comment by GabPoll** [comment]
How long should I wait?

**Comment by davidmiller** [comment]
Could be a long time :(

Depends how big your extract is...

On Fri, 6 Nov 2015 at 16:27 GabPoll <notifications@github.com> wrote:

> How long should I wait?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/329#issuecomment-154459354>
> .
>
-- 
Best regards

David Miller
Open Health Care
