### ISSUE TITLE
need to be able to extract records by date of admission or discharge

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#339]
Can't believe we missed this!

One of the consultants is interested in doing an audit of all patients under his care during his month of duty. He doesn't directly use elCID, so Mine list not an option.

In the extraction interface, there is nothing that allows you to search / filter based on date of admission or discharge. This would be useful & I think quite important to make use of this extract function in the short term. Putting as priority 0, but feel free to scale down if disagree / not easy.

**Comment by davidmiller** [comment]
Note that this also restricted the ability to find patients in a discharge review meeting today.

**Comment by michaeledwardmarks** [comment]
Including date of being in walk-in
See for example the Zika Query.

**Comment by michaeledwardmarks** [comment]
+1 on this.
Now that extraction getting faster this is very important.
e.g Tropical Patients between January-June 2015
this is a very common type of search for audits.
