### ISSUE TITLE
Sub-teams of sub-teams breaks elCID

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#344]
Example again explains this best.

On elCID-search there's micro, then sub team haematology. I tried to create a sub team of haematology (transplant). The effect was that elCID didn't load - Error pop up "Options could not be loaded".

If set the parent company to micro, order is restored.
Done on IE11, though again I suspect that's irrelevant.

**Comment by davidmiller** [comment]
Closing this as we've changed the way lists work so fundamentally it's no longer relevant.
