### ISSUE TITLE
Extract: value is not nullified when column is changed

### ISSUE THREAD

**Issue by andylolz** [openhealthcare/elcid#353]
Select a column and a field, then change the column and you’ll see some weirdness where “4. Add your value” has no input box:

![screen shot 2014-07-30 at 22 46 07](https://cloud.githubusercontent.com/assets/464193/3757043/b1136f9e-1834-11e4-8485-3d8a09d63a24.png)

**Comment by davidmiller** [comment]
This whole logic has changed now without anyone looking back to update this ticket - closing !
