### ISSUE TITLE
Discharge Diagnosis Review LIst

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#364]
With regards to #362

We will generate a view similar to #115 

- [x] View by Team
- [ ] Able to view by Month of Admission
- [x] Able to view by Month of Discharge
- [ ] Only certain users will have access to this view (similar to extract rights, also similar to https://github.com/openhealthcare/opal-research/issues/4)
- [x] On this view we will display: 
- Demographics
- Location
- Working Diagnosis
- Investigations
- Antimicrobials
- Discharge Diagnosis #363 
- [x] There will be a link for - Confirm Final Diagnoses 
- [x] Once a Final Diagnosis is entered the patient will be removed from this view

We need to be able to filter by month of admission/discharge as that reflects the consultants working pattents

**Comment by davidmiller** [comment]
I've limited it for the FDR one - we're already hand-specifying which teams the presenting complaint/discharge diagnosis appears for, so no real regression there. 

Generally though, I'm very nervous hand-specifying values that are admin-editable. It's a really bad idea.

An approach that I suspect will scale better is to reduce the amount of globally visible teams you have.

IIUC e.g. OPAT is irrelevant to most people, many of the Micro teams are irrelevant at all times, to most users. 

Member-only teams ( The remaining item from #127 ) is the way forward. 

Honestly, there's no *more* noise than team selection for the previous discharge list.

That sounds like something for a future iteration to me.

**Comment by michaeledwardmarks** [comment]
@davidmiller does that mean I can in admin set which lists show up on in the DLW ward round if I want to?  (as opposed to you hard-coding it).

**Comment by GabPoll** [comment]
+1 for admin-editable lists. Just like already setup for team lists & names.

**Comment by davidmiller** [comment]
@michaeledwardmarks At the moment it's me hardcoding it. There are no database (admin) entries for wardrounds, just code. 

Making those teams admin-editable is something we can look at, but honestly I suspect that there are other features you want more :)

**Comment by michaeledwardmarks** [comment]
Ok.
I would be massively in favour of some way of making the DLW team filter cleaner for the user as it is really only going to be used by 
ID
Immune
Tropical
and at the moment there are lots of un-needed distractions on it.

I appreciate the total amount of options is the same as on the old discharged page.
But the way they appear in a drop down is less easily navigatable as a user.
