### ISSUE TITLE
Final Diagnosis Modal

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#365]
Linked to #362
Accessed via the "Confirm Final Diagnosis" link discussed in #364 

- [x] Clicking this link will open a modal which will display the information entered in the Discharge Diagnosis Modal #363 

- [x] There will be a Confirm All Button - this will populate the Final Diagnosis fields with identical information to the Discharge Diagnosis

- If user opts not to 'Confirm All' then for each entry (e.g Primary, Secondary Diagnosis) 
- [x] User will be able to 'Confirm Diagnosis'
- [x] User will be able to 'Replace Diagnosis' 
- [x] If user opts to replace any entries then they would be editable in exactly same way as the entries in the Discharge Diagnosis Modal #363

**Comment by michaeledwardmarks** [comment]
Specifically if you try and use the edit buttons for Secondary Diagnosis you get the following error:

GET http://elcid-opat.herokuapp.com/templates/modals/secondary_diagnosis.html/ 500 (INTERNAL SERVER ERROR)angular.28f401490ec3.js:8495 (anonymous function)angular.28f401490ec3.js:8291 sendReqangular.28f401490ec3.js:8025 serverRequestangular.28f401490ec3.js:11498 wrappedCallbackangular.28f401490ec3.js:11498 wrappedCallbackangular.28f401490ec3.js:11584 (anonymous function)angular.28f401490ec3.js:12608 Scope.$evalangular.28f401490ec3.js:12420 Scope.$digestangular.28f401490ec3.js:12712 Scope.$applyangular.28f401490ec3.js:18980 (anonymous function)jquery.3b80424646a7.js:4624 jQuery.event.dispatchjquery.3b80424646a7.js:4292 elemData.handle

**Comment by davidmiller** [comment]
Three actions from https://github.com/openhealthcare/elcid/issues/365#issuecomment-68455431 have been implemented and deployed to elcid-opat !

**Comment by michaeledwardmarks** [comment]
Agree fixed.
Splendido.
