### ISSUE TITLE
OPAT - Community nurse referral

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#381]
* (CDR) OPAT/uclh letter head with OPAT contact details(see attached)
* (CDR) Patients name/dob/NHS no/address/telephone number/NOK and telephone number
* (CDR) Patients GP name/address/telephone number
* Diagnosis
* Allergies
* Antimicrobial plan (include an area of free text to allow additional administration instructions to be added)
* Vascular access (type/date inserted/external length)

```
Dear Community Nursing Team,
Please visit this patient’s home address to administer IV antimicrobials as directed above.
FISRT visit is required __/__/__ (time)
LAST visit is required __/__/__ (time)
Expected discharge date from hospital __/__/__  (hospital/ward and bed#)
Other documents included with this referral: (with ‘check boxes’ next to each one)
- OPAT referral cover sheet
- Area specific Community Nursing Referral form
- OPAT Drug administration sheet 
- Daily check list
- Equipment to supply to patient
- uclh vascular access community referral form
- Inpatient ‘discharge summary’ 
( Patient will be given a copy of their discharge summary when they leave hospital. )
-  Other….
```

It would be really great for this letter to also generate a ‘equipment supplied to patient’ template too (see attached) – The letter should auto generate the patients name/DOB/NHS number onto this form.

**Comment by michaeledwardmarks** [comment]
I'm closing all of these and merging them in to #624 to centralise stuff
