### ISSUE TITLE
OPAT - Nurse review letter

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#382]
This letter will essentially be a print out of the notes documented in the nurse review, it should comprise of the following details:
* (CDR) Pt name/DOB/Hopsital No/NHS No/address
* (CDR) GP Name/address
* Diagnosis/allergies and antimicrobial plan
* IV access – (line type/date inserted/date removed (if applicable) and ‘line assessment (VIP, external length, any recorded complications)’ and any additional notes
* Any ‘observations/vital signs (ie temp, BP, HR, RR, SpO2) Height, Weight,’ recorded)
* Treatment given today:
* Advice given to patient today:
* Next appointment (date/time)

**Comment by michaeledwardmarks** [comment]
I'm closing all of these and merging them in to #624 to centralise stuff
