### ISSUE TITLE
Remember last "Reason for Clinical Interaction" in Clinical Advice

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#396]
This is a suggestion from micro-haem team. For patient after patient that they see, they need to enter / drop down "Ward consult". This is time consuming and they would like it to default to that option, so they need to enter one less thing (bit like your name is auto-filled in).

Could be done as:
either a) keep remembering the last reason used for that user
or b) only remembers for that session logged into elCID, then blanks again next time.

I suspect a) is easiest.

**Comment by davidmiller** [comment]
The specific use case here for openhealthcare/opal-wardround#2 is trivial - but depends on that ticket being implemented !

**Comment by GabPoll** [comment]
Easy 0.5 issue @davidmiller? 
If v easy can do this as carrot to vanya to file micro-haem pts well inside ward round.
If not easy, then park it as incentive for formal micro-haem sprint

**Comment by GabPoll** [comment]
can close this now. Move to micro haem ward round issue and will hopefully be fixed as a haem sprint of its own.
