### ISSUE TITLE
Pre populate tests for walk in patients

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#398]
Every patient should come pre-loaded with the following three options:
- [x] HIV Point of Care Test (Reactive/Negative/Declined) 
- [x] If declined prompt second question - Reason for Decline (Look-Up List)  
- [x] Stool OCP (already exists in elcid list of Investigations)
- [x] Malaria film (already exists in elCID list of investigations)

**Comment by michaeledwardmarks** [comment]
Leaving this open as it has the info about the HIV POCT test but note essentially superseded by #543

**Comment by davidmiller** [comment]
Closing now as we're there and the other two tickets cover everything.
