### ISSUE TITLE
Receptionist portal for Walk-In

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#408]
One screen:

Hospital Number : SEARCH
If exists auto-populate

Else:
Name
DOB
Gender
Ethnicity

Add patient to Walk-In Nurse List

**Comment by davidmiller** [comment]
You can see the first draft of referrals for walk in on the 0.4 test server - thoughts welcome @michaeledwardmarks @gabpoll !

**Comment by michaeledwardmarks** [comment]
Looks really really good.
Note issue re-category not being set #564

**Comment by michaeledwardmarks** [comment]
I'm shutting this issue in favour of specific issues/modifications
