### ISSUE TITLE
As a User I would like to see more than one page of search results

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#412]
Currently shows 1-10 of 25, for example, but no option to go and view the remaining 15.

**Comment by davidmiller** [comment]
While I agree, I think what we really need is a full scale re-write of the search / results functionality.

This is closely related to openhealthcare/opal-ideas#1

**Comment by GabPoll** [comment]
David, really sorry, i think i duplicated this. Let me close this, perhaps you'll do the same on the new issue, and we can include this within the re-write of search.

In essence, close what you wish that works best in workflow.
