### ISSUE TITLE
Only show 3 clinical advice entries on list view

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#417]
Ref #107 

Need to make live version only show max of 3 entries for clinical advice when on list view

**Comment by GabPoll** [comment]
@davidmiller, is this trivial to fix for Jan release? In essence, what we want changing from the screenshot is removing the lines that have 3 dots.

![screenshot of desktop](https://cloud.githubusercontent.com/assets/4605661/5597843/daf088d2-92a1-11e4-9f6d-25274d237294.png)

**Comment by davidmiller** [comment]
@gabpoll Deployed to elcid-opat !

**Comment by GabPoll** [comment]
@davidmiller i see what you've done here. You've essentially blanked lines by compressing them, such that it displays the 3 most recent clinical advice entries, and the others are there but with very, very small line spacing entries, thereby hiding them. In this way, new entries still add a little height to each row, but a much smaller amount than before and no dots seen. I think in terms of practicality and solving the main problem initially, this works as a solution and we'll address any concerns / issues arising from this after real-world use. Thank you for resolving issue.

**Comment by michaeledwardmarks** [comment]
Fine by me. Bit weird if you navigate by keys - i.e you are on the bottom visible clinical advice but press down the user expects to jump down to the next patient but actually it moves to the compressed advice row.

**Comment by davidmiller** [comment]
Hmmm - that's not the desired behaviour at all. 

I think they just shouldn't be there.

**Comment by GabPoll** [comment]
hilarious - i thought you were being clever @davidmiller . It turns out it's actually a bug!

**Comment by michaeledwardmarks** [comment]
#572 
As with OPAT review this should be the most recent entries
 - Only shows 3 (beautiful) 
- [ ] This should be the 3 most recent entries. (e.g what shows up on the list should update as more entries are added)

**Comment by davidmiller** [comment]
I think we close this then - similarly to #572...

**Comment by michaeledwardmarks** [comment]
@davidmiller 
As this entry doesn't have a time-stamp (at least visible to the user) only a day-stamp does this order as:
3 most recent entries with date set to today?

**Comment by davidmiller** [comment]
Yep, It's date ordered

**Comment by michaeledwardmarks** [comment]
So in the scenario where a patient gets four distinct pieces of advice entered in a single day (rare but not impossible I would think for Vanya patients - say a phone call, ward round, then more phone calls)
It will show 1-3 of that day but not 4 - is that correct?

I have no understanding of the complexity but I would think that where multiple entries have the same date-stamp that they should be ordered with the newest first. Maybe the actual solution here is just to add a time-stamp to this field like in the OPAT review field?

I think the current (elCID-Live) always puts the newest entry at the top and I think we should stick to that as it makes the most sense. Adding a time-stamp would seem to achieve that.

Thoughts?

**Comment by GabPoll** [comment]
I would favour the time stamp. It's good / recommended practice to date & time all clinical not entries, and i think we should follow this. Then agree that latest entry is the first on list view, as current practice.

This should also help future development: HTD telephone advice will need a time stamp, and likely that the telephone advice modal will be built closely around (or be the same at first) as clinical advice modal.

**Comment by michaeledwardmarks** [comment]
OK so
- [ ] Add time stamp
- [ ] Order by date and time stamp

**Comment by michaeledwardmarks** [comment]
@davidmiller Just checking I am correct that the above two minor things need changing (switch to date-time stamp rather than just date-stamp)

**Comment by davidmiller** [comment]
@michaeledwardmarks Yep, those are still to be implemented

**Comment by davidmiller** [comment]
Having investigated more thoroughly now, similarly to #214 , #647 the shift to datetime is one for 0.5.

There's a danger of losing past date entries here, we need to take the time and get it right.

I'm closing this, adding/setting the time to CA is now in #648

**Comment by GabPoll** [comment]
fair call again @davidmiller
