### ISSUE TITLE
DOB Bug

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#428]
Sometimes when re-admitting a patient when you click the save button the DOB field blanks out and you can't add a new episode.
Unclear what triggers this for some patients and not others but in at least one case this was fixed by changing the patients old episode status from active to  inactive.

**Comment by davidmiller** [comment]
Can we close this ?

Is it still an issue ? 

Much has changed in the last 5 months ! :)

**Comment by michaeledwardmarks** [comment]
Not seen suggest closing currently
