### ISSUE TITLE
Add Patient for Walk-In

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#434]
Clearly we hope that most patients will be added via #408 

But lets say a doctor/nurse does use the add patient button for some reason

Then this should bring up a simplified modal similar to what happens in OPAT
With only
Name
DOB
Gender
Ethnicity

As per #297 the Category == Walk-In and can't be changed and the Date ==Today

We shouldn't have any of the hospital/ward/category/tag options available

**Comment by michaeledwardmarks** [comment]
@davidmiller 
Following up my email about staggered walk-in deployment with an update on this issue.
If we stagger walk-in-deployment (doctors in feb, rest later after training) then we might want to think about this again.

Also as per OPAT we should agree which List the Add Patient button should add a patient too if we do activate it (hope that makes sense!)

**Comment by michaeledwardmarks** [comment]
Currently this creates a bug.
If the patient is added from the doctor view, then they appear directly on the doctor list.
Clicking the end of appointment button brings up a combined modal for both the end of the nurse and the end of the doctor sections...
![screen shot 2015-01-23 at 11 55 23](https://cloud.githubusercontent.com/assets/4578105/5874215/bab2afb8-a2f6-11e4-9c79-69f718e283ab.png)

**Comment by davidmiller** [comment]
I think the thing to do here is to add to the current list, then show the appropriate modal for the list they're on right ?

**Comment by michaeledwardmarks** [comment]
So suggestion is
- If on doctor list: add direct to doctor list
- if on nurse list: add to nurse list
- if using referral portal: add to nurse list

**Comment by davidmiller** [comment]
I believe that to be the current behaviour.

**Comment by michaeledwardmarks** [comment]
Fine.
Closing.
