### ISSUE TITLE
Shut add patient modal before opening the presenting complaint modal

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#452]
Moved from #360

> If you access the presenting complaint modal via the Add Patient mechanism - could that modal shut completely prior to the Presenting Complaint one opening - it looks and feels a bit odd otherwise:

**Comment by davidmiller** [comment]
Fix to this deployed to elcid-opat. 

There is a slight lingering issue captured at openhealthcare/opal#249 which will be fixed before golive.

**Comment by michaeledwardmarks** [comment]
Fixed!
