### ISSUE TITLE
Generate formal help pages on elCID accessed from all elCID pages

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#458]
Similar / identical to document produced by @michaeledwardmarks so that new / unfamiliar users have a reference guide of sorts.

**Comment by GabPoll** [comment]
I think this should be in the next build if possible. Thoughts @michaeledwardmarks?. Can "just" be a link to a help page which includes the content of the current elCID user guide.

This is as much a governance issue I think, to ensure that elCID users have a quick reference guide to completing tasks on elCID. Or at the very least addresses concerns raised by micro consultant.

**Comment by davidmiller** [comment]
@GabPoll There is not that simple to do well honestly.

Can you name one transactional application that does this well ? 
Examples/things you like et cetera?

e.g. 

https://help.github.com/

**Comment by michaeledwardmarks** [comment]
I have to say whilst I agree with @GabPoll about making this stuff available that the reality is that I think 1 user has ever requested this at HTD.
This is only really an issue as some people in Micro feel that use of the software needs training but micro haven't (unlike) HTD taken steps to train staff. 
If micro want training then they should just organise some, it would be clearly be the best solution.

**Comment by GabPoll** [comment]
This idea is definitely not a replacement for training at all. That is the formal way to "induce" people on elCID, whatever department they work in, and will always be the way to introduce users to elCID.

I was thinking more as an adjunct guide, a SOP if you like. There is a SOP for authorising results on WinPath for example.

As to how to implement, @davidmiller that's a good point. Depends how much time we want to invest in it (minimal I suspect). As such, wonder we could offer to download the guide that @michaeledwardmarks wrote. I.e. host it on the elCID server.

**Comment by michaeledwardmarks** [comment]
@davidmiller
What would the hours drop to if we literally just linked to a PDF?

**Comment by davidmiller** [comment]
There's definitely a 1 point solution to this issue which is basically link to a PDF and tell people what the admin email address is.

I'm thinking of doing something more comprehensive here when I talk about the / a 20 point thing.

**Comment by GabPoll** [comment]
ok, in which case i'll make a new 1 point issue and add to waffle. Will keep this open in the meantime.

**Comment by davidmiller** [comment]
If we had a manual, we'd be delighted to provide a link to it.
Closing this until such time as we have one, at which point, we can add it to the application :)
