### ISSUE TITLE
Fixed diagnoses displayed for micro-haem (with contextual options)

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#459]
Closely related to discussions on #124. Borne from discussion with Vanya, @davidmiller and myself today.

These are:
a) neutropaenia
b) BMT
c) prophylaxis

Prompt user to answer these. These diagnoses have to be handled differently to other diagnoses. First question is Y/N. If N, then save & close. If Y, then further options.
1) Date commenced
2) Date ended
3) Details (should be a look up list for antimicrobials, so that for c), you can look up the antimicrobial they are on)

On list / single patient view, only display if not answered or if answer is Y, and if so, display all the details 1), 2) & 3).

**Comment by fredkingham** [comment]
is this dead?

**Comment by GabPoll** [comment]
yep, redundant now
