### ISSUE TITLE
Presenting complaint modal not coming up in correct instances

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#471]
not easy to explain - hear me out.

Presenting complaint needed for ID, Immune & Tropical patients. If you add a new patient when viewing those lists, the PC modal comes up after demographics one. Correct.

However, if add a micro pt when in ID list view, the PC modal also comes up - not desired.

Flipside, if add a ID or a micro pt when in a micro list view, the PC modal never comes up.

Overall, this is ok, as these cross over add pt scenarios unlikely, but thought i should flag up.

**Comment by michaeledwardmarks** [comment]
I think this is basically fixed because we now force collection of Presenting Complaint at Discharge.
So if someone had been added initially on a different list the user would still need to add symptoms as part of discharge flow.
