### ISSUE TITLE
As a User I would like more detailed options for VTE Investigation

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#473]
This is moved from #342 - @jonnylambourne should liaise with @michaeledwardmarks && @GabPoll

**Comment by davidmiller** [comment]
@jonnylambourne && @gabpoll && @michaeledwardmarks - this is : 

"For VTE, there is free text. Would it be possible to change this to a drop-down list of possible outcomes following VTE assessment? (If so, I need to come up with a list of possible outcomes!)"

We can do, do we want to  ?

Could go into the next milestone.

**Comment by GabPoll** [comment]
no strong feelings on this one. I'll defer an opinion.

**Comment by davidmiller** [comment]
This seems really far down the priority list for current OPAT users ! 
I'm going to close and we can re-visit/open as required later on if anyone discovers a user need...
