### ISSUE TITLE
Improvements to Allergy field

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#475]
Two suggestions from @jonnylambourne && @7575colli at today's OPAT meeting: 

1. Could we re-name allergies to include intolerances - e.g. 'Allergies and Intolerances'?
2. Record reactions with a lookuplist (below)

The open point of discussion was whether to re-name the "Details" field to "Reactions" or add an additional field. 

Would welcome input from @michaeledwardmarks @GabPoll on this as well as the chaps from OPAT - as soon as we have consensus we can make it so !

Reaction Lookuplist: 
* anaphylactic / anaphylactoid reaction
* rash
* gastrointestinal upset
* biochemical derangement (e.g. abnormal liver function tests)
* haematological derangement
* other

**Comment by davidmiller** [comment]
Folks - Am I right in thinking this is then a "No action" issue && we can close ? :)

**Comment by michaeledwardmarks** [comment]
Yes
