### ISSUE TITLE
'save and add another' redirects on save

### ISSUE THREAD

**Issue by jonnylambourne** [openhealthcare/elcid#477]
This may just be on the heroku version, but when I am in patient view and I try and 'save and add another' in a number of sections, I am brought out to the main patient view page
This happens in: 
- upcoming appointments
- past medical history

**Comment by michaeledwardmarks** [comment]
I'm not getting redirect issues.
Instead the save and add another button is just working like the save button.
Still annoying but less than the originally described issue.

Mac OSX, Chrome 39

**Comment by michaeledwardmarks** [comment]
I'm removing Priority 0 from this as it is a pain but not super massive issue.

**Comment by GabPoll** [comment]
have just noticed this too. hadn't spotted much as i never really use it. Agree not priority 0.

**Comment by davidmiller** [comment]
I think this is fixed - I've def. not seen it recently.

**Comment by michaeledwardmarks** [comment]
Fixed
Closed
