### ISSUE TITLE
As a User I would like an intuitive, easy to use interface for changing an episode's teams

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#482]
Currently all the options form one long list - which is too long really as it moves the save button off screen (on my computer at least).
Would be better to have two columns side by side.
Hope that makes sense. Think it used to be like that.

![screen shot 2014-12-22 at 17 51 11](https://cloud.githubusercontent.com/assets/4578105/5527932/273d9510-8a03-11e4-80ac-8f811c8d6d64.png)

**Comment by davidmiller** [comment]
Updated teams interface deployed to elcid04-test - do review!

**Comment by michaeledwardmarks** [comment]
Looks good to me.

**Comment by GabPoll** [comment]
yep, i like it too. thx @davidmiller
