### ISSUE TITLE
Discharge Issues

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#483]
So on testing some new issues found

 - add patient on ID-Inpatient list
 - add patient to tropical list too

- discharge patient on ID-Inpatient list
- complete Discharge diagnosis modal (correct)
- patient disappears from ID-Inpatient list (correct)
- patient still on tropical list but status = discharged (correct)

- try and remove them from tropical list by clicking Discharge/Remove from list
- don't get the "Confirm Discharge" modal (incorrect)
- just get the "Discharge Diagnosis modal" (incorrect as already completed when discharged)
- patient remains on tropical list (incorrect)

**Comment by davidmiller** [comment]
I believe a fix to this has been deployed to elcid-opat. Please do test !

**Comment by michaeledwardmarks** [comment]
This is sort of fixed but a bit more complicated than I thought...

- Discharge patient on first list
- Get Discharge Modal: Correct
- Get Discharge Diagnosis Modal: Correct

- Discharge patient from second list
- Get Confirm Discharge Modal: Fixed and Correct
- Get Discharge Diagnosis Modal

The issue is whether to bring up the Discharge Diagnosis Modal a second time.
The issue would be if say Micro discharged someone and the discharge diagnosis modal therefore completed then you would want it to come up when say Tropical also discharge the patient

But if the patient was under Immune-Inpatients and Tropical and one of them had already done it then it maybe doesn't need doing again. (Note in reality this clinical care scenario quite unlikely)

Probably no harm in it coming up the second time though - especially as ultimately it should still get a consultant review. 
So I'm moving to close this.

**Comment by GabPoll** [comment]
yeah, agree. Also, because ultimately the final discharger is likely to be the most important in setting the final diagnosis.

**Comment by GabPoll** [comment]
still can't undischarge someone who is "discharged with follow up"
