### ISSUE TITLE
Add top corner growler display to all lists

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#487]
@davidmiller not sure how easy this is
But the little icon that you have added and which comes up when you action stuff on OPAT patients is extremely nice and a good touch for the user.

I would be keen to use that for all Add-Patients e.g on Tropical list etc etc
Helps the user know something has happened if the patient record is generated off screen and is a partial response to that old chestnut #26 

Thoughts?

**Comment by michaeledwardmarks** [comment]
This appears to be done.
And is way cool.

**Comment by GabPoll** [comment]
Ha! I've only just realised the x was a close button!
Agree fixed. Thx @davidmiller
