### ISSUE TITLE
Growler for Final Diagnosis Review

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#489]
Once diagnosis confirmed it might be worth showing this as the patient stays on the ward round until the end of that given round?

**Comment by davidmiller** [comment]
Deployed to elcid-opat

**Comment by michaeledwardmarks** [comment]
@davidmiller 
Unable to test as both the "Confirm Final Diagnosis" and the edit buttons for Primary/Secondary Diagnosis appear to be kaput on the FDR

**Comment by davidmiller** [comment]
?? They seem to work for me - I just confirmed a couple!

On 1 January 2015 at 20:07, Michael Marks <notifications@github.com> wrote:

> @davidmiller <https://github.com/davidmiller>
> Unable to test as both the "Confirm Final Diagnosis" and the edit buttons
> for Primary/Secondary Diagnosis appear to be kaput on the FDR
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/489#issuecomment-68496583>
> .
>



-- 
Love regards etc

David Miller
http://www.deadpansincerity.com
@thatdavidmiller <http://twitter.com/thatdavidmiller>
07854 880 883

**Comment by michaeledwardmarks** [comment]
Ok seems to work except one special instance which i will raise.
