### ISSUE TITLE
Constantly adding secondary diagnoses in Final Diagnosis Review via Discharge Diagnosis Review modal

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#491]
When the Discharge Diagnosis Review modal comes up, and you press confirm, the secondary diagnosis field is correctly auto-populated. However, if you go back to the Discharge Diagnosis Review modal and press confirm (e.g. if changed the primary diagnosis), it adds a duplicate secondary diagnosis. See J Doe 6764 for an example.

**Comment by davidmiller** [comment]
I believe a fix to this has been deployed to elcid-opat. Please do test !

**Comment by michaeledwardmarks** [comment]
Appears fixed!
