### ISSUE TITLE
Display allergies in all Antimicrobial and Clinical Advice Modals

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#492]
As happens for OPAT Review and OPAT Antimicrobials.

**Comment by GabPoll** [comment]
I thought I'd raised this before, but perhaps was by email.

Anyway +1 - looks odd at the moment in that allergy alerts appear when patient viewed in OPAT episode, but not if on regular team list. (though oddity maybe because i know what to look for)

**Comment by GabPoll** [comment]
Can I recommend a bit of a GUI enhancement here - allergy and header take up way too much screen real estate:
![screenshot of allergy header](https://cloud.githubusercontent.com/assets/4605661/5756962/adc44cc0-9cad-11e4-914f-58368b07db1d.png)

**Comment by davidmiller** [comment]
@gabPoll we can re-think/design, I think you're right. 

For Monday, would you rather have it as-is, or wait until the next deployment?

(Wait would be my mild preference - you've coped thus far, let's try not to roll this out too widly!)

**Comment by michaeledwardmarks** [comment]
Agree. Wait

**Comment by GabPoll** [comment]
agree wait as well

**Comment by davidmiller** [comment]
@GabPoll I think we should look at making the Clinical Advice modal wider (c.f. Obs Chart) && Then having a proper think about how to display what's going on there. 

We can meet up for coffee and come wireframe it < 0.4/1.0 ?

**Comment by GabPoll** [comment]
Agree re planning better Clinical Advice modal - I've been proponent for some time (#171).
Leaving this open for the allergy display. GUI issues will be separate.

**Comment by davidmiller** [comment]
@gabpoll do let me know if you think the antimicrobial/CA modals on the elcid04 server are a better use of space !

**Comment by michaeledwardmarks** [comment]
These look good.

**Comment by GabPoll** [comment]
Absolutely love how this is implemented in 0.4.

Slight refinement, hence re-opening, in CA & Antimicrobials, can you display the details in bracket, just like in Allergies modal. See Nina Netherton as example - when opening CA, should say Penicillin (rasg) in allergies section.

**Comment by michaeledwardmarks** [comment]
good suggestion

**Comment by davidmiller** [comment]
> Absolutely love how this is implemented in 0.4. 

 :D

**Comment by michaeledwardmarks** [comment]
lovely

**Comment by GabPoll** [comment]
thx @davidmiller , looks great.
