### ISSUE TITLE
Change elCID page header from "elCID - OPAT" to "elCID"

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#494]
Aide memoire, but can easily slip through.

**Comment by davidmiller** [comment]
@GabPoll I think this needs to go in our deployment testing docs, not here ! :)

**Comment by GabPoll** [comment]
Fair enough. Just popped in my head and didn't want to forget. Happy for it to be on hackpad. Thanks for adding to testing protocol.
