### ISSUE TITLE
Put filter for discharged last week ward round in alphabetical order

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#495]
As discussed.
Alongside this we will deactivate unneeded team tags to improve usability.

**Comment by davidmiller** [comment]
Deployed to elcid-opat

**Comment by GabPoll** [comment]
Looks fine to me. I suggest we leave this. We thought about restricting to just ID, immune & tropical, but this feature might be of use to others too in case of accidental discharge, etc... I'm thinking OPAT, perhaps haem or even ortho if Steve gets round to it. Thoughts welcome @michaeledwardmarks & @jonnylambourne

**Comment by michaeledwardmarks** [comment]
This looks good to me - closing.
I assume no way to exclude the meta-teams - i.e Immune
There are no pure-immune patients anymore they are all Immune-Inpatient or Immune-Liaison
Not a big issue.

**Comment by davidmiller** [comment]
FYI in the background all Immune Inpatient teams are also Immune. All Micro-Haem patients are also Micro etc.

(At least IIRC). 

As long as it's not a major issue I vote to leave this until feedback. (Especially given the volume of new tickets to triage ! :) 

I'd rather put effort towards e.g. save as draft than this.

**Comment by GabPoll** [comment]
Agree with parking this
