### ISSUE TITLE
Presenting Complaint button runs over into next column.

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#496]
Seen on ELCIDT

**Comment by davidmiller** [comment]
Not even in a column any more!

**Comment by michaeledwardmarks** [comment]
Any chance we could make the presenting complaint button a different colour/bold/something?
So it shows up more clearly if not completed initially.

**Comment by michaeledwardmarks** [comment]
Agree this specific issue could now be closed - but worth thinking about how me make the button prominent - as moving it off the in your face ness of the list itself may decrease completion
