### ISSUE TITLE
OPAT Review Field

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#497]
Sure this was discussed elsewhere but cant find issue.

I think it would be very sensible (and I think technically very easy? @davidmiller ) to do following

- [x] OPAT Review - Merge OPAT Plan/Discussion (as was done for Clinical Advice) - suggest drop Discussion
- [x] Activate Macros for OPAT Review as per Clinical Advice

If there is any chance of that happening with planned update (19th Jan 2015) then that would obviously be good but appreciate it may not be possible.

**Comment by davidmiller** [comment]
Deployed to elcid-opat

**Comment by GabPoll** [comment]
Perfect.

**Comment by michaeledwardmarks** [comment]
Excellent!
