### ISSUE TITLE
Test version - Observations 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#498]
Observations:
1) Is it possible to change terms ‘obs chart’ and ‘obs table’ to ‘Observation Chart / Observation table’

2) On the UCLH test version, BP on main screen displays correctly ‘(systolic/diastolic)’ but values display incorrectly in the obs table and obs chart (i.e diastolic / systolic)

3) On the Heroku app test version, the BP displays correctly on the obs chart and table.  But on the main menu screen, the figures display incorrectly.  i.e diastolic /systolic. When entered BP of 120/80, this displayed as 80/120 in the main menu screen, but displayed correctly everywhere else including chart and table.

4) In main menu screen could a space be added between SpO2 and the figure, for example, it currently displays as ‘SpO298%’ which is not easy on the eye to decipher the figure. 

5) On the obs chart display, the numbers on the far left of the table are not easily legible.

6) Can 'mmHg' be added to the units of measure for the BP

**Comment by michaeledwardmarks** [comment]
I'm moving these over to the specific Observations issues list - promise I'm not just shutting them @7575colli !

**Comment by 7575colli** [comment]
OK, we wont use this until it is fixed - The BP figures are back to front in some screens
