### ISSUE TITLE
OPAT test version - Gender 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#499]
Gender:
Please add look up list:
Male
Female
Unspecified 

J. L - Is 'unspecified' the correct terminology?

**Comment by michaeledwardmarks** [comment]
This already exists.
If you start typing it offers you the options, plus free-text.

**Comment by jonnylambourne** [comment]
From the 'health & social care information centre' (http://www.datadictionary.nhs.uk/data_dictionary/attributes/p/person/person_gender_code_de.asp?shownav=1)
'unspecified' should probably be 'Indeterminate' (unable to be classified as either male or female)

**Comment by GabPoll** [comment]
Gender lookup lists did not port over from heroku. Have added the categories. All seems to be working fine on elCID-test now. Writing here only for documentation
