### ISSUE TITLE
OPAT test version - Please change front of Opat

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#501]
There are quite a few places that display ‘Opat’, could these be changed to ‘OPAT’ please.

**Comment by davidmiller** [comment]
If you list where the places are, I can find them to change!

On 10 January 2015 at 13:00, 7575colli <notifications@github.com> wrote:

> There are quite a few places that display ‘Opat’, could these be changed
> to ‘OPAT’ please.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/501>.
>



-- 
Love regards etc

David Miller
http://www.deadpansincerity.com
@thatdavidmiller <http://twitter.com/thatdavidmiller>
07854 880 883

**Comment by 7575colli** [comment]
Menu screen: 
1) Opat Line assessment 
2) Opat Review
Il have a look for any others

**Comment by davidmiller** [comment]
These now capitalised...

**Comment by michaeledwardmarks** [comment]
Cool
