### ISSUE TITLE
OPAT test version - Line assessment 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#503]
Line assessment
This field isn’t currently functional. The field will need to directly correlate to a specific line that has already been added.  The line type, insertion date, external length will need to be pre populated.  I think that it will be best if I explain what I mean in person or on the telephone.  This isn’t critical to getting the database up and running… We can maybe fix this later if there isn’t time at the moment.  
VIP score should be look up list of:
0, 1, 2, 3, 4, 5.  Currently ‘0’ is missing from the look up list.

**Comment by michaeledwardmarks** [comment]
@7575colli 
Most people will only have 1 line at a time surely?

A look-up list of the number 0-5 is no different from simply typing the number!

**Comment by michaeledwardmarks** [comment]
As @7575colli has marked this as not critical I have moved this to the OPAT 0.2 milestone.
Personally I'm no't sure that the Line Assessment field needs to be directly linked to anything as
- People only tend to have 1 line at a time
- You can always use the date to link the data at the point of extracting the data

May have missed something?

**Comment by 7575colli** [comment]
Ok.  

I just tried to add '0' to the VIP section, it wouldnt accept the number - a straight line remained in the box.

Can you add '0' as an option to the VIP score please?

**Comment by 7575colli** [comment]
That was on the UCLH test verision BTW

**Comment by michaeledwardmarks** [comment]
@7575colli 
I see you point about VIP scores now.

@davidmiller 
Line Assessment Modal
Subfield: VIP Score
This is currently a Dropdown with options 1-5

- [ ] It needs an option for 0

Looked in admin but don't think this is an admin editable list (reasonable given it is just numbers!)

**Comment by michaeledwardmarks** [comment]
@davidmiller 
Same here as with antimicrobials and the line field.
Not sure these OPAT updates have deployed

**Comment by davidmiller** [comment]
Deployed to elcid-search

**Comment by michaeledwardmarks** [comment]
Fixed
