### ISSUE TITLE
OPAT test version - Format of dates

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#505]
I have noticed that there are lots and lots of date fields that display the date as DD/MM, others display date as DD/MM/YYYY.  My preference would be for all dates to be displayed as DD/MM/YYYY.  Looking at entry’s retrospectively without the year noted could be challenging to figure out when the entry was made and also hazardous because there it is possible that someone might misinterpret the information.

**Comment by GabPoll** [comment]
This is actually an inbuilt design of elCID, as far as i remember. System always records DD/MM/YYYY but for current year, in list view it displays DD/MM only. This was with purpose of saving screen space.

**Comment by michaeledwardmarks** [comment]
Hi Steve
I Agree with @GabPoll 
The logic at present is:
If year = current year then display DD/MM
If year = not current year then display DD/MM/YYYY

This was as requested by lots of users inc SMJ.
I propose we close this issue and review if people feel it needs to be looked at downstream.

**Comment by jonnylambourne** [comment]
another bit of elCID cleverness I had not appreciated

**Comment by 7575colli** [comment]
Very clever!
