### ISSUE TITLE
OPAT test version - Travel 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#506]
Travel:
Please add calendar to ‘travel date’ field

**Comment by GabPoll** [comment]
This might be a problem. @michaeledwardmarks correct me if I'm wrong, but having just the year for travel is deliberate as dates cannot always be specified (or need to be).

**Comment by michaeledwardmarks** [comment]
I agree with @GabPoll 

We frequently can't get the full travel history/dates from people - I'm strongly in favour of this being kept as it is. I know this to be true as I have just reviewed the travel history for > 2,000 patients and we often don't have the full dates, plus travel dates get very complex i.e saudi date A to B then Oman date C to D etc etc - you would need multiple calendars.

I would move to close this issue and review the need for this downstream.

**Comment by 7575colli** [comment]
Good point.  I agree
