### ISSUE TITLE
OPAT - Address / GP / Community nurse contacts

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#507]
Address:
Is it possible to make the address boxes longer?

I recall and earlier version having a field for adding community nursing services/GP/NOK contact details.  Wont the GP details be critical if any letters are to include a pre populated GP address? 
Can the Community Nursing contacts include:

Community Nursing team:
Named Nurse/Charge Nurse:
Referrals Tel: 
Referrals Fax: 
Email

Notes: (just a free text box please)

**Comment by michaeledwardmarks** [comment]
GP details for letter will actually be sucked from CDR so this doesn't matter for letters at all actually!

Not sure about the nursing contacts stuff but seems reasonable

**Comment by jonnylambourne** [comment]
agree
would be good to have community nursing team, as this info not readily available on CDR

**Comment by michaeledwardmarks** [comment]
I'm going to move this to OPAT 0.2 if that is ok as I don't think critical for go live next week

**Comment by 7575colli** [comment]
Ok, i understand.

**Comment by michaeledwardmarks** [comment]
FIXED on OPAT
