### ISSUE TITLE
OPAT test version - Rejecting patient 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#509]
When patient rejected from service, and review date added and confirmed, the small green bar that comes up in the main screen says: 
Rejected: Martin Boldwin. Patient will come up for OPAT review after NaN/NaN/0NaN

Should NaN/NaN/0NaN display the date?

**Comment by michaeledwardmarks** [comment]
@7575colli  Is this on the UCH Test version?

It works fine (and as you expected in your post above) on Heruko.

**Comment by michaeledwardmarks** [comment]
I have just tried this on elCID-Test version and it works fine for me.
Date displays correctly - did it on 3-4 patients.

@7575colli can I confirm you were accessing this via Firefox and not via Internet Explorer.

I'm going to close this issue at present but if you can tell me how you generated the error I will try again at replicating it.

**Comment by 7575colli** [comment]
I was using the Herku app version on my Mac

**Comment by 7575colli** [comment]
I just tried rejecting a pt on UCLH test version and it worked fine :)
