### ISSUE TITLE
OPAT test version - 'Ward round' bug 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#510]
When  i select 'ward round', 'OPAT review', 'start', this screen comes up:

([[ ward_round.name]])
[[episode.demographics[0].name]] [[episode.demographics[0].hospital_number]] [[episode.demographics[0].date_of_birth | shortDate]]

and I'm not able to operate any of the functions.

**Comment by michaeledwardmarks** [comment]
@7575colli 
Again I assume this on the UCH test version?
It works fine on Heroku.

**Comment by michaeledwardmarks** [comment]
Summarised these three bugs in #513 as they are presumabely the same thing for each of the ward rounds
