### ISSUE TITLE
OPAT test version - Final review bug

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#511]
When i select 'ward round', 'final diagnosis review' then select a patient, this screen comes up:([[ 

ward_round.name]])
[[episode.demographics[0].name]] [[episode.demographics[0].hospital_number]] [[episode.demographics[0].date_of_birth | shortDate]] Next  Episode [[ this_episode_number + 1 ]] of [[ total_episodes ]]   Previous

and i am unable to operate any of the functions

**Comment by michaeledwardmarks** [comment]
Summarised these three bugs in #513 as they are presumabely the same thing for each of the ward rounds
