### ISSUE TITLE
OPAT test version - Discharged last week 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#512]
when 'Discharged last week' 'opat' selected, no patients come up.  Could be that no patients were discharged last week :/

Also, is it necessary to have 
OPAT
OPAT referrals
OPAT current
OPAT referrals?
Would it be easier to have one tab for all OPAT discharges?

**Comment by michaeledwardmarks** [comment]
Summarised these three bugs in #513 as they are presumabely the same thing for each of the ward rounds

**Comment by michaeledwardmarks** [comment]
Just re-read this @7575colli !
This particular virtual ward round is for the inpatient teams.
OPAT can ignore it.
