### ISSUE TITLE
Ward Rounds Don't Work on UCH-Test Server

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#513]
See #510 #511 #512 

You get a comment like:

([[

ward_round.name]])
[[episode.demographics[0].name]] [[episode.demographics[0].hospital_number]] [[episode.demographics[0].date_of_birth | shortDate]] Next Episode [[ this_episode_number + 1 ]] of [[ total_episodes ]] Previous

**Comment by michaeledwardmarks** [comment]
The Final Diagnosis ward round seems broadly to work for me on elCID-Test via Firefox on VPN.
Bit difficult to test properly as I can't discharge new patients on to it #515

**Comment by michaeledwardmarks** [comment]
Same with Discharged Last week.
Seems to work for me but can test properly due to #515

**Comment by michaeledwardmarks** [comment]
OPAT Review Ward Round doesn't work for me at all on elCID-Test via VPN, Firefox.
I get:

"Ward Round could not be loaded"

Can't get debugging to work properly over VPN so unsure of precise error.

**Comment by 7575colli** [comment]
On UCLH Test version, I just tried 'Ward round' - 'OPAT review' and got:
Ward round could not be loaded

**Comment by michaeledwardmarks** [comment]
@7575colli agree
The OPAT review ward round is definitely not working on the elCD-TEST version on UCH server.

The other virtual ward rounds do work (and not relevant for OPAT anyway)

**Comment by michaeledwardmarks** [comment]
Fixed by #521

**Comment by michaeledwardmarks** [comment]
Does this mean an updated version is now on UCH server?
I will probably wait until the other things are deployed if that is ok and then I can test all in one go

**Comment by davidmiller** [comment]
Of course.

Not yet - am going to do the obs things & then deploy, do the lookuplists
ticket.

On 17 January 2015 at 17:55, Michael Marks <notifications@github.com> wrote:

> Does this mean an updated version is now on UCH server?
> I will probably wait until the other things are deployed if that is ok and
> then I can test all in one go
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/513#issuecomment-70376717>
> .
>



-- 
Love regards etc

David Miller
http://www.deadpansincerity.com
@thatdavidmiller <http://twitter.com/thatdavidmiller>
07854 880 883

**Comment by michaeledwardmarks** [comment]
So in my opinion everything seems pretty much fixed.

It would seem very sensible if easy to fix the Y-Axis on the observation chart as it is unreadable at the moment. It just needs to shift over about 0.5cm
https://github.com/openhealthcare/opal-observations/issues/12

We could then deploy and test all the recent changes and specifically these two other open issue:
#521 
#514

**Comment by michaeledwardmarks** [comment]
Still getting "Ward Round Could Not be Loaded" for OPAT-Review
Micro-Haem seems to work (although there are 176 patients.....)

**Comment by davidmiller** [comment]
@michaeledwardmarks - I'm looking into it !

**Comment by michaeledwardmarks** [comment]
Fixed.
