### ISSUE TITLE
OPAT Lookup lists not ported from Heroku to UCH Test Version

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#514]
I've just been playing with UCH Test version.

The reason that @7575colli was having issues with the lookup lists (reason for line removal, line complication, genders and a few other places) which I couldn't replicate on Heroku version is that the contents of the lookup lists haven't been copied over from the Heroku instance

Excellent spot @7575colli !

So although in the version on elCID-Test reason for removal has a lookup list in Admin it is currently blank.

@davidmiller we need to make sure we copy these over correctly...I know we have discussed merging lookup lists before #366

**Comment by davidmiller** [comment]
OK, so there were a few that hadn't been fully synced, or had gotten lost, but we should now be at all lookuplists synced to the UCH test server !

**Comment by michaeledwardmarks** [comment]
Whilst synced the Reason for Removal and Complications look-up lists (Line Modal) are not hooked up

**Comment by davidmiller** [comment]
They're both there for me now on ELCIDT - check again ?

**Comment by michaeledwardmarks** [comment]
Can't check until my VPN works again annoyingly

**Comment by michaeledwardmarks** [comment]
Fixed.

**Comment by michaeledwardmarks** [comment]
Whatever we did to fix other things has wiped these again.
I'm opening predominantly as a reminder for deployment as I know this can be fixed easily.
