### ISSUE TITLE
Unable to discharge double tagged patients

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#517]
Likely to be related to #515 .

Test RFH patient is tagged to micro-ortho and micro-haem. If I click discharge / remove on either list, get option to confirm discharge (correct), then get pop up "Item could not be saved" (incorrect) - patient should be removed from the list i am on - e.g.if on ortho list, should remove them from ortho list and then just be on haem list.

I can work around this, by unitcking the ortho team tick, the patient being left just on haem, but then i still can't discharge from haem list with same error as above. Net effect = undischargeable micro patient. Later, i'll get a chance to see if this is also problem in test version.

**Comment by michaeledwardmarks** [comment]
I think is more complicated.
For some old patients on the list I am getting the same problem.

Specifically these appear to be patients tagged to more than one team whose status has already been set as discharged (presumably they were discharged from another list).

If you then try and confirm discharge these patients you get an "Can't be saved error"
With following debugging

PUT http://elcid-opat.herokuapp.com/tagging/74/ 500 (INTERNAL SERVER ERROR)angular.28f401490ec3.js:8495 (anonymous function)angular.28f401490ec3.js:8291 sendReqangular.28f401490ec3.js:8025 serverRequestangular.28f401490ec3.js:11498 wrappedCallbackangular.28f401490ec3.js:11498 wrappedCallbackangular.28f401490ec3.js:11584 (anonymous function)angular.28f401490ec3.js:12608 Scope.$evalangular.28f401490ec3.js:12420 Scope.$digestangular.28f401490ec3.js:12712 Scope.$applyangular.28f401490ec3.js:18980 (anonymous function)jquery.3b80424646a7.js:4624 jQuery.event.dispatchjquery.3b80424646a7.js:4292 elemData.handle

**Comment by michaeledwardmarks** [comment]
I'm also getting a different problem - with new patients (as opposed to above problem with existing problems).

- Add patient tagged to two teams (Haem / Ortho)
- Discharge patient from Haem
- Patient is discharged from Haem list
- Patient is removed from Haem list (correct)
- Patient status is changed to discharged (correct)
- Patient has disappeared from Ortho list (incorrect)

Patient should still be on Ortho list but with Status as Discharged
If you find the patient via search function they are status discharged and still tagged Ortho (correct) but not showing up on list view.

There is no debugging error so guess this is a error in flow logic.

**Comment by davidmiller** [comment]
@GabPoll The reason "Test RFH" isn't discharging is that somehow they have become tagged to the Micro super-team (e.g. Micro-all, which still exists in the background) three times. 

I can fix this so that it will save, but It's concerning, as there should be no path for an episode to be tagged against a team multiple times. 

Can you recreate the issue at all with a fresh patient ? 
What did you do to them ! :)

**Comment by davidmiller** [comment]
@michaeledwardmarks If there are any specific patients on any list that can't be discharged, do send me the list & patient name combo & I'll investigate. 

The two micro team problem *you* describe above is different to @GabPoll 's - there were some cases where the parent team (e.g. Micro-all) was being incorrectly unassigned - which is why they disappeared from the other sub-team. (To appear on Micro-Haem you must also appear on Micro-All).

**Comment by michaeledwardmarks** [comment]
@davidmiller 
I thought that was likely to be the case.
I can't recreate @GabPoll error on new patients

**Comment by GabPoll** [comment]
agree, on new patients, this issue seems fixed.

There are various ways this workflow might be amended if / when there will be more micro involvement with elCID (at UCLH or elsewhere), but will cross that bridge when we get there.

**Comment by GabPoll** [comment]
BTW,  @davidmiller was it ok to close this issue, or were you working on something related to @michaeledwardmarks issues on this ticket.

**Comment by davidmiller** [comment]
So, actually the fix to the problem @michaeledwardmarks describes "fixes" the issue @GabPoll describes. 

Honestly it's more accurate to say that it hides it. 

I probably need to go away and figure out how the situation arises in the first place.

**Comment by davidmiller** [comment]
@GabPoll I've noted it in openhealthcare/opal#255

**Comment by michaeledwardmarks** [comment]
Is the issue I raised fixed?

**Comment by GabPoll** [comment]
i thought this issue was fixed. Have you spotted an error @michaeledwardmarks ?

**Comment by michaeledwardmarks** [comment]
Ok. Sorry just checking we had fixed both our issues within this thread. Agree fixed.
