### ISSUE TITLE
Add teams options also shows inactive team names

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#520]
So for example at the moment, there are only 3 active micro teams: blood cultures, ortho & haem. Add teams options also brings up options for C diff NEW, C diff 2014, etc.., etc...

Minor issue, but will want to fix going forward when limiting viewing rights of different users (can't find issue)

**Comment by michaeledwardmarks** [comment]
This just needs tweaking in admin.
It's related to the view/direct-add settings.
See now for example

**Comment by michaeledwardmarks** [comment]
Closing as fixed.
Added to Hackpad for next reboot to ensure we check the various options correctly.

**Comment by GabPoll** [comment]
Clarified.
- Altering Direct Add/Active in admin fixes this for the add patient modal
- Remains a problem if you then subsequently open Team Modal

**Comment by michaeledwardmarks** [comment]
Fixed!
