### ISSUE TITLE
Ward rounds auto start and then get stuck

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#521]
I'm getting worse at this bug description thing, sorry @davidmiller!

Load up micro-haem ward round, shows 3 patients on list and then a second later, goes to the first patient and then can't bring up list of patients and can't move to next patient.

Identical behaviour for OPAT review. Other ward rounds seem ok.

This is noted on elcid-opat. @michaeledwardmarks did you see this too on elcid-test (i.e. related to #513?). The errors described there seem different to this.

**Comment by davidmiller** [comment]
You mean that none of the three red buttons in the header work ? 

They all do for me ...

**Comment by michaeledwardmarks** [comment]
I agree with @davidmiller 

I think this is simply a (minimally) jarring user experience as a result of implementing https://github.com/openhealthcare/opal-wardround/issues/13

For me on both Micro-Haem and Opat -Review
- It jumps straight in at the first patient.
- The forward and backward buttons work
- The "Episode button" works - gives me a list of episodes for the ward round and I can jump between them.

I think @GabPoll might simply be seeing the list flagging quickly and then it jumping straight in. 
This is because these two lists (unlike FDR and DLW) don't have filters. I agree it is slightly jarring (why is that screen there, arghh now its gone) 

IIRC this is the desired behaviour based on the above meta-issue

I'm removing Bug and Priority 0 pending further feedback from @GabPoll

**Comment by GabPoll** [comment]
that is correct, none of the buttons work. DOing this on FF34.

**Comment by GabPoll** [comment]
absolutely not working on FF. Don't have chrome - could either of you check whether this is a browser thing - presuming both of you trying on Chrome? Important as wards use FF.

**Comment by michaeledwardmarks** [comment]
@GabPoll 
Can you turn debugging on and give result of output?

**Comment by michaeledwardmarks** [comment]
- Bug not seen with Chrome
- Bug seen with safari (don't know where debugging tools live in Safari).
- Bug seen via VPN on elCID-Test with FF

I think this is therefore likely to be the same bug as #513 which as @GabPoll describes only seems to affect Micro-Haem and OPAT-Review ward rounds.

**Comment by GabPoll** [comment]
thank you for confirming this @michaeledwardmarks .

Interestingly, @davidmiller this may help you, on IE11, the page looks just like described on #513. On FF it doesn't - screenshot below.
![screenshot of ward round fault](https://cloud.githubusercontent.com/assets/4605661/5757622/28d3f44a-9cb5-11e4-89ff-f061c1511190.png)

**Comment by michaeledwardmarks** [comment]
@GabPoll 
I can not replicate on native FF (version 35) on my macbook - buttons work fine.
But does occur via FF on VPN

**Comment by GabPoll** [comment]
Interesting @michaeledwardmarks - just updated to FF35 on Windows, and the bug still persists but now looks identical to #513 error.
I think we need input from @davidmiller now!

**Comment by davidmiller** [comment]
```javascript
Error: $scope.filters is not an object
$scope.set_visible_episodes@http://localhost:8000/assets/js/wardround/controllers/episode_detail.js:34:20
@http://localhost:8000/assets/js/wardround/controllers/episode_detail.js:43:8
invoke@http://localhost:8000/assets/js/angular-1.2.20/angular.js:3918:14
instantiate@http://localhost:8000/assets/js/angular-1.2.20/angular.js:3929:23
$ControllerProvider/this.$get</<@http://localhost:8000/assets/js/angular-1.2.20/angular.js:7216:18
ngViewFillContentFactory/<.link@http://localhost:8000/assets/js/angular-1.2.20/angular-route.js:913:26
nodeLinkFn@http://localhost:8000/assets/js/angular-1.2.20/angular.js:6648:13
compositeLinkFn@http://localhost:8000/assets/js/angular-1.2.20/angular.js:6039:13
publicLinkFn@http://localhost:8000/assets/js/angular-1.2.20/angular.js:5934:30
createBoundTranscludeFn/boundTranscludeFn@http://localhost:8000/assets/js/angular-1.2.20/angular.js:6059:21
controllersBoundTransclude@http://localhost:8000/assets/js/angular-1.2.20/angular.js:6669:18
update@http://localhost:8000/assets/js/angular-1.2.20/angular-route.js:871:25
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://localhost:8000/assets/js/angular-1.2.20/angular.js:12887:15
updateRoute/<@http://localhost:8000/assets/js/angular-1.2.20/angular-route.js:552:15
qFactory/defer/deferred.promise.then/wrappedCallback@http://localhost:8000/assets/js/angular-1.2.20/angular.js:11498:31
qFactory/defer/deferred.promise.then/wrappedCallback@http://localhost:8000/assets/js/angular-1.2.20/angular.js:11498:31
qFactory/ref/<.then/<@http://localhost:8000/assets/js/angular-1.2.20/angular.js:11584:26
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:8000/assets/js/angular-1.2.20/angular.js:12608:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:8000/assets/js/angular-1.2.20/angular.js:12420:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:8000/assets/js/angular-1.2.20/angular.js:12712:13
done@http://localhost:8000/assets/js/angular-1.2.20/angular.js:8315:34
completeRequest@http://localhost:8000/assets/js/angular-1.2.20/angular.js:8527:7
createHttpBackend/</xhr.onreadystatechange@http://localhost:8000/assets/js/angular-1.2.20/angular.js:8466:1
" "<div class="ng-scope" ng-view="" autoscroll="true">" angular.js:9997
```

**Comment by michaeledwardmarks** [comment]
These look ok on Safari - where previously the bug was seen.
I will wait until everything else has been fixed and all deployed on to UCH server before rechecking and closing this issue as appropriate.

**Comment by michaeledwardmarks** [comment]
Fixed
