### ISSUE TITLE
ending of final review ward round is non-intuitive

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#522]
imagine an fdr with 10 patients.
when you confirm diagnosis for patients from 10>2 you click conifrm, and then next, move on and the total episode number counts down.
when you do patient 1 you save the final diagnosis and are left on that patient.
you then have to click a menu buttpn (lists or ward rounds etc) to exit.

need patient 1 to close and some kind of notification that you are finished.

**Comment by davidmiller** [comment]
Honestly, I'm not sure having them drop off the ward round and the number drop down is the right thing to do.

Needs looking at medium term :)

**Comment by michaeledwardmarks** [comment]
I was thinking that when there are no remaining unconfirmed diagnoses that clicking the next button could say " no more to review would you like to go back to the main screen" / the next button be replaced by an end of ward round button. 
.
Pros and cons of counting people off list:
Pro - makes it easy for someone to review a month's patients in several chunks without lots of re-reviewing.

Cons - difficult if you save the diagnosis and change your mind!

**Comment by GabPoll** [comment]
Compromise could then be no count (because it sort of does that anyway in the total patients left on the round), but the notification when you've hit the end. Currently it just sits on the final patient and you can't go any further.

**Comment by michaeledwardmarks** [comment]
Same also for OPAT review

I'm in favour of
- [ ] not counting down the number during the ward round itself
- [ ] on last person (e.g episode N/N) that  the next button be replaced by an end of ward round button.

**Comment by davidmiller** [comment]
I'm in favour of both of these, as well as 

* No previous button on the first person
* Name/number filter for names on list when you view the list (like on team lists)

I think these should be three separate issues on the wardrounds issue list.

**Comment by michaeledwardmarks** [comment]
Closed and replaced by Issues 15-18 on the ward rounds issue list
