### ISSUE TITLE
OPAT Discharges should set discharge date

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#524]
Discharge (Move to review wardround) doesn't always set a discharge date. 

Make sure we do !

**Comment by davidmiller** [comment]
We now set Discharge dates on elcid04-test @michaeledwardmarks @gabpoll !

**Comment by michaeledwardmarks** [comment]
Cool!
What should I be reviewing?
(NB also my comment re #629)

**Comment by davidmiller** [comment]
Complete therapy for an OPAT patient.
Search patient
Discharge date is set 
There is no step 4 !

**Comment by michaeledwardmarks** [comment]
ok!
Does that mean out of interest that you can use Discharged Last Week for OPAT (for a slightly different function to the OPAT review ward round)

**Comment by davidmiller** [comment]
Probably, but it's not supported behaviour ;)
