### ISSUE TITLE
Growler Date

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#525]
When setting review date in OPAT the growler displays MM/DD/YYYY

This is isolated to the growler only.

**Comment by GabPoll** [comment]
Similar problem in #456

**Comment by michaeledwardmarks** [comment]
Is this deployed anywhere for testing

**Comment by davidmiller** [comment]
not yet - I'm going to do a bunch at the same time

On 19 January 2015 at 17:49, Michael Marks <notifications@github.com> wrote:

> Is this deployed anywhere for testing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/525#issuecomment-70533812>
> .
>



-- 
Love regards etc

David Miller
http://www.deadpansincerity.com
@thatdavidmiller <http://twitter.com/thatdavidmiller>
07854 880 883
