### ISSUE TITLE
OPAT Current has ?pre-existing patients on it

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#527]
Patients who were not added to OPAT appear on the OPAT current list

Hypothesis 
- used to be possible to set OPAT as a category for any patient.
- there may be patients (including discharged ones) who have category == OPAT
- when the OPAT list/tag gets turned on these patients get sucked on to that for some reason

In the short term we could get around this by just removing them/deleting them from database.

- [x] The OPAT lists (Referral/Current/Follow-up) should be blank after deployment (even if this is achieved manually)

**Comment by davidmiller** [comment]
I'm not sure quite what happened here, but having just re-run the update on ELCIDT, we have no OPAT patients. 

Move to close.

**Comment by michaeledwardmarks** [comment]
Closing
