### ISSUE TITLE
All new patients appear on FDR including undischarged ones - whose Final Diagnosis can not be confirmed

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#528]
Two linked issues:

As soon as you Add a new patient 
- Regardless of what list you are added to all new patients appear on the FDR (including Micro, OPAT etc) immediately following adding them

- For Patients appearing on FDR this way the Final Diagnosis can not be confirmed until the patient is discharged 

- Once you discharge a patient then you can confirm the Diagnosis. 

For example
- Add patient on Micro-Haem
- They appear on FDR (if you don't apply a team filter)
- You can not set discharge diagnosis
- Go back to list and discharge patient
- They are still on FDR (unfiltered)
- You can now set/confirm the discharge diagnosis

- [ ] Only Tropical / ID-Inpatients / Immune-Inpatients should appear on the FDR
- [x] You should not appear on the FDR until you have been discharged

**Comment by michaeledwardmarks** [comment]
- Fixing this turns out to be computationally slow when X is large.
- In particular X is large at present as all prevoiusly discharged people now have a blank Primary Diagnosis

Options  and solution suggestions for comment from @davidmiller 
- [ ] Short term make confirmation of diagnosis available via DLW for last weeks patients

- Filters could be applied BEFORE elCID tries to identify relevant episodes. This makes searching them computationally less expensive

- In my mind I wonder about a hidden field
'Diagnosis Completion Stage'
On creation of episode this is set as 1 (Intentionally blank)
On filling in the Discharge diagnosis this is set as 2 (provisional)
On confirming the diagnosis this is set as 3 (final)

FDR should then only identify records where this field == 2
AFAICT at the moment the system doesn't distinguish positions 1&2 above and this results in lots of unwanted people on FDR.
Not clear to me if this is computationally cheaper to run but AFAICT would stop loads of people building up who meet the criteria for FDR.

**Comment by davidmiller** [comment]
My thought now is that we end up using Discharged last $Period and no longer having an explicit FDR round - IIRC that was @michaeledwardmarks plan all along ? :) 

If so, can we close this and add the steps needed to make DLW fit for purpose - or is it already?

**Comment by michaeledwardmarks** [comment]
That sounds good.
I'll make a specific DLW issue.
