### ISSUE TITLE
Micro-Haem Ward Round pulls historic patients

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#529]
Currently there are about 15 patients on the Micro-Haem list
But in the micro-haem ward round there are 176
Looking in Admin and sorting by Tag I note there are 176 Micro-Haem tags

There are therefore patients who have been discharged/removed from the list but for some reason their Micro-Haem tags have not been deleted - they still get pulled on to the Micro-Haem ward round.

I have tried discharging a current Micro-Haem patient and can confirm this does result in their Micro-Haem tag going.

I assume this in some way reflects an error that crept in at one of the points we changed either tagging or discharge error.

Therefore this issue can be fixed by deleting these tags.
This can be done fairly simply via the Admin Interface if needed.

**Comment by GabPoll** [comment]
@davidmiller will that solution hinder the way these patients are recalled in data extraction in the future?

**Comment by michaeledwardmarks** [comment]
At the moment the tag SHOULD be deleted when you discharge someone.
IIRC extract finds historic tags

**Comment by michaeledwardmarks** [comment]
Further I confirm that deleting a tag in the admin interface does indeed remove patients not currently on the list who are mistakenly showing up on Micro-Haem Ward round

**Comment by GabPoll** [comment]
though thinking it through, will extraction still work as it extracts people historically tagged as micro-haem at some point in their time?

Absolutely vital we don't lose those patients from haem data extract.

**Comment by GabPoll** [comment]
asynchronous githubbing, sorry @michaeledwardmarks

**Comment by michaeledwardmarks** [comment]
We should re-migrate the live database and re-check this since I tidied up Vanyas list

**Comment by GabPoll** [comment]
@davidmiller, can you re-migrate the live list to test server Monday am?

**Comment by michaeledwardmarks** [comment]
From @davidmiller 

There are old patients who turn up on the MH Ward round, but not the MH List.

All the cases I have found, this is because they were discharged a long time ago (Mar 2014) and they have the MH-tag but not the micro-all parent tag.
The MH-tag is pointless for these patients because they won’t actually turn up on any list ever (doubly because both they’re discharged, and don’t have the parent tag)

Option 1) I find episodes matching this criteria && add the micro-all tag && a clinical person eyeballs these episodes to decide what to do. (I can send you a list)
Option 2) I just remove the micro-haem tags.

**Comment by michaeledwardmarks** [comment]
Suggestion from @michaelmarks

Option 2.1
We know who is currently on the live list
Generate list of people meeting criteria that are causing an issue for the VWR (Micro-Haem, no Micro-All)
Cross reference this with the live Micro-Haem list
We anticipate (if I have understood) that none of them should be on the live list
We enact option 2 above

**Comment by GabPoll** [comment]
agree. Option 2 best - remove current MH tag. They will still have historical MH tag for extraction. This is just a presentation issue. These are old MH pts that need to
a) not be seen on list - i.e. MH tag needs removing
b) not be seen on WR - i.e. MH tag needs removing
c) be searched as MH pts in future for data extraction - historical MH tag persists on elCID database

@davidmiller please confirm i have that correct, thank you.

**Comment by davidmiller** [comment]
@gabpoll

a) Are already not on list because parent micro all tag is not present
b) Precisely
c) Precisely

**Comment by michaeledwardmarks** [comment]
Fixed by DM.
Leaving open as reminder for fixing this evening on live server
