### ISSUE TITLE
Sub-team tags are not added when re-opening an old admission on list view

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#532]
Specifically re-opening of old admissions
Growler say admission created but you can't see the episode on the list you are on

I have found the cause which is explained below:

Investigation findings:
- Select list Immune-Inpatients
- Add a new patient (i.e 0099009900)
- Look in Admin: Taggings
- Patient has a tag for Immune-Inpatients & Immune
- Discharge patient
- Add patient (0099009900)
- Select Re-open old episode
- Growler says added
- Patient not on list
- Go to search page
- Search for 0099009900
- Patient found as expected
- Single patient view shows patient has Immune tag but NOT immune-inpatient tag even though user was on Immune-inpatient list when re-opening the episode
- Open admin: as expected the patient only has an immune tag, should also have immune-inpatient tag

Compare with same process on Tropical.
- Only 1 level of tags.
- When re-opening an episode on Tropical top-level-tag is added (as it is in the immune example)
- As there are no sub teams, display on list determined only by presence of top-level tropical tag
- Therefore patient shows up when re-opening admission

Solution
- [ ] Re-opening an episode should add both the meta-tag and any sub-tags appropriate to the list the user is on when they re-open the episode

**Comment by michaeledwardmarks** [comment]
So this looks fixed on the elcid-Search deployment

@davidmiller I always worry slightly when some things are deployed to one place and some to another. I realise this may be irrational.

Is elCID-Search equivalent to the proposed deployment currently?

**Comment by davidmiller** [comment]
I think elcid-search == ELCIDT + the fix to this issue.

On 20 January 2015 at 21:09, Michael Marks <notifications@github.com> wrote:

> So this looks fixed on the elcid-Search deployment
>
> @davidmiller <https://github.com/davidmiller> I always worry slightly
> when some things are deployed to one place and some to another. I realise
> this may be irrational.
>
> Is elCID-Search equivalent to the proposed deployment currently?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/532#issuecomment-70733966>
> .
>



-- 
Love regards etc

David Miller
http://www.deadpansincerity.com
@thatdavidmiller <http://twitter.com/thatdavidmiller>
07854 880 883
