### ISSUE TITLE
Antimicrobials calendar cannot be operated by keyboard by default

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#533]
(suggested by VG)

Workflow:
1) click on new antimicrobial
2) type in a drug name
3) tab to the start date field
4) unable to choose a date by moving cursor keys and then tabbing away to next field
5) same issue with drug end date field.

Whilst we deliberately took off the default start date to today, if person uses keyboard at this point, the date selector should appear, starting on today.

**Comment by GabPoll** [comment]
still an issue in 0.4

**Comment by davidmiller** [comment]
All the calendars should be back to keyboard navigable as of 0.6.3 !

**Comment by GabPoll** [comment]
i confirm they are keyboard navigatable. Good de-regression!
