### ISSUE TITLE
Unable to filter extract search by date of clinical advice given

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#534]
gives error

**Comment by davidmiller** [comment]
@GabPoll Where is this - live ?

**Comment by GabPoll** [comment]
It's on both live and elcid-opat. Very likely a residual bug that we've never tested.

A bug finding sprint on extract is recommended. There are some fields that don't search well. Not priority for now, just documenting.

**Comment by davidmiller** [comment]
We'll need to deal with this - will come as part of wholesale re-write next year. Closing this specific ticket.
