### ISSUE TITLE
Search interface will need expanding as new fields become available

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#535]
e.g should be able to extract based on Primary Diagnosis or OPAT specific fields

**Comment by davidmiller** [comment]
The advanced search fields are now dynamic rather than specified by a programmer

**Comment by GabPoll** [comment]
@davidmiller dynamic in what way - i can see more categories, others are missing. Is there somewhere in admin where these can be changed now?

**Comment by davidmiller** [comment]
@GabPoll What do you think is missing ?

**Comment by michaeledwardmarks** [comment]
Not sure how I should be testing this although clearly there are lots more things to search via now!

**Comment by davidmiller** [comment]
So, you can't test that new records will dynamically be added, you have to trust me!

For reference, it's this change! : https://github.com/openhealthcare/opal/commit/71780fd6c678263835459b78cf4bd56c7a70055e#diff-780502cb98033a4d019da13401972604L74 

But the fact that e.g. OPAT Might be one way.

It's plausible that we might want to specifically exclude some record types from the advanced search - so if there are any you think we can lose then that would be good to know

**Comment by GabPoll** [comment]
@davidmiller "Teams" is missing in advanced search

**Comment by davidmiller** [comment]
@gabpoll - Great spot - we need teams !

**Comment by davidmiller** [comment]
Teams are back on elcid04-test!

**Comment by GabPoll** [comment]
teams back on. not sure if you want to keep this issue open for now.

**Comment by davidmiller** [comment]
Not really ! :)
