### ISSUE TITLE
Shouldn't need to hard refresh following updates

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#536]
Some users expereincedy need for hard refresh following update.
This gives mistaken view that system is broken.

**Comment by GabPoll** [comment]
+1

**Comment by davidmiller** [comment]
This is fixed and added to the release plan on hackpad - I think you just have to take my word for it that this is no longer an issue !

**Comment by davidmiller** [comment]
Well - until we deploy to UCH servers at least...
