### ISSUE TITLE
Walk In Letter

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#537]
I think the letter function is key for the Doctors here because otherwise we are asking them to double enter. In fact much more key than for OPAT really.

In first instance I think a copy-paste clipboard function would be fine..

All the heading and stuff come via CDR so can be ignored.
Template is approximately.

Re: NAME - DOB

We saw your patient  on DATE at the Hospital for Tropical Diseases walk-in clinic.

Travel: (ALWAYS SHOW THIS HEADING)
LIST OF COUNTRIES - DATE OF TRAVEL

Presenting complaint:
The patient reported a (SHORT/LONG - we can choose words for each of the time-frames in the symptoms modal) history of SYMPTOMS FIELD. On examination REPORT ANYTHING ABNORMAL FROM EXAMINATION MODAL. (If NAD button used then replace sentence with - examination was unremarkable).

Investigations:
HIV POCT - RESULT
Malaria Film - RESULT
Stool OCP - RESULT

Outstanding Investigations
Enter any other investigations the user has entered here

Management:
It was felt that the most likely diagnosis was DIAGNOSIS FIELD. 
IF - Advice subfield (MANAGEMENT Modal) completed then add line:
He was advised to ADVICE
If - Antimicrobial prescribed (Antimicrobial Modal) then add the line:
I have prescribed DRUG
Depending on what follow-up was selected (MANAGEMENT modal)
We have/have not booked follow-up in INSERT CLINIC // The patient was admitted to the ward

**Comment by davidmiller** [comment]
@michaeledwardmarks Still need to tackle the problem of nobody knowing how /having access to create CDR letters though ?

**Comment by michaeledwardmarks** [comment]
The way this works at the moment is in CDR you say "OPEN LETTER"
It then loads a generic letterhead, gp details etc etc.
Under that you can then have some pre-written bits of information (so the walk in one has the word travel half-way down the page etc).
The user completes letter and saves it. 
CDR does some renaming of the file etc etc.


Letter creation = 2 issues for us
- [ ] Transform the information on elCID in to a format that it can be pasted in to word - in a way that replicates the current letter format 

- [ ] Getting IT to change the template so the page is blank except the header and therefore you can just copy and paste information in to it.

I can begin conversations about altering the walk in template. This should be straightforward really.
To make this work though I need to know we can take the elCID data, format it and paste it in to a word document.

**Comment by michaeledwardmarks** [comment]
So durations - I think if they select options 1-2 we insert the word short, 3-4 sub-acute and 5 long.
People can always edit.

**Comment by michaeledwardmarks** [comment]
Examination/Clinical Findings:

- Lymphadenopathy
There was no lymphadenopathy
or 
There was DETAILS lymphadenopathy 

- Jaundice
The was no evidence of jaundice
or
The patient was clinically jaundiced

- Dehydrated
(Only if YES selected): The patient was clinically dehydrated.

- Rash 
(Only if YES selected): There was a RASH-TYPE rash over the RASH-DISTRIBUTION

- Cardiovascular
If NAD - Cardiovascular examination was normal.
If not - Examination of the cardiovascular system revealed X

- Respiratory
If NAD - Respiratory examination was normal.
If not - Examination of the respiratory system revealed X

- Abdomen
If NAD - Adbominal examination was normal.
If not - Examination of the abdomen revealed X

- Neurological
If NAD - The neurological examination was normal.
If not - On neurological examination the patient had 

- Oropharynx
If NAD - The oropharnyx was normal.
If not - On examination of the oropharnyx the patient had 

Other Findings
(IF NOT NAD): DETAILS were also noted.

**Comment by michaeledwardmarks** [comment]
Ideally, if multiple of the Cardiovascular/Respiratory/Abdomen/Oropharnyx.Neurology were NAD then it would simply display:

Examination of  A>N was normal.

**Comment by davidmiller** [comment]
Updated letter deployed to elcid04-test with examination and symptom duration mappings

**Comment by michaeledwardmarks** [comment]
This is a huge step forward.

__Minor Things__
_Depending on what follow-up was selected (MANAGEMENT modal)_
We have/have not booked follow-up in INSERT CLINIC // The patient was admitted to the ward

_Observations_
We can't currently add observations via list view (which is where we want to add them) (see #628 )
But once we can then these should appear as the first line of the Examination section of the letter
Formatted as ideally a single line
Temperature TEMP Blood Pressure SYSTOLIC / DIASTOLIC Pulse PULSE Respiratory Rate RESP RATE SpO2 SpO2

**Comment by michaeledwardmarks** [comment]
@davidmiller
Should the minor points above be fixed in the current version of the letter on elcid04-test?

**Comment by davidmiller** [comment]
@michaeledwardmarks should now be deployed !

**Comment by lauranabarro** [comment]
Letter is totally wonderfully awesome guys!

Some very anal points:

1) I don't think we should "feel" a diagnosis. Its not like we feel these things in "our waters". Could it be changed to "The most likely diagnosis is....".
2)There are some funny capitals that pop up in the letter such as "The patient was asked to Return if unwell"
3) The letter should end with " With best wishes" or something similar, then people can sign. 

Sorry if this is the wrong place to have written this or if these points have already been raised

Inspirational work guys!

**Comment by davidmiller** [comment]
@lauranabarro So, The feel vs. is, I've changed - will deploy later today.

The capitals thing is interesting. 
The capitals come from the advice that the user typed.
I think a better formulation might be similar to that used in the list display e.g. 

> Advice: 
> [[ insert advice here ]]

It's really hard to work out when it is & isn't appropriate to pull the advice field into a sentence.

**Comment by davidmiller** [comment]
These have been deployed to elcid04-test - I think we've covered everything in this ticket so far ! :)

**Comment by michaeledwardmarks** [comment]
Just amazing.
M
