### ISSUE TITLE
Optmising add record for OPAT

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#539]
Add Patient Modal for OPAT modal
Would be helpful to have a location sub field - free text box would be fine
Display this in location section of the list
Helpful for @7575colli to go and review people on the ward

**Comment by davidmiller** [comment]
Wait, what ?

Aren't OPAT patients outpatients?

**Comment by michaeledwardmarks** [comment]
Many of the referrals are often inpatients initially (hence the import function!)
Steve has the referral list and he goes to see them to assess suitability - hence why this field is useful for them day to day (although not of any long term interest so could just be a free text box)

**Comment by GabPoll** [comment]
just wondering, are any of the OPAT patients transfers from other hospitals? If so would need to add them as an inpatient first?
Thoughts @7575colli @jonnylambourne 
Don't know why it just popped in my head

**Comment by michaeledwardmarks** [comment]
Unnecessary.
For OPAT you can either directly add or import an inpatient.
So for external patients you just direct add

**Comment by GabPoll** [comment]
Fine, ignore my previous entry then, sorry.

**Comment by michaeledwardmarks** [comment]
@davidmiller not sure if this is so trivial as to be done tomorrow AM with the hosp number & cache thing?

**Comment by GabPoll** [comment]
consolidated into #589
