### ISSUE TITLE
Nurse view for Walk-In

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#540]
Discussed with Di (lead walk-in nurse @HTD) 
Drop the following fields from the Nurse view:
Clinical Findings
Diagnosis
Antimicrobials
Management

(NB Management and Diagnosis for nurse led care will be captured by the nurse led care modal)

**Comment by davidmiller** [comment]
On elcid04

**Comment by michaeledwardmarks** [comment]
Perfect.
Closed
