### ISSUE TITLE
Hospital numbers are not saved properly for OPAT

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#541]
can't reproduce everytime but for OPAT on the live server the hospital number is not saving properly
We should try and fix and deploy tonight as this is a big issue
I'll investigate more

**Comment by michaeledwardmarks** [comment]
Specifically this is for the hospital number added via the add patient modal
If you then go and open the demographics field and re-enter it then it is saved

Can't reproduce on the non-OPAT lists

**Comment by michaeledwardmarks** [comment]
Same for Walk-In
Again only via the add-patient modal

**Comment by michaeledwardmarks** [comment]
Fixed for OPAT.
Leaving open for Walk-In.

**Comment by davidmiller** [comment]
Now also fixed for Walk In

**Comment by michaeledwardmarks** [comment]
Fixed and closed
