### ISSUE TITLE
Nurse Led Care Modal

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#542]
Nurse led care modal needs completing:

In first instance can we have 

Q1:
Reason for nurse led care - drop down (admin-editable please)
- Inappropriate referral
- Needs referral to consultant clinic
- Needs to be seen in post-tropical screening clinic
- Treated by nurse

Q2 (if treated by nurse):
- Diagnosis (could/should populate the diagnosis field)
- Treatment (free-text - call field "Treatment given by nurse")

I have now discussed this with nurses and I think these cover the main points

**Comment by davidmiller** [comment]
Deployed to elcid04.

Available in next modal for patients on triage list.

**Comment by michaeledwardmarks** [comment]
So so beautiful
