### ISSUE TITLE
Admit to team modal doesn't work - at end of walk-in appointment

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#544]
Select End of Appointment on doctor view
Select admit to team
List of teams comes up but can't do anything beyond that.

**Comment by michaeledwardmarks** [comment]
Specifically you can select a team to admit them under

**Comment by michaeledwardmarks** [comment]
This is amazing.

Two minor questions for @davidmiller 
1) Is this a whole new episode (e.g this isn't like the current OPAT-Inpatient Add bug)
2) Assuming answer of 1 is yes, could we display category==Inpatient for the newly created episode (I know it doesn't actually effect episode type, more from point of view of display)

**Comment by davidmiller** [comment]
My understanding is that it creates a new inpatient episode.

If it's not displaying then I will check that this is the case.

**Comment by davidmiller** [comment]
@michaeledwardmarks 

The episode category is now being read from the right place post openhealthcare/opal#245

**Comment by michaeledwardmarks** [comment]
Fab.
Very minor thing - when you do this
- for the new inpatient episode
- the category displays as "inpatient" not "Inpatient"

**Comment by davidmiller** [comment]
OK - will capitalise :)

**Comment by davidmiller** [comment]
Actually was all categories not being capitalised, unrelated to walk-in.

Fixed now & deployed to elcid04-test
