### ISSUE TITLE
Travel field in walk-in

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#546]
Needs following extra subfields:

1) Malaria Prophylaxis (Yes/No)
If Yes:
2) Drug: Dropdown (admin editable please!)
3) Compliance: Complete/Incomplete

**Comment by michaeledwardmarks** [comment]
@davidmiller 
This is close to perfect - it looks to me like the Drug drop down is currently hooked up to the main antimicrobial lookup list:
OPAL
Lookup List: antimicrobials

Could it be hooked up to a specific one - reason is there are essentially only 4-5 drugs used an prophylaxis so an abbreviated list would be good.

**Comment by davidmiller** [comment]
I'm strongly against a second lookuplist for drugs.

I don't think we'll get subsets of lookuplists for 0.4. 

We can discuss later on how we address the conceptual issue of e.g. "Malaria drugs" ?

**Comment by michaeledwardmarks** [comment]
ok. Will close this at this time then.
