### ISSUE TITLE
Defining use case and needs for Groups and Roles

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#547]
We need to think about this in the future in order to be able to more easily audit contributions of different teams to overlapping patient groups. 

Example:

Recent extract of ID-Liaison patients
Count number of episodes of clinical advice
Realise that lots of that advice is from Vanya as the patients are also under Micro-Haem
Have to manually look at list of users to work out which advice is attributable to ID as opposed to Micro-Haem

Thoughts:
1) Can you work out which user wrote each entry (different potentially from the entry in the discussion field - e.g in the X discussed with Y  bit you sometimes just get initials, but clearly we could identify the underlying user).

2) Can we have a role type category e.g Vicky Jonhston is an ID/Trop doctor. Show me the clinical advice entries made by any ID/Trop doctor.

A solution is also going to be key if we want some kind of Dashboard/regular report for ID-Liaison or any other team.

**Comment by michaeledwardmarks** [comment]
Currently doable manually but
1) non-intuitive
2) time-consuming

**Comment by GabPoll** [comment]
Currently date filters are easiest way to do this for patients who have been under serial care by different teams e.g. micro pt, then taken over by ID, etc.... This is clearly sub-optimal for parallel patient care, the most common scenario.

**Comment by GabPoll** [comment]
I think the role type category is the way to go here. The problem are the junior doctors - they keep changing, so their role would need to keep being updated. E.g. Vicky might do the ward round, but the clinical advice entered by a FY1. If we can police this (Maggie), then this would be a good solution. So any entries by FY1 x who works in ID, are labelled as such.

Would require a new (hidden?) field in Clinical Advice - "Team giving clinical advice". The issue becomes how much you drill down that team definition. For example, Vanya could be micro-haem. But what happens if he's on call and he writes something about an ortho patient? Solution could be that we restrict just to parent teams. Micro vs ID vs Immune would work ok during daytime hours. What about on call - cross on calls between Immune & ID SpRs?

**Comment by GabPoll** [comment]
One other solution is that every log in episode, user is asked to define their role. Perhaps can have it so it auto-defaults as their previous state, but with option to change. That feels prone to problems that approach!

**Comment by michaeledwardmarks** [comment]
I think we only need to distinguish Micro vs not-Micro probably
People move relatively infrequently between these roles
Not keen on setting role at time of login

**Comment by GabPoll** [comment]
Ok, agree with that. Let's restrict to parent team roles for now.
So to do list is:
- [ ] Add category in Users section of admin to define "Team assigned to". If this looks up parent team list, that's a bonus
- [ ] Add hidden field "Team issuing advice" to clinical advice modal that pulls "Team assigned to" entry for that user for each clinical advice entered. Same way as "Advice given by" pulls in the name of that user.
- [ ] Ensure "Team issuing advice" can be extracted in search and, preferably, also filtered in advanced search.

**Comment by michaeledwardmarks** [comment]
Good suggestions.

Slight modification is the fact that "Team assigned to" doesn't have to map exactly to the tags.
For inpatients (where this role>linkage to an entry issue is found) we probably only need

- Microbiology Team
- Infection Team
+/- Immune Team

Then to solve my particular issue you would do:
Tagged ID-Liaison
Clinical advice entered by member of Infection Team

**Comment by GabPoll** [comment]
yeah, happy with modification, as it also gets round cross cover between ID / Immune team doctors.

For political reasons, change "Infection Team" to "ID Team". I think technically ID, Immune & Micro all considered the Infection Team.

**Comment by michaeledwardmarks** [comment]
Worth saying this might in the future be layered
e.g
User X = 
ID Team 
& 
Consultant

or User Y =
Micro-Team
&
Registrar

We have a use case for "Teams" as a user setting
Plausible in future that we might also have one for "Job/Seniority" setting

For the moment I think just the top layer ("Teams") is needed.

**Comment by michaeledwardmarks** [comment]
Although I get that this isn't a walk-in issue, I think basic role/team user characteristics needs to come sooner rather than later hence putting in that milestone ATM

**Comment by michaeledwardmarks** [comment]
@davidmiller 
Specifically looking in user profile sections I see there are
1) Groups
2) Roles

Is one of these the solution to this?

**Comment by davidmiller** [comment]
The way this has been conceived of is: 

(Done) A user has n roles where role ==:

* Consultant
* Clerk
* F1
* Clinical lead for research study $X

A user can be a member of n teams where team == : 

* Division of infection
* Micro
* ID Liaison
* OPAT 
* Research study $X researcher team
(Teams here maps to teams in the admin)

As I understand your proposal, it seems that you're suggesting that no user will ever be in > 1 teams, and that there should be another thing called teams, which is not linked to the current "teams" ?

Have I misunderstood?
How sure are you that we will only ever want infection & micro ? & how does that relate to the general purpose roles & teams features that we may as well build?

**Comment by michaeledwardmarks** [comment]
__Teams__

- I think helpful to think of 'regular teams' ("HTD""Micro""Immune" perhaps) and 'special-research teams' (e.g for research)
- People will need to be able to be a member of more than 1 team
- People may come and go from special-research teams
- Movement between 'regular teams' would be relatively uncommon
 - For consultants they tend to have fixed jobs so unlikely to switch regular 'teams'
 - SpRs might change team but unlikely to be a member of multiple teams simultaneously I think
 - More junior people only likely to be a member of one team as they only work for inpatient teams

To give specific examples I would like to be able to
- See clinical advice given by HTD people - based on 'regular team' (regardless of which list the patient was/wasn't tagged to)
- See/not see a specific research list - based on 'special-research team'
- We could in theory deactivate other lists based on regular teams 
  - e.g Only Micro-Team people see Micro list etc
  - e.g Only some people see the Discharged Last Week Ward Round etc

__Roles__
- I think roles are most likely to be useful in Research-Special Teams
  - Scientist
  - Nurse 
  - etc
- Being a member of the team makes the specific list show up
- Your role in the team determines your view of this list

- There may be cases where we limit routine stuff within regular teams but I can't think of an example currently

**Comment by davidmiller** [comment]
I'm 99% sure that we came to an agreement on Skype that we were basically all in agreement, just using different terms to mean the same thing?

Broadly speaking we have the high level framework in place, there are a couple of obvious additions that we'll make as soon as we have genuine use cases.

I move to close?

**Comment by GabPoll** [comment]
ok, let's close this, and then test the framework once we have a use case.
