### ISSUE TITLE
Improve display of very long OPAT Review entries on list view

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#548]
Seen in OPAT
Partly this is due to just copying and pasting an old excel sheet entry when transitioning to elCID.
But similar behaviour has been seen with de-novo entries on Micro-Haem

**Comment by GabPoll** [comment]
what's the behaviour? On list view it should only display date, name of person giving advice and person receiving advice - i.e. the display should be independent of the content of the advice section.

**Comment by michaeledwardmarks** [comment]
OPAT review not clinical advice - sorry for confusion.
Changed title of issue.

Probably it should just show:
Date
Name
Type of Review

**Comment by GabPoll** [comment]
Ah ok. Title hadn't changed, so have done so, but please check I've got the issue description correct.

**Comment by davidmiller** [comment]
@micaeledwardmarks - I'm not sure that the OPAT team actually want this - had you discussed it with them ?

**Comment by GabPoll** [comment]
agree, they want the opposite now - they want to see everything on one page at a glance. Current (not future) haem solution would be a backward step (more clicking).

Inclined to close this, build haem WR, show them and then see what they prefer.

**Comment by davidmiller** [comment]
I'd be inclined to close it too - maybe we limit the display to the most recent on list view once we've sorted the other views - that way you can scan the list again!

**Comment by michaeledwardmarks** [comment]
Ok. 
Closing.
