### ISSUE TITLE
On server can we change the address to elcid rather than elcidl

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#550]
Everyone calls it elcidl
very annoying!

**Comment by davidmiller** [comment]
That's not within our gift I'm afraid - it's uclh IT...

**Comment by GabPoll** [comment]
I’m doing this offline by email, so apology for replying to a closed issue.

 

Any chance as well to distinguish the address from elcid test – elcidl and elcidt look v similar.

 

Suspect answer is no due to UCLH IT!

**Comment by davidmiller** [comment]
It's whoever is in charge of the UCLH internal DNS. 

This will be someone in ICT. 

It is a 2minute change if you can get the right sign-off / person in the room.
