### ISSUE TITLE
Inconsistent column headers in extracted data files

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#551]
Episode ID holds al the various extracted files together. However, there is inconsistency in the headings. All files except episode have heading "episode_id". The episode file only has "id". Would be good if all the same.

**Comment by davidmiller** [comment]
Strongly disagree - where is the "Feature" label? ;)

It shows how the hierarchy works - e.g. episode_id is a foreign key to the ID field of an episode. It expresses the relationship.

I assure you this is very much deliberate !

**Comment by GabPoll** [comment]
ok, given that no one else seems bothered, I'll politely agree to disagree. This may be easy and low priority, but not fixing it is even quicker!
