### ISSUE TITLE
Reword some of the next stage OPAT buttons

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#552]
Having clicked the Completed IV button on OPAT current
Can we rename the options as follows:
Completed Treatment >> Completed OPAT care
Switch to Oral >> Ongoing Follow-Up

Having clicked the Next button on OPAT Follow-up
Completed Treatment >> Completed OPAT care

**Comment by davidmiller** [comment]
These have been renamed!

**Comment by michaeledwardmarks** [comment]
Fixed and closed
