### ISSUE TITLE
Not all antimicrobial fields showing for one pt - OPAT live version 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#553]
@davidmiller 
Regarding a patient currently on OPAT referrals - When i add a new antimicrobial, only fields upto 'frequency' show.  I am not able to input: 
Delived by
Adverse events
Reason for stopping
comments 
This only seems to be the case for this case.

**Comment by michaeledwardmarks** [comment]
@7575colli 
Could you email David about this rather than having it on github
For confidentiality etc
