### ISSUE TITLE
Get rid of archived episode modal

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#555]
I think this might be worth considering.
If you wrongly discharged someone you can now undischarge them.
If you want to see old episodes you can search (and scroll through once we have that fixed).

What are the current use cases really?

**Comment by davidmiller** [comment]
I think you're right - it's not particularly intuitive, it doesn't explain what each of these options do very well... 

You're right, it's essentially superseded by the undischarge button I think (which is easier to understand I suspect).

It also leads to the weirdness we occasionally see on the haem list !

I'd be +1 on killing it. 

Thoughts from @GabPoll ?

**Comment by GabPoll** [comment]
+2 on the kill

**Comment by michaeledwardmarks** [comment]
+3

**Comment by davidmiller** [comment]
Fine - let's do it then.

**Comment by michaeledwardmarks** [comment]
@davidmiller can you just remind me the behaviours for when ADD Patient triggers just tagging vs creating new episode

Is it
If patient currently tagged to a list and episode == active ACTION = tag to new list
if patient currently tagged to a list and episode !==active ACTION = add patient/archived episode modal
if patient not currently tagged to a list then regardless of whether there is an 'active' episode ACTION = add patient/archived episode modal

**Comment by michaeledwardmarks** [comment]
I think the behaviours (with new episode category thing should be)

- If patient tagged to a list
  - Category type ==same (e.g you are adding on an inpatient list and they are on another inpatient list, as opposed to OPAT or walk-in list)
  - Episode is active (e.g patient not dead,discharged,transferred)
TAG Patient to your list

- If patient tagged to a list
  - Category type == NOT same (e.g you are adding on an inpatient list and they are on OPAT or Walk-IN)
MAKE new episode of appropriate type for the list you are on

- If patient tagged to a list
  - Category type ==same (e.g you are adding on an inpatient list and they are on another inpatient list, as opposed to OPAT or walk-in list)
  - Episode is INactive (e.g patient dead,discharged,transferred)
MAKE new episode of appropriate type for the list you are on

- If patient is tagged to No list
MAKE new episode of appropriate type

**Comment by davidmiller** [comment]
Active status is being incorrectly set - probably because of parent tags?

This is resulting in re-tagging of discharged episodes when we should open a new one.

**Comment by davidmiller** [comment]
@michaeledwardmarks @GabPoll 

What exactly does "No longer under active review" mean ? 

Do we still need it ?

**Comment by michaeledwardmarks** [comment]
It means the person hasn't actually left the hospital but we aren't looking after them any more.
It is mostly an issue for Micro.
The tricky thing is how to handle if you pick the patient up again e.g whether to consider the episode as inactive or not. I'm not sure how often it actually gets used in practice.
@davidmiller I would defer to you about the best way to handle these - as mentioned I would be happy to consider this as making the episode inactive if that seems sensible to you and @GabPoll

**Comment by GabPoll** [comment]
This is difficult to get right.
Let's imagine for a moment that we have feeds, then the whole admission, discharge thing disappears, and we then just have a system where we pull patients on and off lists at will based on your interest in them - inpatient, liaison review, phone consult, etc....
Given that we're not there now, we need to keep the admission / discharge thing for inpatients. However, for other specialties (micro especially), those are not important statistics really. All they really need is: add patient (for current review) and then a button saying "patient no longer being reviewed", ignoring anything about discharge, etc...
To that effect, it strikes me that Discharge & No longer under active review are basically the same thing. I would think a solution is that they could be put together in the discharge modal (i.e. top option - "discharge / no longer under active review"), and this has the same effect of closing that episode.

**Comment by michaeledwardmarks** [comment]
Agree.
For the purpose of this discussion then we have agreed that clicking "No longer under active review" should define an episode as INACTIVE.

**Comment by davidmiller** [comment]
I think this is now retired.

Adding a patient with a pre-existing inactive episode should go straight to new episode.

Deployed to elcid04-test

**Comment by michaeledwardmarks** [comment]
Ok.

So all of them apart from the "No longer under active review" seem correct to me.

For example
- Go to Tropical
- Make new patient
- Remove from list via "No longer under active review"
- Go to ID-Inpatient 
- Type hospital number in
- It adds the same episode to this list

I had thought that because of the above
If patient is tagged to No list
 MAKE new episode of appropriate type

That it would make a new episode.

Is this something to do with the parent tagging thing you mentioned?

**Comment by davidmiller** [comment]
@michaeledwardmarks - following those steps I can't reproduce that behaviour at all - can you test again?

**Comment by michaeledwardmarks** [comment]
Ok this appears fixed.
