### ISSUE TITLE
Total tab

### ISSUE THREAD

**Issue by lauranabarro** [openhealthcare/elcid#558]
Is it worth having a "total tab" where you can see everyone in the department? i.e. nurse and doctor list combined?

Could be useful for planning work.

**Comment by davidmiller** [comment]
We can do this... 

In fact we used to have "All" tabs until relatively recently :)

I think we'd need to consider the flow. How would we remove patients - when they come off all ? Automatically when they're no longer on any other list ? 

What's the use case / user need? 

To see the complete view ? 

I'm not super sure what value it adds when there are say 20 patients on each list over just going through each list separately ? (But then I've never worked in the walk-in clinic !)

Thoughts @michaeledwardmarks  ?

**Comment by michaeledwardmarks** [comment]
I would hold off a total tab at present personally but happy to review downstream.
Both users will be able to see both lists so should be easy for the doctor to see how many the nurses have waiting and visa versa.
