### ISSUE TITLE
Referring speciality look up list to add please 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#559]
Here is the list - All 324 of them:

ABIU - Non Stroke (GC25)
Accident & Emergency (050A)
Accident & Emergency (NHNN) (050B)
Acute Medicine (AAUA)
Acute Pain (TA28)
Adolescent Gastroenterology (010C)
Adolescent Rheumatol (08ZA)
Adult Allergy (RN05)
Adult Audio Vestibular Medicine (RN03)
Adult Audiometry (RN31)
Adult AVM Speech and Language Therapy (RN42)
Adult Cochlear Implants (RN07)
Adult ENT (RN01)
Adult ENT Speech and Language Therapy (RN43)
Adult Psychology (RN32)
AE (CT im) (IM02)
AE (FL) (IM20)
AE (MRI) (IM06)
AE (MT) (IM24)
AE (PF) (IM15)
AE (US) (IM10)
Aids (074A)
Ambulatory Emergency Care (AECA)
Antenatal (ip Mat) (02YA)
Anti Coag (01NB)
Autonomics (GC14)
Bariatric Surgery (0BSA)
BMT (062A)
Bone Tumour PAED NONDOH (04QA)
Bone Tumour Paediatrics (03MA)
Bowel Cancer Screening (010S)
Breast Clinic (015A)
Breast Clinic (DSU) (015X)
Cardiac MRI (007C)
Cardiac Surgery (05NB)
Cardiomyopathy (05VB)
CD Metabolic (GC15)
Chemical Pathology (01MA)
Child & Adoles Psych (029A)
Childrens Hearing Aid Centre (RN39)
Chronic Pain (TA26)
Clinical Genetics (068A)
Clinical Haematology (01NA)
Clinical Pharmacology (057A)
Colorectal Medicine (010B)
Colorectal Physiology (010P)
Colorectal Surgery (010A)
Colposcopy (094A)
Community ENT (RN36)
Community Medicine (01UA)
Computing (TA20)
Corporate (0000)
Cranioplasty External (TA19)
Cranioplasty Internal (TA18)
Critical Care - Neurology (GC11)
Critical Care - Neurosurgery (GC12)
Critical Care (TA01)
DC (CT im) (IM03)
DC (FL) (IM21)
DC (MRI) (IM07)
DC (MT) (IM25)
DC (PF) (IM16)
DC (TR) (IM27)
DC (US) (IM11)
Dementia (GC01)
Dermatology Emergency Services (005A)
Dermatology Medicine & Therapies (005B)
Diabetics (IP) (064A)
Diabetics (OP) (064B)
Dietetics (09DA)
Dietetics (NHNN) (09DB)
DSU (TA29)
Edgware Hearing Aid Centre (RN33)
EDH (TA08)
EDH Education Centre (04LB)
EGA (TA30)
EGA Cots (TA10)
Electrophysiology (07AB)
Emergency Medicine (01QA)
Emergency Postnatal (02ZA)
Endocrinology (IP) (061A)
Endocrinology (OP&DC) (061B)
Endodontics (EDH) (04KB)
Endodontics (RIS) (04KR)
ENT (Head and Neck) (084H)
Epilepsy (Chalfont) (GC02)
Epilepsy (NHNN) (GC03)
Equipment Incidents (TA11)
External OP (BD) (NM03)
External OP (CT) (NM18)
External OP (Gen) (NM15)
External OP (Lab) (NM12)
External OP (MP) (NM09)
External OP (PetCT) (NM06)
Fetal Medicine (05MA)
General Cardiology (007B)
General Medicine (001A)
General Medicine (NHNN) (001B)
General Neurology (GC04)
General Pathology (01LA)
General Surgery (013A)
Geriatric Medicine (011A)
GI (TA02)
GP (FL) (IM23)
GP (PF) (IM18)
GP (US) (IM13)
Group Physiotherapy (08PB)
Grown Up Congenital Heart - Cardiology (05BA)
Grown Up Congenital Heart - Surgery (05AB)
Gu Medicine (009A)
Gynaecology (025A)
Gynaecology (DSU) (025X)
Gynae-oncology (099A)
Gynae-urodynamics (09AA)
Hand Therapy (08TA)
Head & Neck (TA03)
Headache (GC05)
Hearing Aid Centre (RN34)
Hearing Therapy (RN35)
Heart Hospital (TA06)
Hepatology (060A)
Histopathology (01RA)
Hybrid Theatre (TA31)
Immunopathology (01SA)
Infect-comm Diseases (075A)
Intensive Care Unit (088A)
Intensive Treatment (059A)
Internal IP (BD) (NM01)
Internal IP (CT) (NM16)
Internal IP (Gen) (NM13)
Internal IP (Lab) (NM10)
Internal IP (MP) (NM07)
Internal IP (PetCT) (NM04)
Internal OP (BD) (NM02)
Internal OP (CT) (NM17)
Internal OP (Gen) (NM14)
Internal OP (Lab) (NM11)
Internal OP (MP) (NM08)
Internal OP (PetCT) (NM05)
Interventional Cardiology (05KB)
Interventional Radiology (NHNN) (048K)
IP (CT im) (IM04)
IP (FL) (IM22)
IP (MRI) (IM08)
IP (MT) (IM26)
IP (PF) (IM17)
IP (TR) (IM28)
IP (US) (IM12)
Laser (TA21)
Lipid Clinic (OP) (01DB)
Lymphoedemal (05HA)
Main Theatres (TA32)
Maintenance (TA12)
Maternity (026A)
Maternity Ante-natal (080A)
Maternity Post-natal (081A)
Maxillo-facial Surgey (Head & Neck) (045H)
Med Compl (pregnancy) (02WA)
Medical Microbiology (01TA)
Medical Oncology (067A)
Medical Photography (08XA)
Menopause (098A)
Microselectron (08BA)
Midwife Care (036A)
MND  (GC06)
Movement Disorders (GC07)
MRI (TA22)
Multiple Sclerosis (GC08)
Neonatal Int Care Unit (02AA)
Nephrology (077B)
Neurogenetics (GC23)
Neuromuscular (GC16)
Neuromuscular Complex Care Centre (NMCCC) (GC39)
Neuro-Oncology (GC30)
Neuro-Ophthalmology (GC17)
Neuro-Otology (GC18)
Neurophysiology (GC24)
Neurophysiology (Medical Specialties)  (086M)
Neuro-Psychiatry (GC19)
Neuro-Psychology (GC20)
Neurosurgery (NHNN) (048B)
Neurosurgical Pre Assessment (GC13)
Newborn Hearing Screening Programme (RN40)
NHNN (TA07)
NHNN General Physiotherapy (08HB)
NHNN Occupational Therapy (08GB)
NHNN Speech & Language Therapy (08IB)
Obesity Medicine (0BSB)
Obstetrics-gynaecology (091A)
Occupational Therapy (08CA)
Older People Rehab(LGR) (04DA)
OP (CT im) (IM01)
OP (FL) (IM19)
OP (MRI) (IM05)
OP (PF) (IM14)
OP (US) (IM09)
Ophthalmology (017A)
Oral Medicine (EDH) (02XB)
Oral Medicine (RIS) (02XR)
Oral Surgery (EDH) (022B)
Oral Surgery (RIS) (022R)
Oral Surgery (Theatres) (022A)
Orthodontics (EDH) (023B)
Orthodontics (RIS) (023R)
Orthotics (08SA)
Other (TA23)
Out of Theatre Services (TA27)
OUTPATIENTS (x49)
Outreach Oncology (ASP) (ASPA)
Paed Allergy (RN37)
Paed Audio Vestibular Medicine (RN04)
Paed Clinical Haematology (05FA)
Paed Cochlear Implants (RN38)
Paed ENT (RN02)
Paed Psychology (RN41)
Paediatric and Adolescent BMT (062C)
Paediatric AVM Speech and Language Therapy (RN44)
Paediatric Dentistry (EDH) (047B)
Paediatric Dentistry (RIS) (047R)
Paediatric Dentistry (Theatres) (047A)
Paediatric Dermatology (005C)
Paediatric Diabetes (087B)
Paediatric Endocrinology (087A)
Paediatric Neonatology (071A)
Paediatric Oncology (04NA)
Paediatric Radiotherapy (018C)
Paediatric Surgery (054A)
Paediatric Urology (021A)
Paediatric Urology (DSU) (021X)
Paediatrics (002A)
Pain Management (APP) (GC35)
Pain Management (Cancer) (GC33)
Pain Management (Facial) (GC38)
Pain Management (General) (GC21)
Pain Management (General) (GC37)
Pain Management (Haematology) (GC32)
Pain Management (Neuropathic) (GC36)
Pain Management (Physio) (GC26)
Pain Management (Psychology) (GC27)
Pain Management (SCS) (GC34)
Pain Management (Specialist) (GC28)
Pain Management (UGP) (GC29)
Pain Management (X44A)
Pancreatobiliary Medicine (03PA)
Periodontics (EDH) (043B)
Periodontics (RIS) (043R)
Personal dosimetry (TA14)
PetMR (NM19)
Physiology (007A)
Physiotherapy (08PA)
Pre-assessment (0PAA)
Premenstrual Tension (092A)
Prion (GC09)
Prosth / Cons (EDH) (042T)
Prosthodontics (RIS) (042R)
QA (TA15)
Radiation Incidents (TA17)
Radiotherapy (NHNN) (018B)
Radiotherapy (TA04)
Radiotherapy (Treatment) (08AA)
Radiotherapy (UCH) (018A)
REFERRAL/BOOKING/TELECOMS (x24)
Rehabilitation (NHNN) (02HB)
Reproductive Medicine - Endocrinology (093B)
Reproductive Medicine (093A)
Respite Care Op Planned (04BA)
Rheumatology (008A)
RLHIM Acupuncture Clinic (ACPA)
RLHIM Allergy Environmental Medicine (AEMA)
RLHIM Autogenics (AUTA)
RLHIM Cancer (CANA)
RLHIM Childrens (CHIA)
RLHIM Dietician (DIEA)
RLHIM General Medicine (GENA)
RLHIM General Medicine Stress (GMSA)
RLHIM Muscular Skeletal (MUSA)
RLHIM Occupational Therapist (OTA)
RLHIM Physio (PHYA)
RLHIM Podiatry (PODA)
RLHIM Rheumatoid Arthritis (RAA)
RLHIM Skin (SKIA)
RLHIM Womens (WOMA)
RPA Services (TA16)
Sickle Cell Crisis (03UA)
Sleep Service (RN06)
Sleep Study (NHNN) (034B)
Sleep Study (polyso) (03KA)
Sleep Study (remstar) (03VA)
Sleep Study (screen) (034A)
Special Needs (EDH) (04HB)
Special Needs (Theatres) (04HT)
Specialcare Babyunit (027A)
Specialist Endocrine (IP) (03NA)
Specialist Endocrine (OP) (03NB)
Speech & Language Therapy (08DA)
Still Births (089A)
Stroke (HASU) (0STA)
Stroke (QS Stroke Unit) (0STB)
Surgical Reception Unit (TA24)
T8 (TA05)
Telemetry (GC10)
Termination (095A)
Thoracic Medicine (004A)
Thoracic Surgery (05QB)
Training (TA13)
Trans Oesoph Ultrasound (05JB)
Transfusion (01NC)
Trauma & Ortho (016A)
Tropical Diseases (076A)
TTP (03TA)
Tuberculosis Medicine (076B)
UCH (TA09)
Unspecified Cardio-Thoracic Surgery (053B)
Upper GI Medicine (03GA)
Upper GI Surgery (0UGA)
Urology (019A)
Uro-Neurology (GC22)
Vascular DSU Diagnostic (012C)
Vascular DSU Treatment (012B)
Vascular Laboratory (072A)
Vascular Medicine (037A)
Vascular Surgery Diagnostic (012D)
Vascular Surgery Treatment (012A)
Well Babies (039A)
Well Woman (02PA)
(blank)

**Comment by davidmiller** [comment]
Are these *actually* all referring specialities ? 

e.g. I'm confused as to what a referral from "Computing (TA20)" or "UCH (TA09)" would mean !

Similarly "REFERRAL/BOOKING/TELECOMS (x24)" seems like an odd category here... 

I'm guessing you've copy&pasted this list from somewhere without reviewing the contents or am I getting the wrong end of the stick here? 

Thoughts @michaeledwardmarks @GabPoll  ?

**Comment by michaeledwardmarks** [comment]
Steve that is not a practical lookup list.
For example there are ten different pain team entries! 
Agree we could code this but not just using this list.

**Comment by davidmiller** [comment]
I was sent a lookuplist by @jonnylambourne as part of #444 which contains ~= 20 entries. 

I move that we use that and close this one ?

**Comment by michaeledwardmarks** [comment]
Agree that seems a workable number.

**Comment by 7575colli** [comment]
Sure. I agree - However, can we please use the exact terms and coding form the list that i sent to ensure that it is consistant with the Trust list

**Comment by michaeledwardmarks** [comment]
@7575colli I'm trying to understand how you envisage using the lookup list.
I presume to record where work comes from? +/- Direct letters.

I think we can make sure referring team names are consistent with the list above.
There is no way you can exactly replicate the codes above without having 324 items in the look up list. 
For example there are 10 different pain management codes.
What would we do with the information that a referral came from 
- Pain Management (Facial) (GC38)
vs 
- Pain Management (General) (GC21)

I envisage what we need is:
Department Name
Department Address

I may well have missed something here so do let me know if that is the case

**Comment by 7575colli** [comment]
I have rationalised the list based on CDR speciality coding and historic OPAT referrals.  This list is pretty comprehensive. On reflection, i think that we can drop the coding. Let me know your thoughts

Accident & Emergency 
Acute Medicine (AAUA)
Ambulatory Emergency Care (AECA)
Breast Clinic 
Bariatric Surgery 
Bone Marrow Transplant  
Cardiac Surgery 
Cardiology 
Clinical Haematology 
Clinical Pharmacology 
Colorectal Medicine 
Colorectal Surgery 
Dermatology 
Electrophysiology 
Ear Nose & Throat 
General Cardiology 
General Medicine 
General Practice 
General Surgery 
Gynaecology 
Geriatric Medicine 
Gastroenterology 
Hepatology 
Head & Neck Oncology 
Infect-comm Diseases 
Immunology 
Maxillo-facial Surgery 
Medical Microbiology 
Medical Oncology 
Neurosurgery (NHNN) 
Obstetrics-gynaecology 
Pancreatobiliary Medicine 
Pancreatobiliary Surgery 
Rheumatology 
Rapid Access Infectious Diseases 
Thoracic Medicine 
Thoracic Surgery 
Tropical Diseases 
Trauma & Orthopaedic Surgery 
Cardio-Thoracic Surgery 
Upper GI Medicine 
Upper GI Surgery 
Urology 
Vascular Surgery

**Comment by michaeledwardmarks** [comment]
I think it would still need some trimming
- Drop Breast Clinic 
- Drop Bone Marrow Transplant (covered by Haematology)
- Drop Electrophysiology
- I would merge the ID ones (Tropical Diseases, Infect-Comm Diseases)

- There appears to be duplication in cardiology and cardio-thoracic surgey
 - Don't need both Cardiology and General Cardiology
 - Don't need both Cardio-Thoracic Surgery and Cardiac Surgery

- Same for O&G: Do you need both
  - Obstetrics & Gynaecology
  - Gynaecology

It's a bit unclear to me what Gastroenterology would be when you also have separate:
- Upper GI Medicine
- Colorectal Medicine
- Pancreatobiliary Medicine
- Hepatology

So that is at least 7 items I think you could drop.

@davidmiller could you send @7575colli a link to the list @jonnylambourne sent you

**Comment by 7575colli** [comment]
Upper GI Medicine 
Colorectal Medicine 
Pancreatobillary Medicine 
Hepatology 
are sub teams of gastroenterology - I think that it is important to differentiate between the sub teams - linking the pt to the correct team will be important for finding the correct medical team, uclh@home referrals which are very specific about which teams they can accommodate and for auditing users of the OPAT service

**Comment by michaeledwardmarks** [comment]
@7575 - that bit I get!

I guess I mean us that if you have the 4 sub specialty options you then don't need a generic gastroenterology option - because all of Gastro patients fall in to one of the four sub specialty categories

**Comment by 7575colli** [comment]
I see... your right, lets drop gastroenterology

**Comment by michaeledwardmarks** [comment]
Covered by https://github.com/openhealthcare/opal-opat/issues/16 and https://github.com/openhealthcare/opal-opat/issues/19

We should ref here for the drop-down list though
