### ISSUE TITLE
Re-allow deletion of Clinical Advice/OPAT review entries

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#560]
Linked to #431 

- These are currently locked which will be helped by #431 
- Currently can't delete these entries (may partially be helped by above) but still might end up with incorrect entries

Possible suggestion
- User tries to delete Final Saved Clinical Advice/OPAT Review
- "You can not delete this entry - would you like to strike this entry out"
- Entry displays with line through the middle
- We have some kind of field (for extract etc) which marks that this entry was crossed out

Thoughts?

**Comment by davidmiller** [comment]
We  can just allow the user to delete them ?

On 31 January 2015 at 11:25, Michael Marks <notifications@github.com> wrote:

> Linked to #431 <https://github.com/openhealthcare/elcid/issues/431>
>
>    - These are currently locked which will be helped by #431
>    <https://github.com/openhealthcare/elcid/issues/431>
>    - Currently can't delete these entries (may partially be helped by
>    above) but still might end up with incorrect entries
>
> Possible suggestion
>
>    - User tries to delete Final Saved Clinical Advice/OPAT Review
>    - "You can not delete this entry - would you like to strike this entry
>    out"
>    - Entry displays with line through the middle
>    - We have some kind of field (for extract etc) which marks that this
>    entry was crossed out
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/560>.
>



-- 
Love regards etc

David Miller
http://www.deadpansincerity.com
@thatdavidmiller <http://twitter.com/thatdavidmiller>
07854 880 883

**Comment by michaeledwardmarks** [comment]
Ok.
Allow deletion.
I guess we still have the data in the database so that is fine.

**Comment by GabPoll** [comment]
ummm... this needs wider discussion with end users.
I can see benefits of a) allow deletion & b) restrict correction, but being able to see erroneous entries crossed out may be a step forward in terms of governance. Perhaps hides a crossed out entry but with option to view it. Transparency is a governance win, and want the audit trail to be admin-independent.

**Comment by michaeledwardmarks** [comment]
I agree it is complex. 
I guess we hope that allow save as draft will fix a lot of this.
My preference (I think) would be to allow people to delete the entry but have some marker showing an advice entry was deleted?

**Comment by davidmiller** [comment]
You can delete again. 
Temp fix in case we don't do save as draft in this release.

**Comment by michaeledwardmarks** [comment]
Fixed. Closed.
