### ISSUE TITLE
Can't Save changes to user accounts in admin

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#561]
For example 
- Reset user password (works fine)
- Try and set Force Password change back on (or can extract etc etc)
- Get error message saying:
Please complete Roles Field

Obviously most people shouldn't need a role assigning - as the only role is Researcher
But can't save peoples accounts without setting Role==Researcher

Nightmare as interferes with password resets, letting people extract data etc etc.
High priority for fix.

**Comment by davidmiller** [comment]
Interim, create a doctor role.
Medium term, sure - prob not mandataory.

On 5 February 2015 at 17:37, Michael Marks <notifications@github.com> wrote:

> Assigned #561 <https://github.com/openhealthcare/elcid/issues/561> to
> @davidmiller <https://github.com/davidmiller>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/561#event-230924759>.
>



-- 
Love regards etc

David Miller
http://www.deadpansincerity.com
@thatdavidmiller <http://twitter.com/thatdavidmiller>
07854 880 883

**Comment by michaeledwardmarks** [comment]
Cool.
Is creating a doctor role something I can do or something you need to do?

**Comment by davidmiller** [comment]
You can do it w. the green + button to the right

**Comment by michaeledwardmarks** [comment]
Done

**Comment by michaeledwardmarks** [comment]
I'm closing this because I think it is null and void since we rolled out the idea of roles, teams etc
