### ISSUE TITLE
New GUI Comments

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#562]
Really very lovely.
Personally I think Add patient button should be higher up in the actions sidebar - so that it is always prominent. At the moment it gets shifted below the Patient action section.
Thoughts?

**Comment by michaeledwardmarks** [comment]
- Patient flow buttons don't currently show up for Walk-In in the Patient Action bar

**Comment by davidmiller** [comment]
@michaeledwardmarks I think it's subtler than not showing up - it's the episode category not being set. This definitely doesn't get set via the referral portal ATM, but does if you add directly from the list.

That sounds like a new issue to me :)

**Comment by davidmiller** [comment]
Personally, I think the best way to add new patients is to press 'n' ;) But you're right, it's no longer a main focal point. I'm not sure how often people actually do add patients though? 

I imagine it's not the main thing you do with the list?

**Comment by michaeledwardmarks** [comment]
So related issue is that the box can start dropping off the page (for example if you are displaying the symptoms box) - so you can't see the print button fully![screen shot 2015-02-11 at 22 38 27](https://cloud.githubusercontent.com/assets/4578105/6158071/bfe6503c-b23e-11e4-8d4d-84bea063a3c1.png)
.
I would move it above filter personally.

**Comment by michaeledwardmarks** [comment]
Question - Is it possible/helpful for the Actions Sidebar to be fixed with the list aspect scrolling.
Hope that makes sense.

**Comment by michaeledwardmarks** [comment]
- Add button / filter button can drop off page
- ??Should the sidebar stay fixed relative to a scrolling list
- The team filter (e.g the replacement of the tabs) now can disappear off the top of the page 
![screen shot 2015-02-11 at 23 03 33](https://cloud.githubusercontent.com/assets/4578105/6158439/41b52b08-b242-11e4-9907-fa6f499ca6ec.png)

**Comment by michaeledwardmarks** [comment]
Note the above issue (team filter disappears off top) also means that the column heading disappear as you scroll down.

**Comment by davidmiller** [comment]
The print button shouldn't go onto a second line. 
That's about me not testing it at our common screen size.

Agree that basically the thing that should scroll are the rows in the table. 

Closer to detail view.

**Comment by michaeledwardmarks** [comment]
Yes that would solve most of this I think

**Comment by GabPoll** [comment]
Finally, I have a chance for some thoughts.
1) Big improvement - looks more professional
2) I like the team drop-down menu
3) I don't like where the Add patient and Print buttons are.
4) I think the "Add patient" and "Print" button should be on same row as the teams. These have an over-arching common use function over and above any highlighted patient.
5) I would also be tempted to experiment with filters on the same row as teams. That way the sidebar is only about the patient.
6) Agree that the Team menu shouldn't scroll. Likewise the list table headers.
7) Agree that the patient sidebar shouldn't scroll. However, by that token, the uber cool thing would be if a highlighted patient's row also didn't scroll. I suspect this is "non-trivial"!

**Comment by davidmiller** [comment]
I move that we close this for now - I think most of this has been implemented actually!

**Comment by GabPoll** [comment]
agree re closing this
