### ISSUE TITLE
Walk-In category is not set via referral portal

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#564]
Which results in incorrect patient action buttons showing up

**Comment by michaeledwardmarks** [comment]
?Deployed to 0.4?

**Comment by davidmiller** [comment]
It is now !

**Comment by michaeledwardmarks** [comment]
Agree this is fixed.
Minor point. 
Think date of Admission should be set as TODAY when using referral portal.

**Comment by davidmiller** [comment]
Do you really mean date of admission? 

I think you want to capture a different conceptual thing like "Date of appointment" ?

In the case of walk in, there is no admission in the common case, it's something else.

In non-walk in cases e.g. OPAT/Micro Haem etc, it doesn't seem to me that the date of admission should be set as today...

**Comment by michaeledwardmarks** [comment]
Yes - what I mean is that 
- For Walk-In patients we should capture "Date of Appointment" 
- This should be automatically set today
 - When added via referral portal
 - When aded via Add Patient to a Walk-In list

**Comment by davidmiller** [comment]
I'm moving these out to #598 . 

This issue now closed !
