### ISSUE TITLE
Should the management field become part of the End of Appointment modal

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#566]
So rather than having a separate field for this on list view.
Doctor clicks end of appointment
Forced to complete follow-up drop-down (exactly as it is in the current modal, but compulsory)
Advice optional

Then picks one of the three current modal options.

It would ensure that the follow-up status is recorded (very big issue governance wise) and playing with the system it feels more natural e.g end of appointment> set follow-up status

**Comment by michaeledwardmarks** [comment]
Could then potentially drop that column from list view display too which might be nice for real-estate

**Comment by davidmiller** [comment]
@michaeledwardmarks Honestly I don't really understand what it's for per-se.  

What kind of information are we envisaging being in there?

**Comment by michaeledwardmarks** [comment]
Currently that field captures:
1) Was the person booked in to a follow-up clinic
2) Did I give them any advice

But rather than having a separate modal for this we could potentially collect this at the time when user clicks end of appointment?

**Comment by davidmiller** [comment]
We can capture that in the discharge flow if we think that's better. 

I'm still waiting on what goes in the lookup list for followup options though?

**Comment by michaeledwardmarks** [comment]
TBH I think on reflection the best approach might be:

When Doctor clicks end of appointment action button:
- If Follow-up subfield of Management modal is already complete: Bring up end of Appoint Modal

- If Follow-up subfield of Management modal is NOT complete: Bring up Management Modal and then End of Appoint Modal

Does that make sense?

**Comment by michaeledwardmarks** [comment]
Could we check that travel has been completed at the time of discharging from Walk-In (either via Nurse-Led Care modal, or Doctor-End-of-Appointment modal)

**Comment by michaeledwardmarks** [comment]
Should the above commit have done something?

**Comment by davidmiller** [comment]
It's not deployed yet because reasons :)

**Comment by davidmiller** [comment]
This is now deployed to elcid04-test

**Comment by michaeledwardmarks** [comment]
As discussed.
Change wording on the interim modal to:
"You haven't entered anything in the management field. Please complete this first. Then re-click End of Appointment."

**Comment by davidmiller** [comment]
Deployed to elcid04-test

**Comment by michaeledwardmarks** [comment]
Beautiful
