### ISSUE TITLE
Discharged Last Week - Doesn't work on 0.4

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#567]
GET http://elcid04.herokuapp.com/wardround/dischargedlastweek 500 (INTERNAL SERVER ERROR)angular.28f401490ec3.js:8495 (anonymous function)angular.28f401490ec3.js:8291 sendReqangular.28f401490ec3.js:8025 serverRequestangular.28f401490ec3.js:11498 wrappedCallbackangular.28f401490ec3.js:11498 wrappedCallbackangular.28f401490ec3.js:11584 (anonymous function)angular.28f401490ec3.js:12608 Scope.$evalangular.28f401490ec3.js:12420 Scope.$digestangular.28f401490ec3.js:12712 Scope.$applyangular.28f401490ec3.js:9785 (anonymous function)jquery.3b80424646a7.js:4624 jQuery.event.dispatchjquery.3b80424646a7.js:4292 elemData.handle

**Comment by davidmiller** [comment]
Working on elcid04

**Comment by michaeledwardmarks** [comment]
Yes - note funny display of team names on the new version.
I think is because it doesn't show the meta-tag but confusing as there are now two non-identical teams both labelled as Liaison.

See image

![screen shot 2015-02-16 at 11 45 01](https://cloud.githubusercontent.com/assets/4578105/6211443/dd83d376-b5d1-11e4-9fe3-5e30609c42ae.png)

**Comment by davidmiller** [comment]
@michaeledwardmarks Good point. Displays parent && child now on elcid04

**Comment by michaeledwardmarks** [comment]
I'm closing.
Note the ordering is a bit funny still - not sure if this reflects the underlying admin ordering of teams?
e.g Immune Main team, then ID subteams, then Immune Subteams, then ID main team

![screen shot 2015-02-17 at 20 27 32](https://cloud.githubusercontent.com/assets/4578105/6236570/73abb776-b6e3-11e4-8238-ed3e15b25f81.png)

**Comment by davidmiller** [comment]
Yeah, it's something to do with the ordering. Honestly I think we should
look at how that ordering works per se now we're having teams as dropdown...

On 17 February 2015 at 20:29, Michael Marks <notifications@github.com>
wrote:

> I'm closing.
> Note the ordering is a bit funny still - not sure if this reflects the
> underlying admin ordering of teams?
> e.g Immune Main team, then ID subteams, then Immune Subteams, then ID main
> team
>
> [image: screen shot 2015-02-17 at 20 27 32]
> <https://cloud.githubusercontent.com/assets/4578105/6236570/73abb776-b6e3-11e4-8238-ed3e15b25f81.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/567#issuecomment-74746464>
> .
>



-- 
Love regards etc

David Miller
http://www.deadpansincerity.com
@thatdavidmiller <http://twitter.com/thatdavidmiller>
07854 880 883
