### ISSUE TITLE
Observations section missing from Detail view of Walk-In episodes

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#569]
There for OPAT patients but not for Walk-In
On list view (correct) for Walk-In

**Comment by michaeledwardmarks** [comment]
Note also need for an Obs Action button on the sidebar for both Walk-In and OPAT patients
https://github.com/openhealthcare/opal-observations/issues/18

**Comment by davidmiller** [comment]
I think this is actually broader in as much as: 

With openhealthcare/opal#245 we now have episode categories, e.g. the differentiation between a walk-in episode and an inpatient episode is much stronger.

A walk-in detail view can now have a completely different layout && template than a different episode type - we have much more control over this. 

While I suspect that the new panels are probably broadly what we'd want, I think we should probably think about questions like: 

* "What information makes sense for the detail view of a walk-in episode"
* "Presented in what order as a way to structure people's thought as they review an episode"

**Comment by michaeledwardmarks** [comment]
That is super exciting!
Answer for walk in is that detail view should contain only those columns that appear in the list view. 
There is at present no use case for additional fields on detail view of a walk in episode.

**Comment by michaeledwardmarks** [comment]
Will think about structures....

**Comment by davidmiller** [comment]
Walkin episode detail now: 

* Has observations
* Have the full set of doctor records + allergies + Nurse led care.

**Comment by michaeledwardmarks** [comment]
Closing this but note need for Add button on List view Sidebar
openhealthcare/opal-observations#18
