### ISSUE TITLE
OPAT Specific Antimicrobial fields don't show up in 0.4

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#570]
e.g delivered by, adverse event etc etc
Even if patient category==OPAT

**Comment by michaeledwardmarks** [comment]
?not deployed to 0.4
![screen shot 2015-02-16 at 11 59 25](https://cloud.githubusercontent.com/assets/4578105/6211568/44ee5ecc-b5d3-11e4-9b33-597faf87532a.png)

**Comment by davidmiller** [comment]
Now showing on elcid04

**Comment by michaeledwardmarks** [comment]
Coolio
