### ISSUE TITLE
Only show 1 OPAT review entry on list view - but show whole entry

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#572]
Note slight differences from #417

**Comment by michaeledwardmarks** [comment]
99% perfect.
Only displays one entry (fab)
but doesn't update to newest entry - see for example 
Bob OPAT Display test 3894382094

The entry on the list is the first one I wrote, then 2 subsequent entries only show up on detail view.

So it should be 
- [ ] List view: only show most recent OPAT Review entry

I note that wasn't clear in my original description!

**Comment by davidmiller** [comment]
This works for me.

It's taking the date/time of the entry to determine latest.

I just added a fresh entry to the list view of elcid04 and it immediately showed.

**Comment by michaeledwardmarks** [comment]
Did you deliberately set the time in the future - I see your entry is time stamped 13:47 which hasn't happened yet!

**Comment by davidmiller** [comment]
Yep, but it also works for me when you don't do that... ;)

**Comment by michaeledwardmarks** [comment]
Ok - agree this essentially works.

The only issue is if you create two entries back-to-back for same person, they end up with the same time stamp and it shows the older one.

e.g
create entry with time = 13:48, save
create new entry whilst time still==13:48
the older entry shows

Thoughts?

**Comment by davidmiller** [comment]
Don't do that.

More seriously... our ability to sort record entries is based on a single field. 
If the value of the field is identical, an arbitrary decision is made.
There's a question about whether we want multi-field complex sorting, or whether you want to e.g. sort by date created/updated by default but....

I don't think this will occur in the world e.g.: 

You did not really do two OPAT reviews in the same minute.
You did not really perform two clinical advice actions in the same minute.

You just edit the entry for the current MDT/review/etc no?

**Comment by michaeledwardmarks** [comment]
I think so too but I'm just mentioning it as an  FYI.
Happy to shut this issue.

**Comment by davidmiller** [comment]
Shure :D 

With infinite time/resource I'd suggest a more complex sorting algorithm - one for the distant future for now though!
