### ISSUE TITLE
Unified storage of walk in management

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#573]
@davidmiller 
Hope this makes sense.
As I remember the underlying structure for investigations is that each entry contains all possible subfields but only some of the get populated. 

I wonder if we could think about soemthing similar for management in walk in.

So underlying structure contains:

1- Nurse vs Doctor management
2- Reason for nurse management
3- Management given by nurse
4- Follow up organised by doctor
5- Advice given by doctor

So that when you extract you end up with a unified csv and set of data for both
- Nurse led management modal #542
- Management field #566

So 1 above will always be completed and then either 2&3 or 4&5

Does that make sense?

**Comment by davidmiller** [comment]
@michaeledwardmarks

I don't think you're really concerned with storage here.
You're concerned with the *presentation* of data extracts - which is very much different.

Medium term, we're going to need separate extract formats for each episode category, and to think about how / whether to allow extracts that contain multiple episode categories, how to restrict that, how the permissions work &tc.

These considerations are subtle and complicated, and need discussion while considering inpatients, outpatients, 

I think we should do the first pass of an extract for OPAT, Walk-In, RiDRTI, then look at what needs iterating on - which would be a great time to think about how to implement the raw tables we extract as CSVs.

**Comment by michaeledwardmarks** [comment]
Happy with that
