### ISSUE TITLE
Remove Discharge/Remove button from appearing in location field of DLW Ward round

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#574]
Confusing forn the end user who thought they were mean to click it to get them off DLW (although obviously people drop off this automatically - people think they need to click it)

**Comment by michaeledwardmarks** [comment]
Maybe moving buttons in elcid0.4 means this won't be a thing in the future?

**Comment by davidmiller** [comment]
The ward rounds need to be moved to the new templates.

I don't think that discharge is a sensible action for DLW.

**Comment by davidmiller** [comment]
On reflection the issue is actually that this button should never read "Discharge" for patients who are already discharged.

**Comment by michaeledwardmarks** [comment]
I think that is true on the list view.
But on DLW I don't think the button should be there at all - because population of that list is automatic and the button makes people think they need to remove people from DLW

**Comment by michaeledwardmarks** [comment]
So on 0.4 I would remove the confirm Discharge button from the sidebar on DLW

**Comment by GabPoll** [comment]
this appears fixed. DLW now just has button that says - confirm diagnosis. This brings up the final diagnosis modal.
The button the goes away (correct).
Pt stays on DLW (correct for current implementation)
Pt NOT added to inpatient list (fixed & corrected - many happy people on the ward)
Leaving open to close on live release

**Comment by GabPoll** [comment]
Hotfixed on elCID live
