### ISSUE TITLE
Category can not be edited

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#575]
I know why we did this but if doing so we now MUST make setting category mandatory or you get blank field.

So on adding a patient it should be 
OPAT == OPAT
Walk-in == Walk-In
everything else == Inpatient

Then inpatient can change to Discharge/Follow-up/Transferred/Deceased but only via clicking the Discharge button

**Comment by davidmiller** [comment]
That location category field matters much less now - it's not how we determine episode category. 

The episode category field is set programatically, and is non user-editable.

If anything, I would move to either remove it or replace with just inpatient/outpatient for inpatient episodes.

**Comment by michaeledwardmarks** [comment]
Agree it is mostly about display for user as opposed to actual role.

Agree that the only setting where the user should be able to have any say about what is set is the possibility to set inpatient/outpatient for inpatient episodes.

**Comment by GabPoll** [comment]
Wanted to +1 this issue. Noticed it today on Ortho round. Need to be able to edit Impatient / Outpatient category.

**Comment by GabPoll** [comment]
Similar issue at present on 0.3. A followup patient has somehow been readmitted, but they can't change the status of the patient to inpatient, because the field is not editable.

Short term solution could be to discharge him, end this episode and then readmit him as an inpatient? Ping @davidmiller @michaeledwardmarks

**Comment by GabPoll** [comment]
Can it be changed in admin @davidmiller . Perhaps best if i give you details separately of pt on live system, and you can go in and do this.

**Comment by michaeledwardmarks** [comment]
For this patient the correct behaviour is discharge the.old patient and make a new episode surely - that is what has happened in the physical world.

**Comment by GabPoll** [comment]
yeah i agree @michaeledwardmarks i think they must have tried to readmit a patient who was in follow up. Will get old d/c and readmission dates and then do this on the live system.

**Comment by davidmiller** [comment]
I think that these get set correctly now automatically. 
The "Category" thing is much less useful now.
Is there anything that needs doing for this ticket ?

**Comment by michaeledwardmarks** [comment]
I don't think so

**Comment by davidmiller** [comment]
OK - closing then! :)
