### ISSUE TITLE
Adding new patient doesn't give sub team options

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#576]
New to 0.4.

Get Micro, ID, etc... options
But no Haem, Ortho, Inpatients, etc...

**Comment by michaeledwardmarks** [comment]
Only on initial add patient
I you then edit the teams on an existing patient you do get these options

**Comment by davidmiller** [comment]
I think this is a sub-issue of #482 - which we will look to address before the 0.4 release.

**Comment by davidmiller** [comment]
The add patient teams form now has sub teams ! 
(Deployed to elcid04test)

**Comment by michaeledwardmarks** [comment]
Fixed.

**Comment by GabPoll** [comment]
agree fixed. 
In the future we should try and fit the vast majority of the teams on the modal so that it doesn't require scrolling down to see more / find save button.
Multiple columns in wider modal?
