### ISSUE TITLE
Patient sidebar GUI comments on v0.4

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#577]
Separate issue just for this, but obviously related to #562 .
- "Teams" icon and name too big font - should be smaller than that of the patient
- Edit team button, prob should be permanently visible rather than mouse over
- Something about "Episode details" was non-intuitive, but can't out my finger on it. First issue is that I had no idea at first where the single patient view, now realise that's the button. So perhaps as a transition, we should call it that to orientate users during the changeover
- Discharge button - feels like it should be red!

**Comment by davidmiller** [comment]
@gabpoll These are interesting, maybe you've changed your mind on some of these? 

I'm going to close this now - we can look at specific changes elsewhere if required?

**Comment by GabPoll** [comment]
agree. i think we're basically there on 0.4 that went out. let's wait for feedback now
