### ISSUE TITLE
Make better use of wide modals for free text entries

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#579]
Applies to Clinical advice and OPAT review once #578 fixed.

Would be nice to make the Clinical discussion box as big (tall as well as wide) as possible. When the CA was locked previously, one lovely thing was that opening up that CA would show all the text in one view. Now we need to scroll, so the more you can see (?smaller font), the better.

**Comment by davidmiller** [comment]
Note that we're optimising for 1280x1024 or larger screen resolution.
I don't think it's true that you have to scroll to see clinical advice at those resolutions.

n.b. I've just reviewed 20 of Vanya's clinical advice entries - all fit entirely on screen with the current layout in the modal.

I don't think making the font smaller will improve usability ;)
It's obviously not true that you want the box as big as possible ;) 

I think you've jumped to a solution that seems obvious to you without actually communicating the user need or problem - which makes it hard to figure out what you're getting at.

**Comment by GabPoll** [comment]
Fair enough, useful to have real life examples.
Looking back, agree, too vague an issue. Disappearing...
