### ISSUE TITLE
Editing a OPAT review, changes it to a nurse review box opening!!!!

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#580]
This is really weird! Try the following
- Go to OPAT referrals
- Open the CA for BOB Opat display
- Write something in the clinical discussion
- Click save
- It's turned into a nurse phone consultation

Is this something about change of timestamp when you change an entry, and so it is no longer the most recent entry?

**Comment by michaeledwardmarks** [comment]
I don't get this at all.

**Comment by davidmiller** [comment]
I have seen it once, can't reproduce subsequently...

On 16 February 2015 at 13:55, Michael Marks <notifications@github.com>
wrote:

> I don't get this at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/580#issuecomment-74511203>
> .
>



-- 
Love regards etc

David Miller
http://www.deadpansincerity.com
@thatdavidmiller <http://twitter.com/thatdavidmiller>
07854 880 883

**Comment by GabPoll** [comment]
i can't reproduce it anymore either. So odd. Must have just been a one off. Will close and keep an eye out for the future.
