### ISSUE TITLE
Number of days that 'line' has been in situ continues to count when line is removed 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#581]
When a line is removed, the 'days in situ' counter should stop. Currently, this continues when the line removal date is entered. 

Also, the removal date of the line doesnt show in the main display - It is not clear if the line is still in place or not.

**Comment by michaeledwardmarks** [comment]
@davidmiller I think would be good to fix this bug for 0.4 if possible?

**Comment by davidmiller** [comment]
@michaeledwardmarks Need to clear the tickets currently in 0.4 first !

**Comment by davidmiller** [comment]
Fix deployed to elcid04-test

**Comment by michaeledwardmarks** [comment]
Beautiful
