### ISSUE TITLE
No longer able to scroll through previous episodes on single patient view

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#586]
Not sure if this is noted elsewhere.
But for patients with multiple episodes (be they OPAT, inpatient etc etc) it used to be possible to scroll through these on single patient view.
Not sure when that feature disappeared?

**Comment by davidmiller** [comment]
Long time ago. 
Pre 0.3.

**Comment by michaeledwardmarks** [comment]
Ok. We should restore if possible.
Especially with the move to OPAT it will be helpful to be able to see previous inpatient and OPAT episodes etc etc.

**Comment by GabPoll** [comment]
+1 with @michaeledwardmarks

**Comment by davidmiller** [comment]
Upon further investigation:

* Prev/Next episodes do exist in single patient view.
* They are not very usable/pretty.
* They do not include episodes w/out an admission date (#605)

**Comment by michaeledwardmarks** [comment]
So I'm closing this because #605 is the explanation for this we believe.

**Comment by davidmiller** [comment]
@michaeledwardmarks But it's not there at all in 0.4 - I thought this was the ticket for that ?

**Comment by michaeledwardmarks** [comment]
My mistake! Re-opened.
Maybe buttons in the action bar?

**Comment by davidmiller** [comment]
Episode History has been reinstated ! 

A good example would be http://elcid04-test.herokuapp.com/#/episode/29

**Comment by GabPoll** [comment]
very nicely executed @davidmiller .

I would reduce icon & font sizes and spaces a bit to save space - this list may go quite a bit down.

**Comment by GabPoll** [comment]
BTW @davidmiller we MUST show this to Vanya when we see him on Monday (as long as he hasn't arranged a separate meeting by the time he replies)

**Comment by michaeledwardmarks** [comment]
This is really beautiful.
I agree that shrinking icon space would be sensible but am closing this issue as think that is lowish priority.
