### ISSUE TITLE
HIV testing in walk-in: reasons not done list

### ISSUE THREAD

**Issue by maggiearmstrong** [openhealthcare/elcid#587]
Below (hopefully, if I get this right) a list of reasons people decline HIV testing in walk-in (this includes reasons people decline POCT).
Maggie
REASONS PATIENT DECLINED
already HIV positive
do not feel there is any need to test
do not trust a finger prick test
do not want HIV result in hosp notes
do not want to test in this environment
no reason given
recently had an HIV test
too scared of the result
would like more time to think

REASON POCT/HIV TEST NOT OFFERED
already HIV positive
not documented
other
patient did not fit criteria

**Comment by davidmiller** [comment]
Thanks @maggiearmstrong  ! :)

**Comment by michaeledwardmarks** [comment]
Closed as moved to #432
