### ISSUE TITLE
Adding new OPAT pt - Please add referring team/consultant / allergies fields

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#589]
When a new pt is added could the referring team/consultant /allergies and location be brought up into the initial screen that asks for the pts name/dob etc. 

Currently these fields are often not completed or overlooked because these fields are hidden on the main screen view. If your not keen on adding the allergies, i will settle for the referrers details and location.

**Comment by michaeledwardmarks** [comment]
Actions:
- [ ] Referring Team Subfield in Add/Import Patient Modal (Lookup list #559 )
- [ ] Referring Consultant Subfield in Add/Import Patient Modal
- [ ] Allergies in Add/Import Patient Modal (Or follow-up modal in style of Presenting complaint for OPAT episodes?)
- [ ] Location free-text field in Add/Import Patient Modal
