### ISSUE TITLE
Make referring team/consultant and location (ward/bed No) visible in main screen view

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#590]
Location and referring team/consultant are currently hidden; can this info be made visible on main screen view please along with the location (i.e hospital /ward /bed)  

Maybe this could be visible in the 'location' column where the 'completed IV' button is?

**Comment by 7575colli** [comment]
Similar to the walk in screen that shows ward, bed etc - But add team and consultant

**Comment by michaeledwardmarks** [comment]
Just highlighting this as having been flagged in recent review meeting with @7575colli and Sarah Logan

**Comment by davidmiller** [comment]
Deployed to elcid04test!

**Comment by michaeledwardmarks** [comment]
Bingo!
