### ISSUE TITLE
Deleting OPAT plan entries

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#591]
Sorry if i  have missed a solution already discussed.  I am currently unable to edit a OPAT plan entry.  I understand the governance issues around this, but I'm concerned that there are currently clinical entries on elcid that are factually incorrect.  As our MDT today highlighted, this is confusing and not particularly safe. 

Maybe a way of clearly marking the entry as an error might be a solution (a faint line through the text and a stamp that labels who and when it was marked as an error)

**Comment by michaeledwardmarks** [comment]
This will be fixed in the next release.
I'm closing this because I know this is already done on the next version coming in March.
