### ISSUE TITLE
MRSA MRAP - 4 weekly alerts 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#592]
I love that MRSA MRAP is a pre entered test to prompt the user to add this entry.

However, when lots of investigations are added, this gets easily lost. For  pts with vascular access, this should be repeated every 6 weeks.  Looking at a glance who and when MRSA screens will need to be repeated is difficult with the amount of details that we are entering.

Maybe a solution could be for the test to turn red 4 weeks after the MRSA test date... this would allow ample time for the test to be repeated within the 6 week timeframe.

**Comment by michaeledwardmarks** [comment]
That is quite complicated to do I think and is in my opinion non-actionable in the absence of further development funding.

**Comment by 7575colli** [comment]
ok

**Comment by davidmiller** [comment]
So, we're working on this kind of functionality elsewhere.
Once it becomes available, we can explain what is available && how you can take advantage of this kind of thing. 

Closing until such times, when we can implement (@michaeledwardmarks as CEDAR rules)
