### ISSUE TITLE
Tests with pending results not easily identifiable   

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#593]
Is there a way of making future investigations (i.e. a scan with a date in the future) or test that has a pending result (i.e. a blood culture with no 'result') easily identifiable.

Maybe they could show in a different colour (red?) or be in bold or always at the top of the list - then when completed, they get put in the usual reverse chronological order.

Totally happy for suggestions

**Comment by michaeledwardmarks** [comment]
Again this is technically difficult (recognise state == X and do Z) and is non-actionable without funding I think

**Comment by davidmiller** [comment]
Complex ordering within records e.g. of tests is subject to quite a lot of complexity - I think it's unlikely short term.

With the 0.4 release we're looking to standardise and reduce variation of display and placement. 

We don't currently have any way of noting "This is in the future", but if we were to display something differently, we'd look to do it uniformly for all dated records.

There are a number of ways to indicate this - not least a subtle horizontal line across to indicate "now".

e.g. 

28/2
27/2
------
26/2
24/2

I think we'd want to look at this after we deploy 0.4 ?

**Comment by michaeledwardmarks** [comment]
I'm closing this pending some feed-y developments as this is currently non-actionable I think.
