### ISSUE TITLE
PMH 'year' field not flexible 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#594]
What are your thoughts about allowing the year field to more flexible.  Currently, the entry is rejected if anything other than YYYY is entered.

However, if your adding something like a total knee replacement - you really want to put the exact date or at worst month. 

How about allowing DD/MM/YYYY, YYYY, MM/YYYY, and 'Sept 2001' for example.  The first three date formats would do though.  Currently i have to write this is the details field which isn't a good use of the date field.

**Comment by michaeledwardmarks** [comment]
Suggest:
-  Rename as date rather than year 
- Make field free text

**Comment by davidmiller** [comment]
@michaeledwardmarks Everywhere ?

**Comment by michaeledwardmarks** [comment]
For the PMH field regardless of the episode type I think that would be ok.
Not for other date fields clearly.

**Comment by michaeledwardmarks** [comment]
@davidmiller - not sure if this is simple enough to bundle in to 0.4

**Comment by davidmiller** [comment]
@michaeledwardmarks Once we've done all the things currently slated for 0.4 we can add it to the list ;)

**Comment by drcjar** [comment]
@michaeledwardmarks @davidmiller might be nice to keep a standard(ish) format to make getting the data out later easier? or not important/doesn't make a difference?

**Comment by michaeledwardmarks** [comment]
The problem is that at the moment the system can't handle dates very flexibily. E.g DoB must be written exactly DD/MM/YYYY but obviously we don't always have that level of detail especially for PMH so we need a free text option

**Comment by davidmiller** [comment]
@drcjar Doesn't make a difference for getting data out, does make a difference for e.g. complexity of search/queries from a technical perspective.

For reference, everything is in a standard format (Postgres Date[Time]/Python date(time)/JS Moment/ Bootstrap Datepicker) except for this one field, which is actually not really / always a date for reasons described above.

In addition, everything is also timestamped at create/edit times - in the same formats.

@7575colli is correct though IMHO - we should be more permissive and let this be a free text box for now. 

We can revisit and look at how to express multiple granularities of conceptual temporal data (Vague year->Month range->specific dates). This is a much harder problem than it seems :)

**Comment by michaeledwardmarks** [comment]
Keen to roll in to 0.4 if possible @davidmiller 
(e.g just switching this to free text)

**Comment by davidmiller** [comment]
@michaeledwardmarks Keen to do all the things already in 0.4 first ;)

As a release deadline approaches, the release loses features, the release date doesn't move backwards!

**Comment by michaeledwardmarks** [comment]
@davidmiller
Is this really 5 hours to make this field a free text field?

**Comment by davidmiller** [comment]
@michaeledwardmarks  It mostly about writing and documenting how to make sure we don't loose any historical data more than the literal shift from one to the other. Even that has some complexity - make sure all the forms are updated everywhere, checking that advanced search clauses are still sensible.

**Comment by michaeledwardmarks** [comment]
Fair enough!
