### ISSUE TITLE
Line assessment upgrade 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#596]
Can i suggest some amendments to this field:

1. Line: ( auto populate with current line), Site (auto populate from current line)
2. Date inserted: (auto populate with current line insertion date)  DAY: (auto populate from current line)
3. ~~Assessment date / time (auto populate with current date/time)~~
4. ~~VIP: look up list as is in place (please add '0' to score)~~
5. CM from exit site today: ___ (No need to show for peripheral cannula)
6. Dressing type: look up list (CHG, Biopatch, Transparent) but allow free text 
7. Dressing intact: Yes / No
8. Dressing changed: Yes / No 
9. Bionector changed: Yes /No
    Note the yes / no answers to the questions - a blank tick box is presumptive - my preference is that this is explicit.
10. Next dressing/Bionector change due: DATE 
11. Drawback of blood seen: Yes / No (no need to show for cannula or Leaderflex cannula) 
12. Comments: Free text (Will allow for exceptions to SOPs to be noted)
13. To make the assessment comprehensive and correlate directly to a specific line, please include insertion date, sum of days.
14. CM from exit site should be a measurement, not a tick box

**Comment by michaeledwardmarks** [comment]
@7575colli 
Again this is quite complicated

1) What is the current line? e.g if there are two lines on the list how do we decide which one is current (I assume by looking at todays dates, comparing to the date line was entered and removed etc etc)

2) Why do you need to replicate the location of the line every time you do the assessment? You have recorded the location in relation to the line. 
e.g do you really need to see
1st Jan Hickman line assessed R-Subclavian
2nd Jan Hickman line assessed R-Subclavian
5th Jan Hickman line assessed R-Subclavian

3) Same thought about Date inserted - I don't see why this needs replicating repeatedly

4) Assessment date does autopopulate

5) VIP look up does include 0 at least on the version I'm looking at (heroku)

6) Do you want drop downs instead of tick boxes? 

Also remember we can't use this instead of the notes - so think about whether all of this is needed in elCID vs the notes at present.

**Comment by 7575colli** [comment]
There will be very few occasions when there will be more than one line in place. But if there are, could the screen not drop down two fields with the lines etc auto populated?? 
If the auto populate thing is tricky... then look up lists will be ok 

The reason for the detail is so that the elcid entry can be printed and stored in the notes... replacing the need for making an dlcid entry then a written entry in the notes.  Duplication of notes makes me want to cry. 

Semi permanent lines are seldom replaced into the same limb so the site is a good source of reference   for confirming that you are referring to a specific line... rather than having to cross reference this to another entry on elcid.  Plus... if the entry is printed, it must be clear that the assessment is relating to an identifiable line... writing where it is sited is a basic requirement. 

6) Good idea... Yes / no drop down boxes would be better thanks.

**Comment by michaeledwardmarks** [comment]
So if you want to print for the notes why would you not just print
1) The current line list
2) The line assessment
This would have the same effect essentially no effort.

**Comment by 7575colli** [comment]
Agreed... that is fine.  But when the line assessment is noted separately to line details (as is on elcid)... Its a tad messy 
Forgive me for trying to seek perfection

**Comment by michaeledwardmarks** [comment]
Nothing wrong with perfection!
Just a balance between what we can realistically do, what we agreed funding for, what is highest priority (e.g I think letters higher priority - imagine you agree) etc etc!

**Comment by davidmiller** [comment]
Phew. 

That's a lot to take in ! :) 

I've numbered the points in the original post for reference.
I've struck through points I believe to have been already implemented. 

Points 1, 2 & 13 are basically the same thing - you want to link a line assessment to a specific line. See discussion below.
Points 5 & 11 are dependent on that linkage. Let's assume it would be trivial if there was a link.

6 Asks for a new lookuplist, which is fine.

7 Asks for the field to change to yes/no/unanswered. 

8 & 9 were discussed during development. 

A Blank/Yes/No field does not capture any new information. e.g. 
If there is a dressing change date, then the dressing was changed !
Recording on the form just makes the form longer

10 & 12. Add new fields - which is fine.

14 is an obvious mistake.

### Linking a LA to a Line

The meta User need is:

> I want a field in a record point to an instance of another record.

Which has come up before.
(#132 would be one example)

This is currently not possible, and non-trivial to implement.
Which does not mean that we will not do it! 
There is broad agreement that this would be useful in a number of cases.
But it does mean that we're unlikely to do it right now.

We discussed this during development and agreed that the interim least worst option would be to have a free text "line" field in which the user could type e.g. `PICC LA 21/2/15`. If there is only one active line, then the line review is implicitly, reviewing that line - this is only an issue for the uncommon case of > 1 line.

I would suspect that printing the single patient view from the upcoming 0.4 release (end of Mar, early Apr) would likely provide all the information for the permanent record, and will also, look like the elCID record if the user wants to look it up, reducing variation and general cognitive overhead.

In my opinion that this remains the least worst option.

### Actions from this issue

- [ ] Add a Dressing type lookuplist
- [ ] Give a null option to Dressing Intact
- [ ] Add field "Date of next bionector"
- [ ] Add field "Comments"
- [ ] Make CM from exit a measurement in CM!

**Comment by michaeledwardmarks** [comment]
Again I wonder about making the actionable points from above part of 0.4 if possible (again I know we have other stuff to work through)

**Comment by davidmiller** [comment]
@michaeledwardmarks Let's do the stuff we have scheduled for the 0.4 release first, then think about what else to add if we have time !
