### ISSUE TITLE
Odd date order of OPAT plan (current pts) in live system 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#597]
'Current OAPT' - JW

Order of entrys is odd: 

24/2
23/2
25/2 - Odd how this date is in the middle - should be at the top of the list
19/2
11/2

Might be a bug?

**Comment by davidmiller** [comment]
The behaviour on the current list is bizarre. 
Honestly, this is fixed by #572  which will be in the next release.
