### ISSUE TITLE
As a user I would like to see trends of test results

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#600]
So that I can quickly ascertain whether this patient is getting better or worse 

e.g. bloods, CPR 

/cc @GabPoll

**Comment by michaeledwardmarks** [comment]
Would consider specific sideboard for this.
e.g when you click on patient then in the panels on the right it shows trends of key blood tests
integration with feeds should make this possible

**Comment by davidmiller** [comment]
TBH the data from manually entered tests is so bad as to be unusable.
Let's re-visit this when feeds come through and we can see what the data is like.
