### ISSUE TITLE
As a User I would like to clear filter terms

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#601]
Filtering patients on list view is brilliant.
However, when filtering for next patient on the list, a natural tendency many have is to backspace one letter at a time. This initiates a new filter for each new word / hosp no. (with one less letter or number), creating a longer and longer list (as the filter becomes less stringent).

The quick way round this is to highlight the entry, so that user can start typing and begin a new focused filter. Alternative solution could be a clear all "x" at the end of the box.

**Comment by michaeledwardmarks** [comment]
it's not clear to me that the current is the wrong behaviour.
Imagine I know there is a patient called something like:
Patharika
But i don't know the perfect spelling, I want to type the whole thing, get no hit, delete the last few letters and discover it was actually spelt
Patharaka

**Comment by davidmiller** [comment]
+ 1 on adding a clear button.

**Comment by GabPoll** [comment]
Clear button simplest solution here and I'm happy with that.

@michaeledwardmarks your example is absolutely correct and logical. However, in Vanya's round what is more common is that he uses the filter to go from "Smith" to "Bevan" for example, by removing each letter of Smith, before adding B. Consequence is that list just keeps filtering less and less stringently as each letter of Smith is removed and this adds time to switching between patients.

**Comment by michaeledwardmarks** [comment]
This is related also to #945 
- e.g if you backspace off the last letter then it causes the page to reload.
I suggest we combine the two actionable points in to 1 issue for parsimony.

- [ ] Clear button for filter
- [ ] Deleting the last character should not cause the page to reload

**Comment by michaeledwardmarks** [comment]
This is a big improvement now that it doesn't reload.

**Comment by GabPoll** [comment]
The clear button is good, and i think is enough to close this.

Difficult to tell if it reloads page. It doesn't as such, but backspace does seem to run the filter again. Looks fast at the mo - was only slow when we had 300+ haem patients on list. MIght need to test this best when in elCID test mode with full data dump from live, e.g. Walkin doctor review list
