### ISSUE TITLE
For investigations, details should come up in brackets next to name of the type of investigation

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#602]
So if there is a wound swab from the right knee, i choose Wound Swab MC&S, and in details i write "Right knee".
This displays as:
- Date, wound swab mc&S
- Microscopy
- Culture
- Sensitive antibiotics
- right knee

I want it to look like this:
- Date, wound swab mc&S (right knee) *this could be in brackets on next line if helps formatting for columns*
- Microscopy
- Culture
- Sensitive antibiotics

In essence though, important to keep the details of the investigation next to the name of the investigation

**Comment by michaeledwardmarks** [comment]
Seems reasonable

**Comment by davidmiller** [comment]
These are fairly minor formatting changes. 

The thing to be aware of here is making sure that you update *all* of the investigation templates.

There are probably some in: 
https://github.com/openhealthcare/acute
https://github.com/openhealthcare/opal
https://github.com/openhealthcare/elcid

The other thing to be aware of is that for historical reasons at the model layer investigations are actually called MicrobiologyTest

**Comment by fredkingham** [comment]
I think this is done but I couldn't find anything in https://github.com/openhealthcare/acute, there's diagnosis.html but I think this is connected to something else

(opal and elcid have both been updated)

**Comment by davidmiller** [comment]
NP - was just saying we should check !

**Comment by GabPoll** [comment]
Perfect, thanks guys
