### ISSUE TITLE
Add "Add new allergy" in Actions section on elCID 0.4 list view

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#603]
Perhaps in a highlight colour.

A clinical safety issue that oversees all clinical activity.

**Comment by michaeledwardmarks** [comment]
+5

**Comment by GabPoll** [comment]
@davidmiller 0.4 or 0.5?

**Comment by davidmiller** [comment]
@GabPoll So, this is one of those where I'm not all that convinced ! :) 

Can we talk about ... What is the user need here ? 

(For a change! )

> As a ....
> I want to...
> So that ...

**Comment by GabPoll** [comment]
As a doctor doing no harm is my number one priority. Adminestering drugs to which the patient is known to be allergic is a never event. Drug allergy oversees all clinical practice and should be visible and editable at all instances. The actions section seems like an appropriate place to add such a button to reflect the overarching nature of drug allergies and to facilitate documentation of this important field for any user in any service that uses elCID

**Comment by davidmiller** [comment]
3 years old now... I think we're unlikely to do that in the next couple releases at least...
Going to close this.

TBH as far as allergy information is concerned I think there's an argument that we're better with feeds or 'check EPMA'.
