### ISSUE TITLE
As a User I would like to see episodes without admission dates in history

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#605]
So that I can review the clinical information contained therein.

**Comment by davidmiller** [comment]
The current display mechanism for `other episodes` is actually based on placing each episode in time by date of admission.

Which is to say that it is `previous episodes` and `subsequent episodes` - and that episodes that cannot be pinned to a point in time are omitted entirely. 

This is clearly the wrong behaviour.

This is clearly related to #586 but specifically notes the need to include episodes that do not have a date of admission.

**Comment by GabPoll** [comment]
Thank you for raising formal Github issue @davidmiller and for priority 0 status. (i'm also a bit pleased i'd worked it out).

What happens if dates of admission are retrospectively added - would that episode automatically be slotted into the episode list? This could be a short term fix for Vanya (given that it is a limited number of patients).

**Comment by davidmiller** [comment]
@GabPoll Yep - it slots right in.

The algorithm currently does: 

1. What is the date of the episode we're viewing
2. Generate a list of previous episodes
3. Generate a list of subsequent episodes

There are two things that can go wrong here: 
1. The current episode has no admission date, so it just bails
2. Some of the episodes for this patient have no admission date, and are then simply not included in the list of episodes.

Adding admission dates to episodes mean that they get picked up by this algorithm in 0.3. 
For 0.4 we need to accept that not all episodes will have admission dates, and provide appropriate algorithms/display paradigms.

**Comment by davidmiller** [comment]
All other episodes are now listed in history, regardless of their date information.

**Comment by GabPoll** [comment]
will keep refinement of this issue to #586.
