### ISSUE TITLE
Admin link for specific patients in sidebar displays a bit weirdly

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#607]
Can't upload image from Solomons but seems to me that if you have admin rights there is a small admin link now next to the patient details bit in the sidebar.
This cut's across the blue highlight bar.
Hope my description makes sense

**Comment by michaeledwardmarks** [comment]
![screen shot 2015-04-16 at 08 20 23](https://cloud.githubusercontent.com/assets/4578105/7169542/2eef8584-e412-11e4-836c-45dca5aef228.png)

**Comment by davidmiller** [comment]
OK - good to know ! 

Seemed fine at my resolution... 

Will find a better place to put it, but yes, this is "Edit this episode in the Admin" -> only available to admin users.

**Comment by michaeledwardmarks** [comment]
Not an issue on the elcid04-test server so closing
