### ISSUE TITLE
On elCID 0.4 list view, only sub team names show in patient action box

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#609]
Look at Euan Right. 2x inpatients + 2x liaison, but one is immune and the other ID.
Need to show parent team name

**Comment by davidmiller** [comment]
So, we need an agreement re. naming conventions there. 
e.g. currently you could title the team "ID Inpatients" but then the team dropdown would read "ID/ID Inpatients".

We should make sure this is taken into account when we address #482

**Comment by GabPoll** [comment]
Agree.
One thing we do have though is screen real-estate to play with now - on average, the "action box" for that patient (where the team names are) is shorter than the list. As such, we can just write out team names in full and list them one per row.

Also what about a consistent labelling system based on linked tags? Would need to sketch this, but i was thinking of 2 linked boxes with consistent colours. E.g. parent team grey, like now, subteam with white background and black border. Just an idea.

**Comment by michaeledwardmarks** [comment]
I don't think this is still an issue?
