### ISSUE TITLE
Cant add 'deliverd by' for P.G on 'current' OPAT list

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#610]
This pt was switched to orals then 'back to IV'.  I cant add 'deliverd by' in antibiotic field.  Not sure if moving pt from switch to orals then back to IV has addedd created a bug.  I think the same was the case for the other pt that i recently had the same issue with.

**Comment by davidmiller** [comment]
@GabPoll Is this one of your Micro Ortho patients by any chance ?

**Comment by GabPoll** [comment]
@davidmiller nope, just checked. This patient not an ortho patient & I've never accessed it before.

**Comment by davidmiller** [comment]
@7575colli This is an instance of a known issue when OPAT patients are incorrectly assigned to Inpatient lists. I have re-set P.G on the live server for you - this should now be fine ? 

The relevant issue is #531 if you want to track it's progress ?
