### ISSUE TITLE
As a junior doctor, I don't want follow up patients on same list as my inpatients

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#612]
Suggestions from ID SHOs. They find the list of patients with outstanding results at the bottom of the printed inpatient list a pain - there are 12 or so patients they do little about most of the time, but takes up space & paper.

They prefer a 3rd ID subteam called "Follow-up".

However, this is not a simple subteam re-assignement issue. It needs:
- ID inpatient discharged
- choose d/c with outstanding results
- discharge date set (hence why can't just change tag)
- untagged ID-inpatient, re-tagged ID-followup (with consequent list switching).

This strikes me as quite similar to OPAT functionality actually.

Thoughts @michaeledwardmarks esp on concept. Thoughts @davidmiller esp on technical feasibility.

I'll end this issue with a quote i got from juniors whilst taking notes on this issue. "This is great, can actually speak to someone and get things changed. Nothing like CDR"

**Comment by davidmiller** [comment]
Simplest possible thing seems to me to be creating the ID F/U list, then after you discharge with f/u change teams.

There's nothing whatsoever that prevents us technically from implementing that as the discharge flow for ID inpatients, would just need to figure out the correct behaviours and then implement.

**Comment by GabPoll** [comment]
ok, thanks @davidmiller . 0.4 implementable? If simple, would be quite a nice PR win of rapid response to feedback.
@michaeledwardmarks thoughts please.

**Comment by davidmiller** [comment]
Adding a team and process around what happens can be done in 0.3 !

Adding the flow for 0.4 is a maybe but I suspect not likely - we really don't have much time left before 0.4...

**Comment by GabPoll** [comment]
ok, that's fine re. not for 0.4.

Adding to 0.3, i know I could do that, but would that screw up discharges dates or not? I wouldn't think so and if not, then the workflow can be:
- ID inpatient discharged
- choose discharge with outstanding results / follow up
- discharge date set on elCID (automatic step by the discharge process)
- patient remains on ID inpatients list as follow up (so everything till now is exactly the same as happens already)
- junior doctor manually changes the team from ID inpatients to ID follow up.

Only the last point is new workflow. I guess the push to move people off their list would then come from them - i.e. if they want them out of the way, they do it.

If the automatic shifting to the follow up list can be easily implemented at a later stage, then I'm happy to create that sub-team list and relay that workflow option to them (all without requiring any David time!).

Would need a 0.3 heroku instance to road test it (make sure can successfully remove them from ID follow up list using the remove/discharge button, etc...). Perhaps easiest done on elCID test via VPN.

**Comment by davidmiller** [comment]
Elcid-test sounds like the perfect place for it to me ! :)

**Comment by GabPoll** [comment]
I've played with this on test server, and it works as intended, so i think this is a change we can make via admin section. Thoughts from @michaeledwardmarks first before implementing please.

**Comment by GabPoll** [comment]
Ok, played some more - not so simple as ever.
For ID, it's easy - they already have sub teams, and no patient is tagged to parent team.
Creating a tropical follow up team, means you have to make a tropical inpatient team. However, all the patients are tagged "tropical" parent team only. So if you make the sub teams, all the tropical patients have disappeared. @davidmiller is the solution here to manually tag all current tropical patients as inpatients via admin section?

**Comment by davidmiller** [comment]
How many are there ? 
I can do it from the shell.
Alternatively: 

* Create Tropical Inpatients, not as a subteam of Tropical
* Go through Tropical tagging everyone to tropical inpatients also
* make tropical inpatients a subteam of tropical

**Comment by GabPoll** [comment]
the latter seems like a good workflow David. So in essence, you make a new parent team "tropical inpatients". Then create subteams for Tropical (e.g. Tropical follow up), and then make the new parent inpatient team actually a sub team of Tropical, along with Follow up.

I like the solution and looks implementable from admin. However, hold off for now till we work out workflow. Reluctant to add a manual step and risk patients being forgotten on list in some way. Feels like a short term plaster that may create problems down the line.

**Comment by michaeledwardmarks** [comment]
I 100% agree.
I think when we implement this change it needs to be all in one go, flow and all.
Creating a new subteam is trivial but it is the flow that is vital.
Otherwise I consider there to be a significant risk of patients not ending up on correct lists, etc etc
So we don't do this in 0.4 but in 0.5!

**Comment by davidmiller** [comment]
@michaeledwardmarks @gabpoll is there a clear consensus over what we'd like to do here ?

**Comment by michaeledwardmarks** [comment]
Closing this
