### ISSUE TITLE
As a junior doctor on call, I want to see +/- print a single list of all ID, Tropical & Immune inpatients

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#613]
And for this list to:
a) be ordered by location around the hospital
b) not include follow ups (ref #612)

This is because one/ two doctors sees all these patients on weekend, and want an ordered list of your patients for the weekend. Helps planning order you see them, where they are, etc.... Makes sense to me from ward days. 

Notable to say that current systems (or previous Word lists), do NOT have such functionality, so this would be a definite enhancement (i.e. win for the platform), not just plugging a gap.

**Comment by GabPoll** [comment]
just realised this is a narrower spectrum duplicate of #120.
The only difference is that this is a specific use case of joint list printing, so @davidmiller if easier to implement on a one off basis, can leave open. #120 more complex as there is a customisability element to it. 

I'm making distinction, as this issue is specifically user requested, whereas at the moment i can't conceive of any other user group that would request such a thing - i.e. #120 could be a possible short term overkill.

**Comment by davidmiller** [comment]
@GabPoll Fairly sure #120 was specifically requested by a user on the ward to @drcjar  :) 

Could well have been this set of teams!

Imagine we would do this by creating a Virtual Ward Round now - for these teams, with that ordering/exclusion, and adding a "print ward round" feature.

**Comment by GabPoll** [comment]
nice solution @davidmiller with the ward round bit & print ward round option. Suspect this may come post 0.4, as for that release, it is much more important we road test & optimise #614 first

**Comment by michaeledwardmarks** [comment]
The previous request #120 did come from the same group of users so suggest we kill one of the two issues - therefore closing this one.

**Comment by GabPoll** [comment]
@michaeledwardmarks agree to close re duplication, but actually not the same users. Yes, both ID SHOs, but different bunch suggesting same thing. Good to get feel not just certain users. I think bumps this up list of priorities of user requested features.
