### ISSUE TITLE
As a junior doctor, I find the printed list font too small and has too much white space (margins too wide)

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#614]
This is an old issue, but given pending 0.4 release, i wanted to raise as an issue so that we specifically test how this behaves on this release. Also a possible opportunity to change things.

**Comment by michaeledwardmarks** [comment]
Difficult as can't reliably reproduce....thoughts?

**Comment by davidmiller** [comment]
There are a couple things I want to change based on investigations me & @GabPoll did in the tower. 

This is useful as an aide memoire for me to make sure that I actually change them !

**Comment by davidmiller** [comment]
We've bumped the font size from 8 -> 12 when you print. 
This will be better, let's see what comes out and see if people still want it bigger etc.

**Comment by GabPoll** [comment]
ok - i guess we'll test this once on elCID test.

**Comment by michaeledwardmarks** [comment]
@davidmiller:
@gabpoll had a look at the print preview of this on 0.4 and thinks remains an issue.
Could we get a dev-time estimate for another crack?

**Comment by GabPoll** [comment]
this might include a real world trip to HTD office to print and trial

**Comment by davidmiller** [comment]
@GabPoll Have we canvassed the users who were complaining of this originally? 
What do they think of the new print font size?

**Comment by GabPoll** [comment]
not yet canvassed. Will do so when i'm back in person. Nevertheless, the print preview on FF still has lots of white space on it, and font size doesn't look too different to before. Will check back on this when in London.
Keeping this open as this has been a simmering issue since day 1, and we should be seen to squash it if it is still an issue.

**Comment by GabPoll** [comment]
since 0.4, we've had no negative feedback and one positive feedback specifically addressing the font size being larger and better.

Also, printing is now on the hackpad for deployment testing, so can check it every time. Hence I reckon close this issue. Always easy to re-open.
