### ISSUE TITLE
Text in OPAT plan in single patient view is all bold - intentional?

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#615]
Really a heads up for @7575colli. Doesn't look right to me, I would make only headings in bold. Low priority if no one bothered! May also be fixed in 0.4 anyway.

**Comment by GabPoll** [comment]
actually, same seen in clinical advice for non-OPAT pts.

**Comment by davidmiller** [comment]
@GabPoll Is this still a thing in 0.4 if not, I think we should probably close ? 

If so, can you explain what it is ! :)

/cc @michaeledwardmarks

**Comment by GabPoll** [comment]
seems fixed for OPAT r/v on 0.4, so prob redundant issue.
Unable to check clinical advice until #616 fixed as well.

**Comment by michaeledwardmarks** [comment]
Correct now as far as I can see including in clinical advice.

**Comment by GabPoll** [comment]
yep, agree fixed. Thx @davidmiller
