### ISSUE TITLE
Unable to save clinical advice on 0.4-test

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#616]
"Item could not be saved". Red line constantly going left to right in the background.

Issue for pts on micro-haem list

**Comment by GabPoll** [comment]
Also a bug if trying to add C.A. from single pt view

**Comment by michaeledwardmarks** [comment]
Error is:

POST http://elcid04-test.herokuapp.com/api/v0.1/microbiology_input/ 500 (INTERNAL SERVER ERROR)(anonymous function) @ angular.28f401490ec3.js:8495sendReq @ angular.28f401490ec3.js:8291serverRequest @ angular.28f401490ec3.js:8025wrappedCallback @ angular.28f401490ec3.js:11498wrappedCallback @ angular.28f401490ec3.js:11498(anonymous function) @ angular.28f401490ec3.js:11584Scope.$eval @ angular.28f401490ec3.js:12608Scope.$digest @ angular.28f401490ec3.js:12420Scope.$apply @ angular.28f401490ec3.js:12712(anonymous function) @ angular.28f401490ec3.js:18980jQuery.event.dispatch @ jquery.3b80424646a7.js:4624elemData.handle @ jquery.3b80424646a7.js:4292

**Comment by davidmiller** [comment]
This is now fixed and deployed to elcid04-test.

**Comment by GabPoll** [comment]
Fixed, thank you @davidmiller
