### ISSUE TITLE
Unable to save drug allergy in 0.4-test

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#618]
Prob same bug as #616, as it gives same error dialog box. "item could not be saved"

**Comment by michaeledwardmarks** [comment]
The error is:

POST http://elcid04-test.herokuapp.com/api/v0.1/allergies/ 500 (INTERNAL SERVER ERROR)(anonymous function) @ angular.28f401490ec3.js:8495sendReq @ angular.28f401490ec3.js:8291serverRequest @ angular.28f401490ec3.js:8025wrappedCallback @ angular.28f401490ec3.js:11498wrappedCallback @ angular.28f401490ec3.js:11498(anonymous function) @ angular.28f401490ec3.js:11584Scope.$eval @ angular.28f401490ec3.js:12608Scope.$digest @ angular.28f401490ec3.js:12420Scope.$apply @ angular.28f401490ec3.js:12712(anonymous function) @ angular.28f401490ec3.js:18980jQuery.event.dispatch @ jquery.3b80424646a7.js:4624elemData.handle @ jquery.3b80424646a7.js:4292

**Comment by davidmiller** [comment]
This is now fixed and deployed to elcid04-test

**Comment by GabPoll** [comment]
bug squashed

**Comment by michaeledwardmarks** [comment]
I can't test anything because the elcid website never loads. :(

**Comment by michaeledwardmarks** [comment]
I can't test anything because the elcid website never loads. 
Sadly I think this is because both the WiFi networks I have are running sooooooo slooowly
:(
