### ISSUE TITLE
In clinical advice modal, cannot select "Reason for clinical interaction" by typing

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#619]
I'm sure this is a regression. Previously you would tab onto it, type "A", and the box would select "Antibiotic stewardship round", then could tab onto the next field.

At present, it necessitates a mouse action or scrolling up & down with arrows.
Priority 1000 (i.e. low)

**Comment by davidmiller** [comment]
@GabPoll Are you sure ? 

I can't reproduce this - e.g. I can still navigate by typing.

This is a browser level feature though - it's not something that our application is doing !

**Comment by michaeledwardmarks** [comment]
To me this is now a drop down (rahther than a look up list) which i think is correct.
As such it is menu selection not typing

**Comment by GabPoll** [comment]
agree, it is drop down, but conventionally you can tab onto the drop down and then type the content to give you a selection. You could do this in elCID 0.3 advanced search as you tabbed across, but now I realise not previously in CA anyway. You can navigate up and down with keyboard arrows. This is fine. No longer an issue. Sorry for wasting time.

**Comment by michaeledwardmarks** [comment]
No problemo.
I'm currently causing havoc anyway.

**Comment by davidmiller** [comment]
@GabPoll I can do exactly what you want to do e.g. tab onto reason and start typing !

**Comment by GabPoll** [comment]
How unusual @davidmiller . Using Chrome 41, Win 7. I suggest we leave it for now. If there was a tag for @gabpoll sub-issues, this would be one of them!

**Comment by davidmiller** [comment]
@GabPoll Can you do that on any other drop down list on that browser/os ? (It's really a browser thing not an elCID / OPAL thing I promise you ! )

**Comment by GabPoll** [comment]
@davidmiller i've now tried FF on Win 8.1. Still doesn't work. Honestly, not an issue.
