### ISSUE TITLE
Travel Modal

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#620]
For both walk-in and non-walk-in
Should have a "No Travel" button.
Very keen for this to be part of 0.4 as I think very important (especially following Maddy conversation about data quality)

**Comment by davidmiller** [comment]
What does that button actually do ? 

Can you express it in the form of a user need ? ;)

e.g. I think it's maybe:

> As an academic
> I need to distinguish between episodes where travel was not recorded and where there was no travel
> So that I can understand the service better

I think it might be a bit late for 0.4.

But it looks like we'll have a relatively light 0.5 release following hot on it's heels!

**Comment by michaeledwardmarks** [comment]
As a clinical user I want to be able to record actively that someone hasn't travelled. 

As an academic user I want to be able to distinguish - Actually no travel VS  no travel entered because user forgot/didn't bother. 

E.g need to make "person didn't travel" a positive statement rather than trying to infer it from the absence of travel data

**Comment by michaeledwardmarks** [comment]
lovely!
