### ISSUE TITLE
Adding patient for nurse triage shows DOB error but works

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#623]
Odd behaviour.
- Nurse triage list
- Add patient 
- enter new hosp no.
- suggests adding DOB
- add correct DOB and then changes DOB field to red (like an error)
- wait a bit, it goes back to "Search number" modal
- wait a bit longer that modal disappears and patient is on the list.

Looks like an error occurring when there isn't one. Doing it on Chrome 41, Win 7.

**Comment by davidmiller** [comment]
@GabPoll This is a super old issue :) 

Special case of openhealthcare/opal#247 - this has always been the case !

**Comment by GabPoll** [comment]
yes and no though.
If you add a patient onto the micro list now, this error is not seen. Perhaps it's all processed quicker. Very marked when adding on nurse triage.

**Comment by davidmiller** [comment]
I'm not saying we shouldn't fix it - I'm saying it's been there since the very beginning but nobody's gotten around to / prioritised it yet!

**Comment by GabPoll** [comment]
ok, in which case, i'll put it in 0.5 milestone so we can fix it then. It just looks so wrong and hangs around sufficiently long time that someone may click something else. I did it, and only later realised the patient had been added to the list after all

**Comment by davidmiller** [comment]
This was fixed Dec 2015 in https://github.com/openhealthcare/opal/issues/247 :)
