### ISSUE TITLE
Create Letter button and Modal for OPAT

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#624]
See below.
I think now we actually just go for one letter type in first iteration

**Comment by davidmiller** [comment]
> As an OPAT User
> I want to copy & paste narrative blocks of text about patients
> So that I can create a letter to send out & for their permanent records

**Comment by michaeledwardmarks** [comment]
The more I think about this and compare the letters @7575colli @jonnylambourne and Sarah Logan have asked for in different settings, plus seeing how this works in Walk-In, the better I think for a first iteration it is just to generate an overview, people can then edit within word (cutting out stuff that isn't needed). 

Because 
- the main variation actually is in Clinic Codes, Addressee etc - and CDR does all that, so we can ignore.
- it will always be easy to remove stuff not needed
- it will always be annoying to generate not quite enough information.

Therefore the generic OPAT letter template for iteration 0.1 should be:


__Indication for OPAT:__ All entries from Diagnosis/Issues (As bullet point list)

__PMH:__  All entries from PMH (as bullet point list)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

__Allergies:__ All entries from Allergies (as bullet point list)

__Antimicrobials:__ All entries from antimicrobials displayed as per instructions below
- Most recent first
- Name, Dose, Frequency, Route, Administered by 

__Current vascular access:__ 
- Most recent (line) (date inserted) (external length) (comments)

__Observations:__ Most recent date-time stamped set of obs

__OPAT Plan:__ Most recent OPAT Plan Entry

__Upcoming Appointments__: Upcoming events

**Comment by davidmiller** [comment]
First pass deployed to elcid04-test - do take a look.

**Comment by michaeledwardmarks** [comment]
@davidmiller  
Great first pass.

Comments - mostly a reflection of me not providing any formatting guidance in my earlier post and you (correctly) doing what I said!

__Antimicrobial formatting__
Mostly formatting tweaks
Drug Dose Frequency (No commas) "delivered by" Delivered-By Subfield.  "Started on" Start-Date "- due to finish on" End-Date
e.g
Flucloaxcillin 2g QDS delivered by District Nurse. Started on 01/02/2015 - due to end on 30/02/2015
(currently shows as Flucloxacillin,2G,QDS,District Nurse)

__Current Vascular Access formatting__
Line-type "-" Location. "Inserted on" Insertion-Date". "External length at insertion" external-length
e.g
Hickmann-Line - Left Subclavian. Inserted on 23/04/2015. External length at insertion 3cm.


__OPAT Plan__
Doesn't seem to go in to the letter???

__Observations__
Can't add via single patient view at moment so can't check if these come in to the letter.

**Comment by michaeledwardmarks** [comment]
Not seeing these updates.
Have tried a refresh....

**Comment by davidmiller** [comment]
Now deployed to elcid04-test

**Comment by michaeledwardmarks** [comment]
Fab.
I think we call this a good first draft and deploy.

**Comment by davidmiller** [comment]
Ace !  :)
