### ISSUE TITLE
Walk-in patients need an Observations button on List view

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#628]
Because people will only use list view in Walk-In and currently it is impossible to add observations from list view

**Comment by michaeledwardmarks** [comment]
@davidmiller
Either 
1) These updates have all gone somewhere other than elcid04-test
2) I'm not getting them despite hard refreshing
3) something else???
Because I can't see any of the 'fixed' issue changes online

**Comment by davidmiller** [comment]
You can now add observations like any other list column on elcid04-test

**Comment by michaeledwardmarks** [comment]
Is indeed!
