### ISSUE TITLE
Set discharge date for walk-in patients

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#629]
Like discharged last week

**Comment by michaeledwardmarks** [comment]
For people whose date of appointment is within the last 7 days

**Comment by michaeledwardmarks** [comment]
@davidmiller
If Discharge from Walk-in set a Discharge Date then the Discharged Last Week list would do this already using the filter I think?

e.g If a date of discharge (today) was set when 
- the nurse completes the "Nurse Led Care" modal
- the Doctor clicks the "End of Appointment button"  (Regardless of outcome e.g regadless of if outstanding result/admitted to ward etc)

Thoughts?

**Comment by davidmiller** [comment]
As ever, yes, in principle :) 

Who wants to look at Walk in patients from last week ? Why ? Can you express as e.g. As X I want to Y so that Z ? At the minute I don't really have a good sense of the value of X, Y or Z  !  ;)

**Comment by michaeledwardmarks** [comment]
Walk in review meeting on Friday AM.
Discuss the cases of the last week. 
Led by a consultant and the weeks walk in doctor.
Currently done by looking at a book which people stick patient labels in.

**Comment by michaeledwardmarks** [comment]
Actions from this
- [ ] Nurse led discharge modal should set discharge today
- [ ] Doctor End of Appointment button should set discharge date (regardless of if person moved to review list or not) - today

**Comment by davidmiller** [comment]
- [ ] Unticked
- [x] Done

**Comment by michaeledwardmarks** [comment]
@davidmiller
If I discharge someone from walk-in via end of appointment should they now show up in DLW under Walk-In?

**Comment by michaeledwardmarks** [comment]
@davidmiller 
Having played with this it seems to me that although a discharged date does get set this doesn't behave exactly the same as other discharged dates.
For example see the search result, patient detail view and admin section of a patient. The former doesn't have the discharge date and the latter two do.

Note that whilst a discharge date is set (with above noted) that the patient doesn't show up on DLW

![screen shot 2015-09-01 at 21 12 37](https://cloud.githubusercontent.com/assets/4578105/9615142/46edf14a-50ee-11e5-8162-5a6a0b9bb6c3.png)

![screen shot 2015-09-01 at 21 12 43](https://cloud.githubusercontent.com/assets/4578105/9615148/4b6efc28-50ee-11e5-9685-20ef856b949a.png)

![screen shot 2015-09-01 at 21 14 23](https://cloud.githubusercontent.com/assets/4578105/9615184/7c575a92-50ee-11e5-9995-46df4ab0b508.png)

**Comment by davidmiller** [comment]
The discharge date is def being set - I've also updated the DLW criteria to include walkin episodes.

I think that's it for this ticket ?

**Comment by michaeledwardmarks** [comment]
Great. 
Not sure how easy - but....
It is great that the clinic letter button is on this for Walk-In patients.
Is it possible/easy to make the end-of-appointment button NOT be there if viewing on DLW (same reason as the confusion caused by the discharge button being on DLW that we had)
