### ISSUE TITLE
List printout apparently doesn't have team name on it!

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#630]
Reported by a real user

**Comment by GabPoll** [comment]
@davidmiller - is this best fixed & tested together with #614, perhaps even once pushed to test server?

**Comment by GabPoll** [comment]
so this is fixed - shall we keep open till we ask someone who prints the list whether it works? I'm sure it does, but not necessarily the kind of moan that would be forthcoming first thing in the morning pre ward round.

**Comment by davidmiller** [comment]
I think we can close it - it's definitely on the piece of paper when you print the list !
