### ISSUE TITLE
Management field - intermittently prompts hospital number modal: Problem passing to a third state?

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#634]
In Walk-in we have a similar version of the previous #516 bug - according to @davidmiller this was due to openhealthcare/opal#249 - which is a by-product of #452

Move patient from Walk-in Nurse to Walk-In Doctor
Leave Management Field Blank
Click End of Appointment
Modal prompts need to complete Management
start typing drink in advice box
Hospital number modal opens (BUG)
Can't use back space in Advice Box (BUG)

We saw similar at one point with the presenting complaint modal (#516)

**Comment by davidmiller** [comment]
Great spot @michaeledwardmarks - and great psychic debugging powers :) 

Was exactly the same thing. 

Now no longer the case on elcid04-test

**Comment by michaeledwardmarks** [comment]
Perfect.
