### ISSUE TITLE
Can't save advanced searches

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#636]
Error seen on elcid04-test
POST http://elcid04-test.herokuapp.com/filters/ 404 (NOT FOUND)(anonymous function) @ angular.28f401490ec3.js:8495sendReq @ angular.28f401490ec3.js:8291serverRequest @ angular.28f401490ec3.js:8025deferred.promise.then.wrappedCallback @ angular.28f401490ec3.js:11498deferred.promise.then.wrappedCallback @ angular.28f401490ec3.js:11498(anonymous function) @ angular.28f401490ec3.js:11584Scope.$eval @ angular.28f401490ec3.js:12608Scope.$digest @ angular.28f401490ec3.js:12420Scope.$apply @ angular.28f401490ec3.js:12712(anonymous function) @ angular.28f401490ec3.js:18980jQuery.event.dispatch @ jquery.3b80424646a7.js:4624elemData.handle @ jquery.3b80424646a7.js:4292

**Comment by davidmiller** [comment]
You can save advanced searches again - deployed to elcid04 test

**Comment by michaeledwardmarks** [comment]
Fixed.
