### ISSUE TITLE
Can't filter Discharged Last Week

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#637]
![screen shot 2015-05-13 at 07 20 44](https://cloud.githubusercontent.com/assets/4578105/7600729/96cf3332-f940-11e4-823b-fce58bf4fef4.png)

There is a filter button but I don't seem to be able to click it!

**Comment by davidmiller** [comment]
@michaeledwardmarks @gabpoll

The filter is back & deployed to elcid04-test

**Comment by michaeledwardmarks** [comment]
Fixed
