### ISSUE TITLE
Add a letter for Walk-In Nurse

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#640]
Take the diagnosis from the Nurse-Led Management thing? 
Otherwise identical to the Walk In Dr letter

**Comment by michaeledwardmarks** [comment]
How do I access this letter?

**Comment by davidmiller** [comment]
Now deployed to elcid04-test

**Comment by michaeledwardmarks** [comment]
Ok. 
So the tricky thing here is that they don't enter the diagnosis or the management till the Nurse Led Discharge modal - but once they complete that the patient disappears.

What about?? making this a button on the Nurse Led Discharge Modal?

**Comment by davidmiller** [comment]
Oh - I see what you mean ! 

What about automatically opening the Nurse clinic letter as the last step in the process rather than a button?

**Comment by michaeledwardmarks** [comment]
Yes that might work.
At the top of the letter, after the name could we add the DOB and Hospital Number.
I say this because I think the nurses may end up just copying and pasting in to a word document and printing for the notes rather than doing a formal CDR letter - I may be wrong, but adding these 2 details provides relevant ID's in cse they do.

e.g
Re: Name
DOB
Hospital Number

**Comment by davidmiller** [comment]
The nurse letter now opens automatically - deployed to elcid04-test

**Comment by michaeledwardmarks** [comment]
Perfect.
could we add the hospital number as above.
Would remove the Nurse Clinic Letter button

**Comment by davidmiller** [comment]
Deployed!

**Comment by michaeledwardmarks** [comment]
Letter no longer coming up when I discharge someone via Nurse Led Care modal

**Comment by davidmiller** [comment]
Comes up fine for me - can you go through the steps to reproduce it not coming up ?

**Comment by michaeledwardmarks** [comment]
Comes up if reason==treated by nurse
doesn't come up if reason !==treated by nurse

**Comment by davidmiller** [comment]
That's deliberate on my part! 
(https://github.com/openhealthcare/opal-walk-in/blob/master/walkin/static/js/walkin/controllers/walkin_discharge.js#L94)

Perhaps I don't fully understand the flow?

I understood from above that it needed to have Nurse led diagnosis information in it? 
Which is only available if the reason is treated by Nurse.

This is a good example of why capturing things in the form 'As a, I want, So that" is useful :)
Because the so that section allows us/me to ask questions that mean I can understand how these flows should work!

On reflection, I think we should put the letter button back somewhere.
At the minute if you mis-copy-and-paste or close the letter modal accidentally there is no way to get it up again.
Perhaps details view, showing only under some conditions?

**Comment by davidmiller** [comment]
@michaeledwardmarks - can you help me figure out what's I'm missing here ?

**Comment by michaeledwardmarks** [comment]
I think this is fine for a first pass.
