### ISSUE TITLE
Can there be a back button?

### ISSUE THREAD

**Issue by lauranabarro** [openhealthcare/elcid#642]
On the doctor review page, can there be a back button next to the end of appointment button to send a patient back to nurses/triage in case they are accidentally put into the wrong clinic?

**Comment by lauranabarro** [comment]
Similarly, can there be a back button on the review list to send someone back to doctors clinic? I have just sent someone to the review list before I have created his letter. Once he is on the review list,I don't think I can create a letter for him...I may be being blond about this!

Thanks
Laura

**Comment by michaeledwardmarks** [comment]
I think #712 and #710 make this redundant?

**Comment by michaeledwardmarks** [comment]
Lets review this with some feedback from real world.
