### ISSUE TITLE
Wrong date format in History tab

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#653]
currently yyyy-mm-dd

should be dd-mm-yyyy

thoughts @michaeledwardmarks  on this one first please

**Comment by michaeledwardmarks** [comment]
well.
YYYY-MM-DD is actually the international date format.
But I agree that in reality people in UK use DD-MM-YYYY

**Comment by GabPoll** [comment]
i think it should be dd-mm-yyyy

at the moment it's better than before, but it's dd-mm-yy. @fredkingham have a look at date format check patient on Micro-haem list

**Comment by GabPoll** [comment]
same applies for how it should display on patient details view

**Comment by davidmiller** [comment]
@GabPoll What we're doing now is using the same date formatting that's used everywhere else in elCID - e.g. 

For this year dd-mm
For older than this year dd-mm-yy

That's the case for every other date  :) 

I'd argue for consistency - if we want to change it to full years we should change it everywhere !

**Comment by GabPoll** [comment]
ok, in which case leave for now. If we want to change overall, can open separate ticket

@michaeledwardmarks what do you think? I'm worried about patients discharged on 12th January 2014 for example. May not be that obvious date & year on that if format is dd-mm-yyyy
