### ISSUE TITLE
OPAT - live database - unable to discharge SI from current list  

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#656]
RE: SI on current list 

click 'completed IV', then 'completed treatment', then 'unplanned stop', then unplanned stop reason: 'other' 

error message: item could not be saved

**Comment by davidmiller** [comment]
This is another instance of #517 and openhealthcare/opal#255

I've removed the duplicate tags on the live server - @7575colli you should now be able to remove the patient from the list
