### ISSUE TITLE
OPAT - Live database - AC on both current and follow up list 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#657]
RE: AC

Pt was addedd as new referral when still on follow up list, therfore has two entrys - one on current list and one on follow up list. 

is it possible in future if the pt is on follow up list and is added as a new referral that the entry is moved from followup to new referral list to prevent duplication  e3wq

**Comment by michaeledwardmarks** [comment]
@7575colli 
Out of interest why did someone add him if he already existed in the OPAT list?

We can look at improving how this is handled in a future release.

**Comment by 7575colli** [comment]
User error

**Comment by davidmiller** [comment]
Agree - we should probably stop this from happening!

For now, I'd suggest just remove the patient on the referral list as if you were rejecting them.

I've noted the issue as openhealthcare/opal-opat#1
