### ISSUE TITLE
OPAT-Referrals weirdness 

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#658]
- Shows all sorts of action buttons on the left including non-relevant ones (symptoms, confirm discharge etc)
The drop down for teams  just showing [[tag_display[currentTag]] / [[tag_display[currentSubTag] ]]

Patient name not showing on sidebar

No patients on list

Suggest @davidmiller investigation!

Debugging slow in the Solomon Islands but possible issue is "demopgraphics is undefined"

**Comment by davidmiller** [comment]
I'm not entirely sure how we end up with patients that don't have an associated Demographics record.

This should be created automatically when we create a patient, and shouldn't be deleted.

On the live server, the relevant entry has a demographics record, so it looks like something has gone wrong with the data migration.

**Comment by davidmiller** [comment]
@michaeledwardmarks this should now be fixed on ELCIDT - but do look out for any other data issues!
