### ISSUE TITLE
Jumbled order of teams in drop down menu on list view 

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#662]
Only happened in last update to elCID test, i think - i.e. a v recent regression

Not really a bug, but looks messy in my view. @michaeledwardmarks ? Assigning to 0.4, but @davidmiller if non-trivial, can kick it.

**Comment by davidmiller** [comment]
So, I think that what's happened is that the ordering algorithm is slightly different in 0.4. 

Take a look at the ordering values for e.g. the Gosh demo - we should add "update ordering values" to the deployment hackpad.

**Comment by GabPoll** [comment]
ok, thanks David, done. Will keep issue open as a safety net when double checking to do list
