### ISSUE TITLE
As a user I was to see all search results

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#663]
At the moment, search results don't paginate. They say 1-10 of 15, but there's no way to see the other 5.

Solutions are scrolling longer list - i.e. show all, or pagination. @davidmiller open to suggestions on best technical solution. Putting on 0.5 tentatively, but please remove if part of formal overhaul of search (e.g. extract 2.0).

**Comment by davidmiller** [comment]
@gabpoll @fredkingham I think this is basically done by the new search improvements to 0.5 - close?

**Comment by GabPoll** [comment]
yes, i think it's ok. Page jumps a little when a page's list is not the same length, but not a big deal.
