### ISSUE TITLE
As a User I would like patients to become automatically active when I filter to just one.

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#664]
Pt GF in OPAT follow up list 
- I searched for pt using 'name filter' - only GF shown in the display 
- I selected 'next' then 'back to IV therapy'
- Screen then displayed that pt 'PR' had been moved back to curent pt list 

When i looked in current pt list, PR had indeed moved back to that list from the follow up list, and pt GF remained in the follow up list

**Comment by michaeledwardmarks** [comment]
Not working for me - when I filter to only 1 the original patient on the full list remains active

**Comment by davidmiller** [comment]
@MM Can you check again on Elcid04test - and if it's still not working can you let me know the list and filter term you're using ?

**Comment by michaeledwardmarks** [comment]
Ok - does seem to be working.
Fab.
