### ISSUE TITLE
OPAT - pt addded to elcid 3 times with same hosp no - Cant add pt to OPAT referrals

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#665]
I cant add a pt to OPAT referrals - He has been entered onto elcid 3 times with the same hospital no. 
When i add hosp no to referrals i get the following message:
ERROR: More than one pateint with same hospital number

**Comment by 7575colli** [comment]
There are now 4 entry’s for pt LS on current list  - i couldn’t figure out a way to add him without a creating a hosp no so i put a '-' in front of the hosp no. He is also labelled as an in pt too which has the other associated issues

**Comment by michaeledwardmarks** [comment]
I think this is probably a manifestation of #668

**Comment by 7575colli** [comment]
This isnt unique to this pt - I think it is creating a new episode for everone, which means that it doesnt import all of the old notes.

**Comment by 7575colli** [comment]
Just tried to add a new referral to OPAT (pt is currently on inpt list) - got following error message:
ERROR: More than one patient with same hospital number

The only way that i can override this is to put a symbol in front of the hosp no

**Comment by davidmiller** [comment]
A fix to these issues has been deployed to elcido4-test - please do take a run at it !

(BTW @michaeledwardmarks - yes this was the same thing as #667 )

**Comment by michaeledwardmarks** [comment]
This is fixed by the fix to #668
