### ISSUE TITLE
DLW should allow custom date

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#666]
At moment shows last 7 days.
Ideally would allow:
Last Week
Last Fortnight
Last Month

(Or even last since X with default==7 days)

**Comment by michaeledwardmarks** [comment]
e.g maybe a date picker and shows Discharges since that time

**Comment by davidmiller** [comment]
I think my favourite widget for this is the Toggl one: 

![screen shot 2015-06-15 at 09 24 11](https://cloud.githubusercontent.com/assets/17229/8155884/83a28452-1340-11e5-933d-2a48b5920003.png)

You can click an arbitrary start date, end date, or any of the shortcuts below.
Shortcuts automatically "apply" - that button is only used when you select a date range manually.

**Comment by GabPoll** [comment]
that looks nice @davidmiller . Is that available sort of "off the shelf" among the open source community?

**Comment by davidmiller** [comment]
Nope, it's just from an application I use :) 

Shouldn't be that hard to implement for ourselves though

**Comment by michaeledwardmarks** [comment]
I wonder if we still need this now we have Consultant Review W/R?

**Comment by davidmiller** [comment]
Given that the target for those rounds is now 'without confirmed diagnosis' I think this is moot.

Better reporting / dashboard stuff should still have that widget though :)
