### ISSUE TITLE
Can't create multiple episodes of same hospital number

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#668]
Working through things to try and look at @7575colli issue.
I can't replicate fully but found some things worth fixing ASAP.

Make an Inpatient 
Make an OPAT episode of same patient
Check - these are distinct episodes (_Correct_)
Discharge the inpatient episode
Leave the OPAT episode
Create new Inpatient episode

__Error_
More than one patient with this Hospital Number

TypeError: Cannot read property 'then' of null
    at enter.then.$scope.state (65153f3a72fa.js:4555)
    at wrappedCallback (65153f3a72fa.js:2749)
    at wrappedCallback (65153f3a72fa.js:2749)
    at 65153f3a72fa.js:2754
    at Scope.$eval (65153f3a72fa.js:2779)
    at Scope.$digest (65153f3a72fa.js:2776)
    at Scope.$apply (65153f3a72fa.js:2780)
    at done (65153f3a72fa.js:2597)
    at completeRequest (65153f3a72fa.js:2615)
    at XMLHttpRequest.xhr.onreadystatechange (65153f3a72fa.js:2609)

Not tested on live but likely to be there I imagine

**Comment by michaeledwardmarks** [comment]
Related

Add Inpatient episode
Discharge
Add new Inpatient episode (same patient)
Try to add to OPAT

__Error_
More than one patient with this Hospital Number

TypeError: Cannot read property 'then' of null
at enter.then.$scope.state (65153f3a72fa.js:4555)
at wrappedCallback (65153f3a72fa.js:2749)
at wrappedCallback (65153f3a72fa.js:2749)
at 65153f3a72fa.js:2754
at Scope.$eval (65153f3a72fa.js:2779)
at Scope.$digest (65153f3a72fa.js:2776)
at Scope.$apply (65153f3a72fa.js:2780)
at done (65153f3a72fa.js:2597)
at completeRequest (65153f3a72fa.js:2615)
at XMLHttpRequest.xhr.onreadystatechange (65153f3a72fa.js:2609)

**Comment by michaeledwardmarks** [comment]
Note in admin it still looks like only 1 patient actually exists with that number.
Almost as if the add patient modal can't recognise that the distinct episodes all relate to the same patient somehow.

**Comment by GabPoll** [comment]
I wonder if this is related to the way that search now shows episodes of the same patient on separate lines. I.e. it doesn't recognise that the distinct episodes relate to the same patient. @davidmiller do delete this comment if it's an entirely unrelated issue.

**Comment by GabPoll** [comment]
Related problem with a patient without OPAT episode. 
Pt hosp no t7777. 
Was an inpatient, i discharged, then admitted tagged ID I/P & micro-ortho. 
D/C from ID I/P leaves list (all ok)
Confirm D/C Micro-ortho - leaves list (all ok)
Tried to add same hosp number to make new episode (i.e. admission) - ERROR = ERROR: "More than one patient found with hospital number"

**Comment by michaeledwardmarks** [comment]
This is because the issue is bigger than just the one I described above.

Create patient on Id-Inpatients (Hosp = Whatever)
Go to different "INPATIENT" list e.g Micro-Ortho
Add patient (Hosp = As above)
Added 
BUT
These are separate episodes (e.g different episode numbers). 

This is incorrect - as per #555 
It should be the case that when adding an existing ACTIVE episode to a list of same CATEGORY that the episode is just tagged.
That isn't happening - it is instead creating a whole new episode, and then you end up with two distinct episodes of same CATEGORY and same HOSP_NO
== Problems seen above

**Comment by davidmiller** [comment]
There are two separate problems here: 

Firstly, the incorrect assertion that there are multiple patients with a given hospital number.
This is a regression caused by https://github.com/openhealthcare/opal/commit/89184f535813191e64e3db3c1fe89a8c3696ab50 - which introduced the ability to respect broader permissions over search results - e.g. not having RFH RidRTI patients turn up in search results. (e.g. openhealthcare/opal-research#31)

Secondly, it seems that tagging to multiple inpatient lists is no longer working because of this? 
Will investigate that after fixing the point above.

**Comment by davidmiller** [comment]
A fix to these issues has been deployed to elcido4-test - please do take a run at it !

**Comment by michaeledwardmarks** [comment]
Tagging confirmed fixed

**Comment by michaeledwardmarks** [comment]
Multiple adding works. 
Adding to OPAT works.
