### ISSUE TITLE
Custom Flows are only available on list view, not on Episode or Advice view via a relation to episode categories

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#669]
On referrals page, patient selected then  detailed view opened
When i select 'accept/refuse, a screen appears for DISCHARGING the patient - i cannot accept the patient onto current pt list from the detailed view

**Comment by michaeledwardmarks** [comment]
I'm now certain this is a manifestation of #667
Because as soon as you move to Detail view - Category>Inpatient
And once that happens the accept/refuse button won't work - because that requires Category==OPAT

**Comment by michaeledwardmarks** [comment]
Cancel my comment above.
I changed category manually using Admin to OPAT and still get the Discharge modal not the Accept/Refuse Modal via Details view.
Also on a patient whose category already == OPAT (without admin change) details view I get discharge modal.

On list view for both patients I get the correct Accept/Refuse Modal

**Comment by michaeledwardmarks** [comment]
Same on Heroku

**Comment by davidmiller** [comment]
I think this is incorrect behaviour - but it's unrelated to the 0.4 release.

It's a similar issue to https://github.com/openhealthcare/elcid/issues/471#issuecomment-68057398

As currently implemented, custom flows relate to a team / group of teams rather than the category of episode. 

This is the wrong algorithm - flows should apply to either a team/group of teams _or_ a category of episode.

**Comment by michaeledwardmarks** [comment]
Ok. 
So I agree custom flows should work on single patient view 
Imagine OPAT spend a lot of time on that view so need the flows to work from there .

**Comment by davidmiller** [comment]
This was highlighted yesterday by @7575colli as being something that would help them greatly.

**Comment by michaeledwardmarks** [comment]
Yes and this cross-cuts with some other issues so hopefully can get done in the OPAT release  mid-late September.

**Comment by davidmiller** [comment]
We have some of this now in 0.6, but acceptance criteria is really: 

Must work for:

- [ ] Default flow
- [ ] OPAT
- [ ] Walkin
- [ ] Inpatients custom data collection flow

**Comment by michaeledwardmarks** [comment]
I'm going to close #677 #671 which are specific examples of this problem

**Comment by davidmiller** [comment]
@michaeledwardmarks A fix to this should be deployed to elcid-uch-test now

**Comment by michaeledwardmarks** [comment]
OPAT appears to work.
Walk-In doesnt seem to work - the button just says: Next Stage with no options coming up.
Can't currently test IP flow due to patient add issues

**Comment by michaeledwardmarks** [comment]
When the OPAT patient has no options left - e.g they have Completed OPAT Care - you still get a button in the Custom Flow Button location 
![screen shot 2016-03-29 at 08 51 09](https://cloud.githubusercontent.com/assets/4578105/14101285/69a3725e-f58b-11e5-87d3-12de8eb3f755.png)

Clicking this leads to a non-usable flow modal:

![screen shot 2016-03-29 at 08 52 11](https://cloud.githubusercontent.com/assets/4578105/14101300/8af8cf94-f58b-11e5-97d6-1b1266110ba1.png)

**Comment by michaeledwardmarks** [comment]
No flow buttons appear for Inpatient Admissions
![screen shot 2016-03-29 at 08 55 26](https://cloud.githubusercontent.com/assets/4578105/14101383/ffb40402-f58b-11e5-8f28-38d9245dcef1.png)

**Comment by michaeledwardmarks** [comment]
I still see Flow Buttons for patients who have completed OPAT Care

**Comment by davidmiller** [comment]
@michaeledwardmarks Do you have a link/patient number ?

**Comment by davidmiller** [comment]
OK: found one - http://elcid-uch-test.openhealthcare.org.uk/#/patient/19

**Comment by davidmiller** [comment]
I think this is just in the fixed-but-not-deployed state actually.

We're holding off deployment a little - but should have one later today with a complete mock integration flow for the first time...

**Comment by michaeledwardmarks** [comment]
Cool beans!
