### ISSUE TITLE
OPAT not importing existing episode data

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#670]
Possibly a manifestation of #667 #668

**Comment by michaeledwardmarks** [comment]
Same on Heroku.
Create ID-Inpatient Episode
Save Diagnosis
OPAT-Referral
Add patient
Diagnosis doesn't cross-populate

**Comment by davidmiller** [comment]
A fix to these issues has been deployed to elcido4-test - please do take a run at it !

**Comment by michaeledwardmarks** [comment]
Fixed
