### ISSUE TITLE
Discharge Button Doesn't Work on Episode View

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#671]
On Detail View:
Modal launches correctly
Discharge Date Saves
Category REMAINS Inpatient
Switch to List View:
Patient still on the list with Discharge Date set and Category == INPATIENT

Discharges work correctly from List view

**Comment by GabPoll** [comment]
great minds think alike @michaeledwardmarks 

to put in context @davidmiller - prob not picked up by ID teams yet as mainly use list view. Most likely affecting micro haem but so many patients, haven't noticed. However, this would actively hinder any attempt to keep list size under control.

**Comment by davidmiller** [comment]
This has always been the case - discharged episodes tagged to a team remain on that team list until someone removes it from the list.

When we are on detail view we don' t remove the episode from any lists at all, we just set the discharge date / status.

What has changed is that location now displays 

> "What kind of episode is this" not "What is the status of this episode"

I *think* you're saying that we should display the distinction between active episodes and episodes that are tagged to a list but discharged to the user ?

**Comment by michaeledwardmarks** [comment]
Yes....I think so, e.g should say discharged, which is effectively code for Inactive-Inpatient type episode.
