### ISSUE TITLE
Discharging patients on patient detail view is not working

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#672]
Same issue for both ID & Micro-haem pts.
On list view it works fine.
On patient detail view - if try to discharge, a discharge date is entered, but pt remains an inpatient. The discharge button becomes a "confirm discharge" button. If you click on that again, nothing happens. Pt is at bottom of the list, with a discharge date, but status still inpatient.

This would not help cut down the growing size of micro-haem list!

**Comment by michaeledwardmarks** [comment]
Simultaenous githubbing by me and gabriele.
Closing this one.
