### ISSUE TITLE
Error in flow in 'completed IVs -  unplanned stop'

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#673]
Current pt 
'completed IV'
'Unplanned stop'
reason - 'other' - Please can we add admitted to hospital as another option in this look up list 
= pt dischrged from OPAT

Preferred outcome is for pt to be moved to follow up list

**Comment by michaeledwardmarks** [comment]
We have added this as an option to the dropdown box.
So if you go:
Completed IV
Ongoing Follow-Up
Unplanned Stop
Reason For Stop > Admitted to Hospital
Patient will be moved to OPAT follow-up list.
