### ISSUE TITLE
elCID permits mismatch between Management field entry and End of appointment action

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#678]
I don't think this should happen

So at the moment in Management you can choose "admit to ward", and then end of appointment action can be discharged from clinic.
Can also happen vice versa

**Comment by GabPoll** [comment]
could we not just obtain this info automatically from the patient journey "end of appointment" button?

**Comment by michaeledwardmarks** [comment]
Agree

**Comment by michaeledwardmarks** [comment]
So the changes made by this and #680 allow you to move someone off without filling in where there follow-up is which is not correct - because the end of appointment button doesn't trigger a question on if/where follow-up is
