### ISSUE TITLE
Change management modal to permit free text documentation of telephone calls

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#680]
Thoughts welcome from @michaeledwardmarks & @lauranabarro 

I was playing with walk in yesterday. Very nice. However, noted that there isn't really anywhere to write anything slightly off-piste from what is offered on the proforma.

I wonder whether we need a clinical advice type section (can rename it). This could then also double up as the place to document follow up phone calls. These can then be logged, and there is no need for that piece of documentation to be scanned in by admin staff.

As d/w @davidmiller & @hmaxwellscott yesterday.

**Comment by GabPoll** [comment]
thinking this through a bit more, could the "Management" section become the free text bit (advice is free text there already), and also where you could record telephone advice.

You could drop the follow up field (because it creates problem #678 - see that issue for possible solution), and replace it with "type of advice" with options 
- walk in appointment discussion
- telephone consultation
Perhaps add a date & time field if choose telephone consultation.

As ever pings for thoughts from @michaeledwardmarks @lauranabarro @hmaxwellscott @davidmiller

**Comment by michaeledwardmarks** [comment]
Not a bad idea.
Might work well.

**Comment by davidmiller** [comment]
Isn't Management then a silly name for this field ?

I propose to:

- [ ] Add a clinical notes type field to walkin
- [ ] Make that record type visible on list view for doctors
- [ ] Make management only visible on detail view
- [ ] Infer followup clinics from the end of appointment modal

**Comment by michaeledwardmarks** [comment]
@davidmiller that all sounds very sensible.
Let me know when I should take a look.

**Comment by michaeledwardmarks** [comment]
This column is fine. 
There probably need to be some changes made to list views and some changes made to flow in view of #678 

This needs to be taken in to the letter creation now.

So it should suck in:
Advice Given in Clinic / Telephone Discussion: CLINICAL ADVICE

**Comment by davidmiller** [comment]
- [ ] Needs to add clinical advice

**Comment by GabPoll** [comment]
This looks good now. Looks like CA is there, or have i missed something?

**Comment by michaeledwardmarks** [comment]
It is on the list but it doesn't get pulled in to the letter, which advice entered via the managment modal used to.

**Comment by GabPoll** [comment]
I see, thanks for clarifying
