### ISSUE TITLE
Unable to switch between episodes during a ward round

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#681]
If you're in any ward round, and on the patient view you click History to look at info from a previous episode, it gives error dialog box: Ward Round could not be loaded. Then just tries to load in background and nothing happens. Tried on OPAT & Haem WR.

I think you should be able to look back at previous episodes. Perhaps if you're in a previous episode on ward round view, could have a button to offer return to current ward round episode, and then can continue ward round? Not straight forward solution to this, I know. Thoughts @michaeledwardmarks please.

Seen on heroku & live

**Comment by michaeledwardmarks** [comment]
whilst I agree this is a bug, I really only see this as an issue for Micro-Haem.
The ID ward round (DLW) is very much just about - what was the final diagnosis for that episode and same for OPAT.
Not sure best solution - but more broadly it sounds like the Vanya development is what you want to really resolve this issue.

**Comment by GabPoll** [comment]
I agree. Definitely wouldn't fix for the purpose of the haem round (which isn't used anyway). If it's a non-issue on other rounds, then could even close this issue.

To prevent confusion, do we want to prevent other episodes opening on ward round view? Or perhaps just leave it and see if anyone actually ever comes across this in real life?

**Comment by michaeledwardmarks** [comment]
I'd probably close this issue pending the Haem specific development.
Happy to re-open if needed.

**Comment by davidmiller** [comment]
I think this is still a bug - e.g. on Discharged Last Week either: 

* We shouldn't give you the option to look at the history of other episodes
* The thing that looks like it's a link to another episode should actually be a link to that episode

It's probably quite quick !

**Comment by davidmiller** [comment]
TBH nobody is really complaining about this - and we haven't observed users noticing it.
Haem round is completely different now, and having spent an hour w. the cons. and reg. doing it for the last six months recently, this wasn't mentioned at all. Closing again.
