### ISSUE TITLE
List headers should be frozen when scrolling down the page

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#682]
Regression since 0.4

**Comment by davidmiller** [comment]
> As a User
> I need to see column headings when scrolling down lists
> So that I can remember which column is which for patients without entries

**Comment by davidmiller** [comment]
Sarah Logan recently voted heavily in favour of addressing this sooner rather than later !

**Comment by GabPoll** [comment]
yes, of all the things discussed, this was top irritation bug with no workaround, and affects almost every interaction for all teams that use elCID. Vanya mentioned it too in meeting. Almost priority 0. Priority 0.5?

**Comment by fredkingham** [comment]
@GabPoll can you take  a look at https://elcid04-test.herokuapp.com/#/list/opat/opat_referrals does this fit the bill?

**Comment by GabPoll** [comment]
you;re a genius @fredkingham, thank you.
I'd like this in 0.4.2 please cos it causes so much irritation. @davidmiller  if I close it will it fall off the waffle board?

**Comment by michaeledwardmarks** [comment]
As mentioned in #700 this sort of works.
The list headers (and sidebar - correct) are frozen initially but once you go a long way down the whole page scrolls again.

**Comment by michaeledwardmarks** [comment]
Closed but see #700
