### ISSUE TITLE
Extract CSVs should deal with TextFields containing new lines

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#684]
Currently e.g. Microbiology Input won't deal nicely with carriage returns.

**Comment by GabPoll** [comment]
@michaeledwardmarks have you seen this before? I think this is regression since 0.4. Came up yesterday when planning ID liaison audit. Thx for putting on 0.4.2 @davidmiller

**Comment by michaeledwardmarks** [comment]
no haven't seen but haven't been doing extracts.

**Comment by davidmiller** [comment]
@michaeledwardmarks It's def. a real thing - comes up anywhere with free text entries that span multiple lines - e.g. review / CA / Todo

**Comment by michaeledwardmarks** [comment]
I just did an extract of some multi-line entries and they seem to come out o.k now!
