### ISSUE TITLE
Confirmed final diagnosis should be visible on patient record

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#685]
At the moment it is not.
Should be added to diagnosis modal as a new diagnosis with (CONFIRMED) in brackets.
Otherwise consultant's final say on pt episode (most imp conclusion) is not visible on records on elCID.
Thoughts @michaeledwardmarks & @hmaxwellscott please.

**Comment by michaeledwardmarks** [comment]
Agree.
Not quite sure where it should display but definitely once an episode has had Diagnosis confirmed via DLW it should be clearly displayed as a confirmed final diagnosis
