### ISSUE TITLE
Typos and spelling errors in admin section on elCID need fixing

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#686]
Non urgent, but could do with tidying up.

Too many to list here. Best to arrange a live chat session and fix them one by one live.

**Comment by davidmiller** [comment]
These are all Django admin pluralization things - should be trivial to fix.

**Comment by fredkingham** [comment]
I think this is fixed for opal/elcid and walkin, its deployed to https://elcid04-test.herokuapp.com/admin please take a look @GabPoll

**Comment by GabPoll** [comment]
cheers @fredkingham 
one typo still there: 
  
Change Specimins to should be Specimens (same for singular) - Same for Lab specimens 

couple of other things: 
where it says igg single test, can eat it be IgG single test please? 

and finally, the penultimate - instead of WI, make it Walkin please

**Comment by GabPoll** [comment]
Ace. Perfect. First ticket completed @fredkingham !
