### ISSUE TITLE
De-synonomise CAP and LRTI

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#689]
Raised by the RiD RTI team

**Comment by michaeledwardmarks** [comment]
To be done in Admin @ the time of next deployment

**Comment by GabPoll** [comment]
agree. added to hackpad

**Comment by davidmiller** [comment]
We need to do this in the lookuplist fixtures still

**Comment by michaeledwardmarks** [comment]
This was done at 0.4.2 I believe

**Comment by davidmiller** [comment]
We still need to do other things to finish this - I'll close it when they're done
