### ISSUE TITLE
As a User I would like to enter multi-line comments in General Notes

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#690]
So that I am able to write more free-flowing notes.

@davidmiller has always found this confusing. 

We watched some users also find this confusing yesterday ! 

Thoughts @GabPoll @michaeledwardmarks

**Comment by GabPoll** [comment]
Agree. 

And personally merging general notes & to do might also save everyone time & effort.

**Comment by michaeledwardmarks** [comment]
Agree.
Especially if in the To-Do thing you could do nice checkboxes ala github and then track them being ticked!

**Comment by davidmiller** [comment]
I think that there's almost certainly room for a more expansive TODO thing - tracking a feature wishlist / brain dump here openhealthcare/opal-ideas/issues/4 pending proper user research into what is needed...
