### ISSUE TITLE
Unable to interact with patient details view

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#699]
No button works. Editable fields are not openable, can't add anything.

Big buttons on ribbon work - Lists, Search, Ward Rounds, etc...

Found on https://elcid04-test.herokuapp.com. Seen on both FF & Edge.

**Comment by michaeledwardmarks** [comment]
I'm not seeing this.
I can edit stuff on Patient Detail view..
I've tried inpatient, walk-in and OPAT episodes and they all work for me on patient details view.

**Comment by GabPoll** [comment]
funny, works again, agree @michaeledwardmarks 
I'll close - should be pretty obvious if it happens again!

**Comment by GabPoll** [comment]
Going to re-open again in case we need to work out why this is happening, even if it disappears

**Comment by GabPoll** [comment]
no need to keep open.
