### ISSUE TITLE
Create an Advice-view with episode history

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#701]
creating a new patient detail view with a list of episodes like the below except using gravatars on the timeline

**Comment by fredkingham** [comment]
hey @gabpoll, I think 701 is ready for a review, let me know what you think

 http://elcid04-test.herokuapp.com/#/patient/579007

(the url isn't linked anywhere but its just /#/patient/[[ hospital_number ]])

**Comment by GabPoll** [comment]
Looks v good. Whilst I await function testing, aesthetic comments:
Hosp no & DOB at top in grey now - white please
Dates for each entry on left - prob black font on grey background
link "inpatient" will need renaming - not clear what that means

**Comment by GabPoll** [comment]
Thanks @fredkingham - looks good as well now with allergies.

"Current inpatient admission" would rename to "More details on current episode". That may change as we develop this more. I understand and agree with link. Will develop organically.
