### ISSUE TITLE
On Advice-view, split delete & edit buttons?

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#705]
Was thinking might be good for edit button to be on left of the entry (i.e. to left of date) and delete button further away and separate from edit button, on the right.

Felt more pertinent on advice view - the box is wider and so edit button feels far away from entry you may want to edit.

For discussion, not request (ping @michaeledwardmarks @fredkingham @davidmiller )

**Comment by michaeledwardmarks** [comment]
Yes that might be good.

**Comment by GabPoll** [comment]
thanks @michaeledwardmarks I also thought might be useful for episode view. I always find myself wanting to double click / interact with a previous detail and then have to go and find edit button.

**Comment by davidmiller** [comment]
@GabPoll Is this still relevant ? 
(I'm honestly not that sure what you mean by this all this time later ! )

**Comment by GabPoll** [comment]
not totally sure either now. Nomenclature for "advice view" etc.. has also changed. Let's close and revisit as new observations arise on how to improve interface.
