### ISSUE TITLE
Advice view - Think about highlighting current stuff differently

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#706]
Once you have multiple episodes running together, or even just very long ones it will be important to pull out easily current information.

Depends on how the pages end up but consider:
- If Antibiotic is current: Different colour text
- Display current antibiotics at the top of the page along with the allergies

**Comment by michaeledwardmarks** [comment]
That way a user can look at the key information easily.
This is J - allergic to X, currently on Y, known resistant organisms 1-2-3

Thoughts @GabPoll

**Comment by GabPoll** [comment]
Yes, good idea @michaeledwardmarks . In some ways info should always be at the top. The way @davidmiller and I had envisioned things was that the right hand panel will remain static as the clinical advice scrolls.

Highlighting I agree, it may well need it. Will have to see a little how it develops. Also, luckily we also have another tester out there - VG. He will want to see this in early stages and get feedback directly as to how he wants it. Obviously we can filter inappropriate suggestions, but we can let this be slightly more user-led.

**Comment by michaeledwardmarks** [comment]
It depends on how the left/right column scrolling works out.
But definitely think you want rapid access/highlighting of the current antibiotics

**Comment by michaeledwardmarks** [comment]
This might be better than my waffling about #782

**Comment by davidmiller** [comment]
The ABX element of this was recently deployed to elCID live - greys out past ABX now.
