### ISSUE TITLE
In any episode view need link to advice view

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#707]
Almost certainly in left panel (where history button is). To the clinicians we would probably call it "Complete clinical advice timeline" or something like that.

@michaeledwardmarks agree?

To be honest this should also be on list view, given that the left panel is the same in both views.

**Comment by michaeledwardmarks** [comment]
Yes, sounds sensible.

**Comment by GabPoll** [comment]
not at the moment as access to advice view is limited by user access. Will close and then revisit if needs arise.
