### ISSUE TITLE
List apparently prints funny if done landscape

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#708]
Real feedback from users.

**Comment by michaeledwardmarks** [comment]
apparently it handles people rolling over page breaks not well.
Current solution is printing portrait

**Comment by michaeledwardmarks** [comment]
Page margins could be improved - close to 1 inch

**Comment by GabPoll** [comment]
Presumably printing portrait then results in small font as well?
________________________________

**Comment by michaeledwardmarks** [comment]
No further reports of this so closing at this time.
Note we have a story to always check printing with updates.
