### ISSUE TITLE
Change flow for Walk-In slightly

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#712]
Walk-In Doctor:
End of Appointment.
Limit to two options
- Admit to ward (Unchanged)
- Move to review list
  - This would ask the Follow-up questions (currently asked if you click no Outstanding results)
  - Move patient to review list 

Walk-In Review:
Results Actioned button
- Change wording to "All results are actioned and/or patient has appropriate follow-up"
- Then just a Remove from list button

**Comment by GabPoll** [comment]
Agree, seems sensible workflow.
