### ISSUE TITLE
Walk-In Symptoms

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#715]
I think we should begin discussions of what the next version of this looks like.
I think top half.
Checkboxes of key symptoms (now known as Select2 - 22/10/2015)
Then the duration drop down
Then a free text box (larger than normal - like the ones we use for advice) labelled History of Presenting Complaint

So we get coded key symptoms, plus room for some freedom

**Comment by davidmiller** [comment]
Pushing this back to 0.5 - we'll need to do lots of acceptance and automated testing on this

**Comment by michaeledwardmarks** [comment]
It would be the History of Presenting complaint box that we pull in to the letter (currently we pull the symptoms/date sub-fields).

We can review once we have the new modal

**Comment by davidmiller** [comment]
This is a great iteration on the current state. Suggest reviewing with users again to see if we need to do checkboxes.

**Comment by michaeledwardmarks** [comment]
@davidmiller
The select two bit of this is great but we need to 
1)Drop onset subfield
2) Make the details box bigger and labelled History of Presenting complaint or similar

**Comment by GabPoll** [comment]
@michaeledwardmarks is right - the Walk in symptoms box should look exactly the same as for inpatients.

**Comment by GabPoll** [comment]
This does indeed need fixing for 0.5

**Comment by GabPoll** [comment]
looks done, thanks guys.

**Comment by michaeledwardmarks** [comment]
This needs to work with synonyms in select2

**Comment by michaeledwardmarks** [comment]
I believe Synonyms now work so closing
