### ISSUE TITLE
Key Investigations Nurses Modal

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#716]
Running list of what we think should be added:

- [x] Respiratory Virus PCR

**Comment by davidmiller** [comment]
From the book: 


- [ ] Chickengunya

**Comment by michaeledwardmarks** [comment]
- [ ] Dengue

**Comment by michaeledwardmarks** [comment]
? - [ ] Ricketssia Serology (doesn't currently exist)

**Comment by michaeledwardmarks** [comment]
- [ ] Parasite ID

**Comment by michaeledwardmarks** [comment]
- Rickettsia Serology (needs adding as a test)

**Comment by michaeledwardmarks** [comment]
Note this requires #760 #761 #762

**Comment by michaeledwardmarks** [comment]
On David-Staging this can now be implemented.

**Comment by davidmiller** [comment]
Deployed to david-staging - was only held up by a typo!

**Comment by michaeledwardmarks** [comment]
Fab
