### ISSUE TITLE
Nurses Letter v2.0

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#717]
Based on feedback from Catriona et al.

Mostly just a change to what prompts a letter for nurses.

- Next Button
 -Nurse Led Care

- [x] This modal should show the Diagnosis and Treatment boxes regardless of what is chosen in the drop-down
- [x] A letter should be created regardless of what is chosen in the drop-down

So essentially they always get the letter, and we record the dropdown as an audit/research marker rather than something that determines flow

**Comment by davidmiller** [comment]
Fixed and deployed to http://david-staging.herokuapp.com/

**Comment by michaeledwardmarks** [comment]
Perfect.
