### ISSUE TITLE
Walk-In Nurse Flow QC Checks

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#718]
- When next button is clicked on Walk-In Nurse
- IF NO Obs
 OR
- IF NO HIV-POCT Result
Prompt: You haven't recorded the Obs AND/OR HIV POCT. Please do this before moving the patient on to the next stage.

Because Obs and the HIV-POCT are important pieces of data and we don't to miss these.
For the HIV-POCT we want an entry in RESULT that NOT=PENDING

**Comment by davidmiller** [comment]
Do we definitely want to *prevent* people from moving if there are no obs?

What do we mean here?
Are there situations where you might not take obs? 
Inappropriate referral?

**Comment by michaeledwardmarks** [comment]
The nurses tell me they take one set of obs on everyone partly because it covers them that it was safe to send someone away as inappropriate

**Comment by michaeledwardmarks** [comment]
I guess we mean at least one ob recorded even if not a full set.

**Comment by davidmiller** [comment]
After discussion with @michaeledwardmarks we've decided to prompt users in the first instance, and review after some real world usage.

**Comment by davidmiller** [comment]
Deployed to david-staging !

**Comment by michaeledwardmarks** [comment]
Nice.
