### ISSUE TITLE
Working Out Age

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#719]
We record DOB.
It would be good if the episodes CSV (or demographics or somewhere) spat out the date the episode (not the patient) was created on elCID to make working out age easier. Obviously we record this but we don't spit it out currently

Currently trying to find a good approach to this for OPAT.
We need to think about a long term sensible approach for this.

**Comment by michaeledwardmarks** [comment]
So for OPAT you can do this via OPAT referral date. But still think a generic solution is needed for such a core metric.

**Comment by davidmiller** [comment]
@michaeledwardmarks You mean age at the time of episode?

Me & @fredkingham plan to add timestamp_created and timestamp_modified to all records - this will come in (Probably) 0.5.

**Comment by michaeledwardmarks** [comment]
Perfecto.
I presume we could get this if needed already anyway - because we do record that stuff we just don't spew it out.

**Comment by davidmiller** [comment]
We can get it but it's an expensive operation.

Ticket is https://github.com/openhealthcare/opal/issues/292

**Comment by davidmiller** [comment]
@MM I'm going to close this now that we've started work on openhealthcare/opal#292 ;)
