### ISSUE TITLE
Should the advice view lock new entries instantly?

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#724]
At the moment, it's a bit like #60.

If you type something, you hit save, but then want to quickly add something to that entry, you can't do it.

Option a) - leave all unlocked to be re-edited
Option b) - resurrect a version of #431 or some kind of time out after which an entry is locked.

Ping @michaeledwardmarks @davidmiller @fredkingham

**Comment by davidmiller** [comment]
Seems that we've parked all discussion of locking entries for the foreseeable TBH.
It's a really hard thing to get right - none of the liaison or inpatient services seem particularly concerned about this, I'm closing until someone comes and requests again.
