### ISSUE TITLE
Historic Tags not in CSV

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#727]
These should be in the location.csv of an export

**Comment by michaeledwardmarks** [comment]
Recover Deleted Taggings in OPAL>Taggings contains these

Proof of principle on Heroku.
search team==ID_Liaison
3 hits
Episode 1/36/92
36 & 92 are actively on the ID-Liaison list
1 is not
Go to 
OPAL>Taggings>Recover Deleted Taggings
Find all deleted ID_Liaison tags
There is only 1 
It is for the patient whose episode ID is 1

Hope that helps

**Comment by davidmiller** [comment]
@michaeledwardmarks Fix to this is deployed to elcid04-staging as part of the 0.5 release if you'd like to test ?

**Comment by michaeledwardmarks** [comment]
This doesn't seem to work for me. 
For example Episode 2 of david-staging was tagged ID-Inpatients, but that doesn't come out in the CSV,

**Comment by davidmiller** [comment]
Yep, deployed to elcid04-staging as part of the 0.5 release - david-staging is 0.4.3

**Comment by michaeledwardmarks** [comment]
ahhh!

**Comment by michaeledwardmarks** [comment]
Not currently working for me on elcid0.4
I downloaded tropical patients - there are 3.
Only 1 of them has the tropical tag in the tagging column

**Comment by michaeledwardmarks** [comment]
Fixed
