### ISSUE TITLE
The advice view timeline should clearly display reason for clinical interaction on each occasion

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#728]
e.g. Clinical advice (perhaps only that in bold). M Marks with Haem SHO
or
Micro Haem ward G Poll with Haem SpR

The wording less important than the fact it's there at the moment.

**Comment by davidmiller** [comment]
We need to display the reason for clinical interaction field somewhere.

**Comment by GabPoll** [comment]
thank you @davidmiller - have amended ticket title accordingly to clarify.

**Comment by davidmiller** [comment]
Done and deployed to http://elcid04-test.herokuapp.com/#/patient/579007

**Comment by GabPoll** [comment]
squished
