### ISSUE TITLE
How can we better record the team giving advice

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#731]
Specifically how can we separate out clinical advice modal entries as to whether the advice was given by micro or ID or indeed another team. 

You can't using tagging because patients tagged to both lists.

Intuitively you can use the name of the person giving advice.
But - juniors in particular rotate.
E.g last year advice from Colin Brown would be ID liaison and this year it would be micro. 

You could still sort that out but only tediously and assuming you had a list of who was doing what job when. 

This might come back to the discussion of teams/roles. 

Open to other suggestions.

We need some serious thought on this as otherwise there is a risk of data becoming very difficult to audit.

**Comment by GabPoll** [comment]
it depends whether you want person specific audit vs service specific advice. I would think person specific less useful. More interesting is all the advice given by any one service. And while you do that, you collect the person info as well.

**Comment by michaeledwardmarks** [comment]
Agree.

the issue is currently we identify the person giving advice but not strong way (for juniors) of linking them to a specific service

**Comment by davidmiller** [comment]
This is a bigger problem than e.g. elCID

I'm not sure that there is a good way to generically identify the role a given person was currently giving advice in at a given time...

I'm closing this - if a way to do that presents itself more than happy to reconsider, but I imagine this to be v. much non-trivial!
