### ISSUE TITLE
Haematology patients to be added via a new Referral button in v0.5

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#732]
This will be called "Haematology referral". 

- Will work just like OPAT referral
- Will start an inpatient episode
- Will tag patient micro_haem

Gill will do this.
THis will not be the only way to get tagged micro-haem (separate ticket)

**Comment by michaeledwardmarks** [comment]
Do we have a way people will ever come off that tag?

**Comment by GabPoll** [comment]
At the moment no. We think that is not important. We could timeout their tags as previously discussed. Not sure it's critical. Thoughts @davidmiller please

**Comment by davidmiller** [comment]
@michaeledwardmarks FYI - Haem list is dead in 0.5

**Comment by GabPoll** [comment]
I should say that patients can still be tagged micro haem patients in the same way as before - i.e. could add a patient and tag them, or can add a tag to an existing patient on a list - e.g. if an ID patient is then found to have a haem malignancy. Should not interfere with discharging procedures of inpatients. Correct @michaeledwardmarks

**Comment by GabPoll** [comment]
@davidmiller agree haem list dead. Wasn't sure how to define that as a github ticket!

But the haem tag is important for audit purposes and also cos it will open up a special modal (still transcribing issues)

**Comment by davidmiller** [comment]
@gabpoll IIUC Gill enters more details than just the basic demographics - is that so?

If that's the case then we're going to need to figure out the whole user journey from her perspective :)

**Comment by GabPoll** [comment]
@davidmiller Gill currently enters demographics then a single copy & paste splurge into a diagnosis details box. Could we configure the Referral button to enable entry of demographics + 1 other details box such as this, or is Referrals hard wired to be demographics only?

**Comment by GabPoll** [comment]
To clarify above point, the extra box/field visible of Micro-haem referral will be "Diagnosis -> condition"

**Comment by GabPoll** [comment]
Beautiful. 

When you get to diagnosis modal, it is still labelled "patient details". Also, after referral made, offers link to microhaem list. This will not exist.

**Comment by GabPoll** [comment]
Also there is something funny about the referral section. I somehow feel it should be a search box for any part of patient details, like the one in the ribbon at the top. Instead it only searches number. I initially typed in the name of the patient, and then it created a new patient with that name as the hospital number.

@davidmiller, i think this came up before, right? I think when we spoke to Sarah.

**Comment by davidmiller** [comment]
@GabPoll That wasn't what I thought she was talking about ! 

AFAICT She thought that you clicked the button to start finding your patient, and then started typing into the details box to search. 

Accordingly, we've changed the wording of the button.

As to whether we should include name in the search here, what we're doing is the same as what happens in the "New Patient" modals on the list view - which is why it was only number.

Good spot re the continuing patient details header !

**Comment by fredkingham** [comment]
great stuff, thanks @gabpoll, header on the diagnosis panel is updated and there's no success link

**Comment by GabPoll** [comment]
ok, done, thanks.

Will see how the referral thing goes in the wild
