### ISSUE TITLE
In v0.5, patients tagged micro_haem will display a "Haem extra info box" on right hand side of advice view

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#733]
This is a tag specific box to collect pan-patient extra information about their clinical course. The precise content to be finalised, but will need to include the following fields.

Patient type (bullet options or look up list) - "Transplant", "White cell", "Other"

Options below will depend on result.
If "Transplant"
- Type of transplant - look up list (probably)
- Date of transplant (DATE field)
- Neutropaenia onset (DATE field)
- Count recovery (DATE field)

If "White Cell"
- Type of chemotherapy - look up list (probably)
- Date of chemotherapy (DATE field)
- Neutropaenia onset (DATE field)
- Count recovery (DATE field)

Not sure about
a) "Other" category
b) "Type of" fields

This is information that Vanya says he will fill in, and will frame the events collected in investigations, antibiotics and clinical advice.

**Comment by fredkingham** [comment]
@GabPoll can you update the ticket with how your want it displayed e.g. [[ date ]] [[ type ]] etc :)

**Comment by fredkingham** [comment]
@gabpoll any idea about the "other", ie what fields then get filled in? I'll bash out Transplant and White cell for the time being.

As discussed in the top box will be the last occurrences of White Cell and the last occurrences of Transplant, so if there's "Other" I'm assuming we'd want the aggregate of all previous "others", (I think "other" may need further discussion)

**Comment by davidmiller** [comment]
I suggest just a free text details field would be good enough for a first pass.

**Comment by GabPoll** [comment]
this is a good first pass. Will reserve further comments till i get Vanya feedback. Likely to need tweaking.

**Comment by davidmiller** [comment]
Done pending more feedback from V !

**Comment by GabPoll** [comment]
Clarification after VG conversation. Actually first pass to be simpler than current iteration.
- [ ] In Transplant category, REMOVE type of chemotherapy & date.
- [ ] In Transplant category, put type of transplant above date of transplant
- [ ] In White cell category, REMOVE count recovery

**Comment by GabPoll** [comment]
Also rename "Recent Haem Information" to "Haematology background info"

**Comment by GabPoll** [comment]
Assuming points 4 & 5 are done too @fredkingham
