### ISSUE TITLE
As a user I want to flag investigation results as "Alerts"

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#734]
So that we can make sure to give them high visibility to people viewing this patient.

**Comment by davidmiller** [comment]
@GabPoll 
Should _all_ investigations be flaggable? 
Is it just a subset of investigations (e.g. ones with certain organisms/resistances.) 

What is the correct clinical terminology for the box on e.g. the advice view - is it resistant organisms ? Is it alerts ? etc (e.g. what should go in the title of the panel)

**Comment by davidmiller** [comment]
@GabPoll sorry, only just got to #735 !

**Comment by GabPoll** [comment]
I would think that the simplest solution (and prob most appropriate) is for all investigations to be flaggable. That way it's user driven.

**Comment by GabPoll** [comment]
seems to work lovely to me, thx
