### ISSUE TITLE
Alert investigation results to be automatically populated by any investigation results that is selected as such

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#736]
The content to display in "Alert investigation results"is identical to the content displayed in Investigations section

**Comment by davidmiller** [comment]
(Currently blocked by #734)

**Comment by GabPoll** [comment]
This looks fixed.

One thing is that this list could get long and not be easy to edit - i.e. have to find relevant tests in the timeline. The thing is alert results may get superseded.

Thoughts on a button next to each alert investigation which is "remove from alert list", or something like that?

**Comment by davidmiller** [comment]
Why not let Vanya use it for a while and see what happens? 

We need to deploy this to say ELCIDT and see what it looks like with real data anyway !

**Comment by GabPoll** [comment]
Ok, happy for VG opinion, you're right @davidmiller
