### ISSUE TITLE
Micro haem discussion in advice view to be removed

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#737]
Leave General Consultation with the same fields as currently present WITHOUT any checkboxes.
Date - default to now
Time - default to now
Advice given by - default to user
Reason for clinical interaction - drop down or look up to include "Ward round" - default to last entry for that user
Clinical discussion - as it is
Discussed with - to default to last entry for that user

**Comment by davidmiller** [comment]
@gabpoll I'm not sure what new elements this ticket is referring to that isn't in other tickets?

**Comment by GabPoll** [comment]
At the moment, advice view gives you option to enter a free text clinical consultation as a clinical advice (as now) or micro-haem ward round discussion with some specific neutropaenia check boxes, etc... I think the latter should be scrapped, and it all gets entered via conventional clinical advice modal.
