### ISSUE TITLE
On advice view, back to top button should be in bottom right of page, be bigger and say "Top"

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#739]
Functionality otherwise perfect.

**Comment by fredkingham** [comment]
done on elcid04

**Comment by GabPoll** [comment]
sorry, not seeing the top button at all

**Comment by fredkingham** [comment]
scroll down, its in the bottom right no?

**Comment by GabPoll** [comment]
no, not there at al. Firefox.

**Comment by michaeledwardmarks** [comment]
Works on chrome on my mobile phone.
Appears as you scroll down on

http://elcid04-test.herokuapp.com/#/patient/yt6655

**Comment by michaeledwardmarks** [comment]
Very nice

**Comment by GabPoll** [comment]
Ok, this is a Firefox issue i think!
Works on Edge browser (BTW, it's perfect and would close issue if not for other issues below). 

Not working on Firefox. Haven't got Chrome. Could someone else check this please? Clearly important as that is the browser used on wards. (I've tried CTRL-F5)

Out of curiosity @michaeledwardmarks , how did you get to that patient advice view? I thought it only worked on this patient https://elcid04-test.herokuapp.com/#/patient/579007.

**Comment by michaeledwardmarks** [comment]
I'll check on FF. We use FF not chrome on ward so it needs to work on FF .

**Comment by michaeledwardmarks** [comment]
Doesn't work on FF for me either.

I note the following error message:

"Error: [ng:areq] Argument 'ClinicalAdviceForm' is not a function, got undefined
http://errors.angularjs.org/1.2.20/ng/areq?p0=ClinicalAdviceForm&p1=not%20a%20function%2C%20got%20undefined
minErr/<@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2034:8
assertArg@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2132:1
assertArgFn@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2135:1
$ControllerProvider/this.$get</<@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2382:641
nodeLinkFn/<@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2338:20
forEach@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2042:87
nodeLinkFn@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2337:85
compositeLinkFn@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2288:1
compositeLinkFn@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2288:99
compositeLinkFn@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2288:99
publicLinkFn@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2281:70
createBoundTranscludeFn/boundTranscludeFn@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2290:11
controllersBoundTransclude@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2345:8
ngIfWatchAction@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2768:1242
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2592:368
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2594:244
done@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2411:81
completeRequest@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2429:59
createHttpBackend/</xhr.onreadystatechange@http://elcid04-test.herokuapp.com/assets/CACHE/js/42d54694904b.js:2423:1
"

**Comment by fredkingham** [comment]
should all be fixed in ff on https://elcid04-test.herokuapp.com/#/patient/579007

btw the view is just https://elcid04-test.herokuapp.com/#/patient/[[ hospital number ]]

so you can try a few different patients

**Comment by GabPoll** [comment]
Excellent, thanks.
