### ISSUE TITLE
On advice view, the order of the right hand episode specific panels should be....

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#741]
(top to bottom)
Haem specific info
Antimicrobials
Investigations
Diagnoses

Maybe to be refined, not sure

**Comment by davidmiller** [comment]
@gabpoll shouldn't the order be the same as the order in the MH list ?

**Comment by GabPoll** [comment]
@davidmiller i think not. Given that the list is disappearing, this is an opportunity to rank them in order of utility. Especially because here the top one will be most visible. VG to decide this one.

**Comment by GabPoll** [comment]
order not correct yet. see above list. thank you

**Comment by fredkingham** [comment]
sorry about that, must have got lost somewhere, please check again now

**Comment by GabPoll** [comment]
done, thanks!
