### ISSUE TITLE
Can't re-add someone to Walk-In

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#742]
Create Patient X
Discharge via Nurse Led Modal
Try and create new Walk-In Episode
Error Message

Also 
Create Patient Y
Discharge via Doctor Led Care>Walk In Review>Remove From Review
Try and create new Walk-In Episode
Error Message

"Patient is currently an Inpatient" 

Can't see anything in Debugging.

**Comment by michaeledwardmarks** [comment]
You can create a new episode of a different type e.g an Inpatient or OPAT episode.
But you can't create a new Walk-In Episode

**Comment by michaeledwardmarks** [comment]
This is theoretically a big problem because if we see someone and they come back a week later still unwell we can't record that on elCID.....

**Comment by GabPoll** [comment]
wow, big issue indeed. Well spotted. @davidmiller could we put on 0.4.3?

**Comment by michaeledwardmarks** [comment]
Ideally this needs fixing sooner than 0.4.3

**Comment by GabPoll** [comment]
yes wondered that, but first we have to fix on heroku. Then maybe hotfix - let's hear from @davidmiller first.

**Comment by michaeledwardmarks** [comment]
Cause of bug identified.
- [ ] patients discharged from walk-in need episode status set as inactive

Currently discharged from walk- in patients episodes remain active hence why you can't make a subsequent episode.

If you manually change to inactive in admin then you can create a new episode.

**Comment by GabPoll** [comment]
nicely worked out!

**Comment by michaeledwardmarks** [comment]
I would guess that in the circumstance when you do try and add someone to walk-in who has a genuine active walk-in episode (e.g they are still actually on one of the walk-in lists) that the it would also be better if the message said:
- This patient is already on Walk-In list X

**Comment by michaeledwardmarks** [comment]
For discussion:
- If you are on Walk-In review should you be able to have a new episode added?

e.g 
I saw you on Monday, you come back on Friday....

So in this case the episode becomes inactive when you
- Get Nurse Led Discharge
- Doctor End of Appointment

**Comment by GabPoll** [comment]
Agree with "This patient is already on Walk-In list X"

In the latter scenario, do you mean they are in Walk-in review because a test is still pending? If so, yes, sort of an inactive episode that can be re-activated by re-attendance.

**Comment by michaeledwardmarks** [comment]
Yes similar to that.
I actually think if they 're-attend you want a new walk-in episode not just reactivation, because you want to 're-examine etc and record those findings.

**Comment by michaeledwardmarks** [comment]
@davidmiller Not sure if we agreed yesterday what we would do if the person was still on the review list when they come back?
You advocated moving them back to earlier on the list I think and I advocated counting the review list as inactive/discharged.

The only field that might be an issue if we re-activate is Clinical Findings which is a singelton.

**Comment by davidmiller** [comment]
@michaeledwardmarks My understanding of the review list is that you should leave it fairly quickly.
e.g. if you've come back before you've left the review list then your previous tests, travel history etc will still be relevant.

**Comment by michaeledwardmarks** [comment]
Fair enough by me.
If reactivate then need to make clinical findings not singleton??

**Comment by davidmiller** [comment]
@michaeledwardmarks this is deployed to david-staging

**Comment by michaeledwardmarks** [comment]
Fixed.
