### ISSUE TITLE
In antimicrobial modal, there should be a tick box for "No antimicrobial drug"

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#746]
the alternative is to have an antimicrobial called "NONE" in the drop down. I don't think that's intuitive.

Do we also want a prompt at discharge if nothing filled in - did your patient really have no antimicrobial?

Blocked by #744 at the mo

**Comment by michaeledwardmarks** [comment]
One possible issue with this is that you make it a subfield of a specific antimicrobial record rather than a specific field.
e.g you could record the None button multiple times.
Agree checking at Discharge is sensible we should have a list of those

**Comment by GabPoll** [comment]
Suprseded by 747
