### ISSUE TITLE
Things to check at Discharge

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#747]
- [x] Travel
- Either a country is entered OR the Did-Not-Travel button is ticked

- [ ] Antimicrobial
- Either a drug is entered OR a record that NO-Antimicrobial was given

this is for 
ID-Inpatient
Tropical
Immune-Inpatient

**Comment by michaeledwardmarks** [comment]
This is linked to
- Remove Free-Text from Discharge Diagnosis
- Make symptoms categorised/non-free text

And therefore to good, complete data

**Comment by michaeledwardmarks** [comment]
- [ ] Symptoms: That categorised symptom data  #749 was collected

**Comment by GabPoll** [comment]
this is a good summary issue. Thx for opening.

**Comment by michaeledwardmarks** [comment]
This is looking good.
I'm just thinking about the antimicrobial one - what do we do if they decide they want to add more than 1 add discharge?

**Comment by michaeledwardmarks** [comment]
I would tweak the wording.
" You haven't recorded any antimicrobials for this patient.
Please enter the name and the start and end dates of any antimicrobials the patient received or state that the patient was not on antimicrobials."

I would do similar for travel. So they get a clear "You are being asked to do this because it hasn't been recorded type message"

**Comment by michaeledwardmarks** [comment]
- [ ] Doesn't check for symptoms
I would re-order the flow.

1) Symptoms
2) Antimicrobials
3) Travel
4) Discharge Diagnosis

Maybe with an opening line of:
"Please complete the following missing information before recording the discharge diagnosis"

**Comment by GabPoll** [comment]
i think this looks perfect to me.
