### ISSUE TITLE
Discharge Diagnosis should not allow free-text

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#748]

**Comment by michaeledwardmarks** [comment]
Looks good.
What is our strategy if they are insistent "my diagnosis is not on the list"

**Comment by davidmiller** [comment]
https://github.com/openhealthcare/elcid/issues/745 ?

**Comment by michaeledwardmarks** [comment]
Yes option 1 there looks good.

**Comment by davidmiller** [comment]
I think we went for option 3: FT at discharge, no FT at review.

**Comment by GabPoll** [comment]
@davidmiller seems like we've gone for no FT at both discharge & review. @michaeledwardmarks thoughts?

**Comment by davidmiller** [comment]
@gabpoll that was a mistake - now fixed

**Comment by GabPoll** [comment]
done then
