### ISSUE TITLE
OPAT Rejection Date is very odd in the CSV

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#753]
![image](https://cloud.githubusercontent.com/assets/4578105/9975100/0bc3aab2-5ea7-11e5-887b-a613f988be38.png)

**Comment by michaeledwardmarks** [comment]
This is the case both for real elCIDL data and for data from Heroku

**Comment by davidmiller** [comment]
@michaeledwardmarks This is how the now fixed double-save issue presents in the eventual data. 

There is probably a way to go back and figure out what data is junk. 

It'll look like identical (apart from date) multiple records created within seconds of each other on the same patient/episode.

It's quite a hefty piece of data cleaning work though - short term you're almost certainly best off just dumping anything that has this kind of value.

As a second medium term strategy we should probably look at some server side validation for dates to make sure that we don't let code/application errors like this into the database.
