### ISSUE TITLE
Search based on date of discharge from OPAT doesn't seem to work

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#755]
Complete patient OPAT episode.
Date of discharge is set as today
Advanced search:
Location>OPAT Discharge>After>Yesterday
No Results

**Comment by davidmiller** [comment]
I don't think that this will ever work - discharge date is set in episode.

I think this is a duplicate of #339

**Comment by GabPoll** [comment]
this doesn't work as @michaeledwardmarks wanted. However @davidmiller said it's not possible. Then I got assigned it. What would you like me to do @davidmiller - close it?
