### ISSUE TITLE
Date accepted in to OPAT Current doesn't get saved anywhere or exported in to CSV

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#756]
- We get the data on who was rejected
- [x] Need date the person was accepted
- [x] Should be able to search by time someone was accepted on to OPAT

**Comment by michaeledwardmarks** [comment]
This would be 
- Date OPAT Current Tag added AND OPAT-Referral Tag removed

or more simply obviously the date the button was pressed, but I can't find that saved anywhere in admin

**Comment by michaeledwardmarks** [comment]
We need to work out 
- [ ] how we will get this out for the existing dataset 
- [ ] how we get it out moving forward
- [ ] are these the same solution (hopefully)

**Comment by davidmiller** [comment]
Deployed to david-staging as a field on location.

This will move at some stage, but for now the most sensible place was next to all the other opat referral metadata.

**Comment by michaeledwardmarks** [comment]
Should I be able to see this when I double click in to Location?

**Comment by michaeledwardmarks** [comment]
Also I don't see this in admin view of OPAT-Meta which I assume I should?

**Comment by davidmiller** [comment]
Admin view or extract of location

On Fri, 9 Oct 2015 at 20:05 Michael Marks <notifications@github.com> wrote:

> Also I don't see this in admin view of OPAT-Meta which I assume I should?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/756#issuecomment-146962664>
> .
>
-- 
Best regards

David Miller
Open Health Care
