### ISSUE TITLE
On 0.5 (not 0.4.3) search based on Team == OPAT doesn't work

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#757]

**Comment by fredkingham** [comment]
@michaeledwardmarks can I get an example? Its looking like it works but i'm guessing there's a subtle example it must be missing somewhere

**Comment by michaeledwardmarks** [comment]
which server is currently hosting a 0.5 implementation?

**Comment by fredkingham** [comment]
still on https://elcid04-test.herokuapp.com/ at the mo (although there'll
be a new server soon...)

**Comment by michaeledwardmarks** [comment]
hmm. no idea what i did before but appears to be working...

**Comment by fredkingham** [comment]
could be a part of the historic tag issues which should now be fixed maybe.
