### ISSUE TITLE
How should we best order Walk-In Review

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#764]
Option 1:
Alphabetically

Option 2:
Date of attendance (then alphabetically within days?)

Option 2 allows you know to check easily the people you saw when you were the walk-in doc.

**Comment by davidmiller** [comment]
Per list ordering is one of those things we really should have but really don't.

So... yes but not easily.

Filters are awesome though short term.

**Comment by michaeledwardmarks** [comment]
Putting this in 0.5 might let us finish Walk-In so might be worth aiming for.

**Comment by GabPoll** [comment]
Vote from me for option 2

**Comment by michaeledwardmarks** [comment]
Also vote for option 2 from myself and also from the current walk in Reg Kate

**Comment by GabPoll** [comment]
because no "fixed" tag, moving to 0.6

**Comment by davidmiller** [comment]
Fixed and deployed for review to https://elcid052.herokuapp.com/ 

Review only now orders date of appt, then alphabetical within a day.

**Comment by GabPoll** [comment]
Looks ok - just need to check with Docs in walk in whether they want oldest attendance at the top (as it is at present) or the other way round (newest at the top)

**Comment by michaeledwardmarks** [comment]
Looks good. I think they don't mind which order for dates hugely just that it be ordered.

**Comment by michaeledwardmarks** [comment]
So our straw poll gave 1 for oldest at top and 1 for newest.
I suggest we go with this - it's in a clear order and we can see how we go.

**Comment by GabPoll** [comment]
Agree. Also might prompt to trim list of patients on it for a while, rather than,being forgotten at the bottom.
