### ISSUE TITLE
Search result miscounts episode numbers?

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#767]
on http://elcid04-test.herokuapp.com/#/list/opat/opat_referrals search for Bug 668 patient. It says 25 episodes, but if you open patient detail view, there are only 5.
@fredkingham am i missing something?

**Comment by davidmiller** [comment]
Yep - same here. 

Something's going wrong there for sure!

**Comment by fredkingham** [comment]
should be fixed, please review

**Comment by davidmiller** [comment]
Looks fixed to me !

On Thu, 1 Oct 2015 at 19:48 Fred <notifications@github.com> wrote:

> should be fixed, please review
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/elcid/issues/767#issuecomment-144814460>
> .
>
-- 
Best regards

David Miller
Open Health Care
