### ISSUE TITLE
Inpatient patient categories look different in modal when editing to way formatted on list ?

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#769]
Showing for some patients as "inpatient" 
These people don't show up on DLW

**Comment by davidmiller** [comment]
@michaeledwardmarks Where do you think the category is _displaying_ wrong?

**Comment by michaeledwardmarks** [comment]
If you click to edit the location field then category shows as 'inpatient' although when looking at the list it is formatted as 'Inpatient'

**Comment by michaeledwardmarks** [comment]
Reworded the title. 
I'll investigate on heroku and see if I can reproduce the DLW bug.

**Comment by davidmiller** [comment]
It's unrelated to discharged last week.

**Comment by michaeledwardmarks** [comment]
Ok!
