### ISSUE TITLE
new ward round - Consultant Review

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#772]
Patients with unconfirmed primary diagnosis
By consultant

**Comment by GabPoll** [comment]
We will capture the consultant at discharge #747

**Comment by michaeledwardmarks** [comment]
This looks good.
- [ ] It incorrectly shows a Clinic Letter button which it doesn't need (not sure if this is unfixable pending the flow on details view fix)
- [ ] I would make the Confirm Diagnosis button more prominent - some of the consultants will struggle to see that

**Comment by GabPoll** [comment]
maybe too late for 0.5, but i would prevent a list being shown  and not show "Start this ward round" until a consultant has been shown in the drop down. Prevent reviewing the wrong patients.

Agree re both of the points made by @michaeledwardmarks above. Clinic letter still showing

**Comment by fredkingham** [comment]
@davidmiller, see all the pull requests (walkin, opal, and elcid)

**Comment by GabPoll** [comment]
given the time before 0.5, i don't know @davidmiller / @fredkingham whether we want to include this as it is in 0.5, or hold back till all 3 points above addressed

**Comment by GabPoll** [comment]
Actually looks ok for 0.5
