### ISSUE TITLE
Delete micro-haem list?

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#777]
This creates a problem. If an ID patient gets seen on micro ward round, they get tagged micro-haem (#776). This is spot on. Then what will happen is that on ID inpatient list, this patient will have the micro-haem tag showing. Currently this clicks through to micro-haem list. 

Shall we make the micro-haem label non clickable?

**Comment by davidmiller** [comment]
@GabPoll that's a great spot !

Honestly I'd suggest not displaying them. 
We should definitely have them not clickable.

@fredkingham Might need another property on opal.models.Team e.g. something like list_display(default=True) ?

**Comment by michaeledwardmarks** [comment]
Agree don't display.

**Comment by GabPoll** [comment]
this is still present on elCID test server

**Comment by davidmiller** [comment]
Needs to be added to the hackpad

**Comment by GabPoll** [comment]
on the hackpad. Virology should stay
