### ISSUE TITLE
Search on elcid 0.4 seems weird

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#780]
For example searching for Thought MM says no results although there is a patient called that on ID Inpatient

**Comment by GabPoll** [comment]
Have had exactly same problem. Had assumed that this was not the latest search, and therefore was left broken.

Thanks for issuing M

**Comment by davidmiller** [comment]
Still happening ?

**Comment by GabPoll** [comment]
seems ok now.
