### ISSUE TITLE
When a Patient is Dischargd with Follow-up the Location Modal should say Discharged with follow-up or similar not inpatient

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#782]
This is a longstanding regression related I believe to how we now handle patient categories
The current format is very confusing as it shows discharged patients as "Inpatient" if they are discharged with follow-up.

**Comment by michaeledwardmarks** [comment]
You see the same if 
Person on List A & B
Discharge from List A
On List B the status still says Inpatient

**Comment by davidmiller** [comment]
Checking again on elCID 0.6.3 looks like this is no longer the case.

Meanwhile 'categories' is still a little bit of a mess under the hood :(
