### ISSUE TITLE
Pull Travel Specific Exposures in to Walk-In letters

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#783]
Should display as:

Travel:

COUNTRY - DATE
Specific Exposures: SPECIFIC EXPOSURES

If trivial 0.5 please.

**Comment by davidmiller** [comment]
Fixed and deployed for review to https://elcid052.herokuapp.com/

**Comment by michaeledwardmarks** [comment]
Looks fine
