### ISSUE TITLE
Check if a diagnosis is entered when removing from walk in review

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#787]
Like we do for nurses and hiv tests.
Do on review list not doctor list as that gives time for it to be informed by results

**Comment by davidmiller** [comment]
Fixed and deployed for review to https://elcid052.herokuapp.com/

**Comment by GabPoll** [comment]
i think that looks ok

**Comment by michaeledwardmarks** [comment]
Fab
