### ISSUE TITLE
As a clinician I would like a comprehensive list of Conditions, Symptoms and Consultants

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#788]
We will take the symptom list from the competencies list in the NHS Eportfolio.
@michaeledwardmarks will extract and circulate.

**Comment by michaeledwardmarks** [comment]
We will identify SNOMED-CT IDs for these

**Comment by GabPoll** [comment]
for the moment, the list of symptoms I sent you last night @davidmiller is going to be sufficient. If so, then can close this. I've moved to hackpad as a check list.

**Comment by davidmiller** [comment]
We would also like to add the labtestdetails list from this ticket: https://github.com/openhealthcare/opal-research/issues/72#issuecomment-152182867
