### ISSUE TITLE
As a User I would like to view the patient I have just referred to Haem

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#796]
So that I can start entering notes for them.

**Comment by GabPoll** [comment]
This should be done such that after referral made, then link is present that takes straight to that patient's advice view.

**Comment by GabPoll** [comment]
this looks done to me. 

However I would change one thing - the hyperlink to the patient advice view should be the patient name, not "Micro-haem".

**Comment by davidmiller** [comment]
OK - closing (see #840)
