### ISSUE TITLE
As a User I would like to know how far through the discharge process I am

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#798]
So that I can understand how much time the process is going to take

**Comment by GabPoll** [comment]
well, i think this is actually done - it's pretty clear that you have to get through the 5 symbols. Not sure time is a key thing as it's quick and the fields familiar (as the modals are essentially the same).

@davidmiller agree?

**Comment by davidmiller** [comment]
Sure - I mean time in a looser sense :)
