### ISSUE TITLE
Need to mae sure drug frequency look up list on live is fully synonymised

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#806]
On heroku it says once a day, twice a day, etc... but no synonyms for OD, BD, TDS. This is vital cos docs think like the latter. Also vital cos currently in alphabetical order not frequency order.

This issue is an aide memoire for live system

**Comment by michaeledwardmarks** [comment]
It's a dropdown on elCID live so this doesn't matter!
