### ISSUE TITLE
when adding antimicrobials, "not on antimicrobials" tick box should not appear if patient already has an antimicrobial entered

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#812]
Appreciate this may not be trivial and can be ignored for 0.5

**Comment by davidmiller** [comment]
I think this makes sense for list view - also travel

**Comment by michaeledwardmarks** [comment]
Is this still a thing? We don't ask for antimicrobials at discharge if the patient has had one entered.

**Comment by davidmiller** [comment]
I think this is a fixed bug - would need to check but I'm fairly sure we fixed it in one of the previous 0.5.x releases

**Comment by michaeledwardmarks** [comment]
Concur it appears fixed to me on 0.5.3 heroku.
