### ISSUE TITLE
In advanced search, the 4th box ALWAYS goes onto a second line now.

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#821]
Caused by new category called Haematology Background Information - made that box too wide.

Solutions:
a) narrow Saved Searches
b) change name to Haem background info

**Comment by GabPoll** [comment]
this issue really grates me. Perhaps cos it's labelled "design"!

**Comment by davidmiller** [comment]
I think the whole interface needs a proper looking at.
There's a gathering pace around something that deals with extract, reporting, dashboards, export IMHO.

**Comment by davidmiller** [comment]
We've re-done this in 0.6.4 (I think) to fix this - and the logic has completely changed as well. Agree things shouldn't float onto new lines :)
