### ISSUE TITLE
When haem referral already on elCID, result looks strange

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#822]
It should say
"xxxx patient is already on elCID - this is his haeamatology consult record" with hyperlink on his name or on work haematology consult record"

Instead it currently says - "Thanks - xxxx added succesfully"

Thankfully it doesn't look like it's creating a new patient.

**Comment by davidmiller** [comment]
@fredkingham are you taking this as part of the add episode via gloss flow?

**Comment by fredkingham** [comment]
@GabPoll I've made some changes, I *think* its ok now let me know what you think

**Comment by GabPoll** [comment]
ok, so it is better. I would change one more thing:

Where it says "we've added to microhaematology" with a hyperlink on microhameatology, I'd change it to "we've created a micro-haematology records for this patient", with the link being on the words "micro-haematology record". The current destination of that record is currently perfect.
