### ISSUE TITLE
On advice view, change date display for each clinical advice to DD Month YY

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#823]
I know we've discussed this before, but we need this for the transition of existing haem patients to 0.5

There have been times when advice has been added to the wrong episode. As it is, we're rolling out a system where advice is sorted by date within an episode but crucially, episodes are in their own date order (which may have been wrong to start with). However because of previous mixups, some advice is not perfectly chronological. I've seen it already on elCID test that for a few patients without the year, you don't really know what order some advice was given. Especially a problem as we can't open advice in non-active episodes (i.e. so you can't see the year within the modal).

There should certainly be screen space for this. Going forward, this problem will just go away, but we need it for now, sorry.

**Comment by GabPoll** [comment]
sorry to be a pain, but this is still not quite right.

To reduce confusion, I would prefer every advice view entry to have DD/MM/YYYY.

There is an oddity on patient Frank Francis 804738492 where there is an entry on 03/11 which remains stubbornly at the bottom. Not sure what that is, Otherwise ordering looks ok.

**Comment by GabPoll** [comment]
Was thinking about this on way in. DD Mon YYYY would be better than DD/MM/YYYY. But at this stage happy to go with whatever is easiest.

**Comment by fredkingham** [comment]
should be done, take a look at https://elcid04-test.herokuapp.com/#/patient/37

**Comment by GabPoll** [comment]
@fredkingham the appearance is now perfect!

However there is some issue with the ordering - i half spotted this yesterday - could you take a look at the same patiient you linked to. The ordering error should be obvious. Thank you.

**Comment by GabPoll** [comment]
it seems that mine sorted well by date, but your entry is out of place for some reason (the one 29 Dec 2014)

**Comment by GabPoll** [comment]
Display is fine. Ordering is a separate issues
