### ISSUE TITLE
When making a haem referral of a patient already tagged to another team, this does not add a micro haem tag

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#825]
This is an error. 
When adding a new patient, the system correctly adds micro haem tag.

**Comment by davidmiller** [comment]
@GabPoll  we believe this is fixed on Heroku

**Comment by GabPoll** [comment]
sorry, doesn't look fixed to me.

**Comment by GabPoll** [comment]
the micro haem bit is good BUT, haem referral also seems to be adding ID inpatient tag to these patients. Weird!

**Comment by fredkingham** [comment]
are you sure they weren't tagged with inpatients already? Which patient did
you try? I just did https://elcid04-test.herokuapp.com/#/episode/43 and it
worked as predicted

**Comment by davidmiller** [comment]
@GabPoll I can't reproduce this at all I'm afraid :(

**Comment by GabPoll** [comment]
Ok, well, that's good. I'll have another go later on, but sounds like this is closable later.

**Comment by GabPoll** [comment]
well, i can't reproduce it either now, and original ticket is addressed. Thank you @fredkingham
