### ISSUE TITLE
On advice view, the writing between episodes always says "Current inpatient admission".

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#837]
Should just say "Episode dates: DD/MM/YYYY - DD/MM/YYYY"

**Comment by davidmiller** [comment]
We're going to take this out entirely. As of 0.6 an admission is not an episode - we'll display admissions separately I'm fairly sure.

**Comment by GabPoll** [comment]
Sounds like a good plan

**Comment by davidmiller** [comment]
Deployed to http://elcid-uch-test.openhealthcare.org.uk/

**Comment by GabPoll** [comment]
yep, cleaner in 0;6
