### ISSUE TITLE
OPAT referral for an inpatient doesnt import any clinical data

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#839]

**Comment by GabPoll** [comment]
still doesn't work on heroku.
Roy Iris on ID inpatient. Referred to OPAT via referral button. OPAT episode has not imported any clinical information from inpatient episode.

**Comment by davidmiller** [comment]
Ah, I see.
Ok - we'll delete the OPAT referral for now.

**Comment by GabPoll** [comment]
So referral should only occur by adding patient on OPAT referral list? Didn't try that!

**Comment by davidmiller** [comment]
I think that's the way that 99% of patients get on there.

**Comment by GabPoll** [comment]
ok, it is fixed. Personally, my way is more logical - i.e. a standardised place where patients get referred (like micro haem), but happy to go with the flow of what everyone else is doing.

**Comment by davidmiller** [comment]
So that would totally make more sense.
In practice, they are phoned to Steve who is already on the list !
