### ISSUE TITLE
Provide better messaging in the symptoms modal 

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#858]
for when your symptom isn't in the list

**Comment by GabPoll** [comment]
agree - we'd discussed this several times.
Could a feedback button address this need and one perhaps for antimicrobials once that becomes no FT?

**Comment by davidmiller** [comment]
@GabPoll possibly - but that's a bigger change than adding a message - I think we need a short term fix )

**Comment by GabPoll** [comment]
I see. Sorry I think I misunderstood what you were planning.

**Comment by fredkingham** [comment]
add help text, if your symptom isn't in the list add it to the details

**Comment by GabPoll** [comment]
If you want to be very finnicky, the grammar isn't quite right here.
If should be capitalised and a comma should follow the word list
"If a symptom isn't in the list, add it in the details box"

Perhaps follow sentence with "and inform elCID team on elcid@openhealthcare.org.uk"?

**Comment by GabPoll** [comment]
perfect, thx
