### ISSUE TITLE
OPAT Review missing Primary Infective Diagnosis field

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#861]
Should be in modal on detail page.

**Comment by fredkingham** [comment]
missing a field that appears in the discharge flow but not the patient details, put it in the record panel/modal please

**Comment by GabPoll** [comment]
this is now in the OPAT Outcome modal - is this where it should be? Or should i be checking somewhere else?

**Comment by davidmiller** [comment]
@gabpoll That's the change that this is referring to yes :)

> --
Best regards

David Miller
Open Health Care

**Comment by GabPoll** [comment]
in which case, done!
