### ISSUE TITLE
What ethnicity is White?

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#863]
Users have reported not knowing how to report patients who are White but not British.

"Where is just 'white' " was the specific question.

I guess "Any other White background"? 

It's not obvious. 

Can we look at synonymising the canonical upstream lookuplist to be friendleir to users

Thoughts please @GabPoll @michaeledwardmarks

**Comment by GabPoll** [comment]
there is an official ethnicity classification - it's the one on all equal opportunities sections of application forms for anything. Not sure how to get hold of it though.

**Comment by davidmiller** [comment]
The lookuplist we had came from official NHS guidance. 
It just turns out that the official classification doesn't make sense to humans :)

That's the advantage of synonyms - we can have human friendly lookuplist entries that resolve to canonical terms  - I think that in the context of our list white is a synonym of AOWB.

**Comment by michaeledwardmarks** [comment]
Yes I'm sure that is true. Our list matches CDR.

Sent from my HTC

----- Reply message -----

**Comment by michaeledwardmarks** [comment]
I think we can close this ATM as we will take this from the Carecast feed from now on
