### ISSUE TITLE
More detailed user profiles

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#87]
Worth considering whether we want someones profile to also include:
Role (consultant,spr etc)
Department (HTD/Micro/Virology)
Could be set during account setup but with option for user to change this.

Reason I think might be useful 
1) #36 - for a user visible audit trail it would be good to display something like "edited by M Marks, SPR - HTD" because people won't necessarily know who everyone in whole division is
2) If we wanted to assign certain rights to some users but not others then having a role might be a way to do this

**Comment by davidmiller** [comment]
I think this is now superseded by #547 - move to close !
