### ISSUE TITLE
Should "Add Patient" buttons be visible in Walk in Doctor & Review lists?

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#891]
I'd think not. I could add a new patient straight to walk in Review list.

Perhaps not a big issue. Ping @michaeledwardmarks .

**Comment by michaeledwardmarks** [comment]
I don't think you should be able to on Review list, but I think Doctor list is ok. Sometimes if clinic is very busy the docs see people before the nurses

**Comment by michaeledwardmarks** [comment]
Closing as not currently an issue.
