### ISSUE TITLE
Handle external patients

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#90]
Requested in feedback.

Problem: Don't have UCH hospital number to act as unique identifier

Options:
1) Combine external hospital name and patient number at that hospital as temporary number (probably in a new External Hospital Number field)
2) Random number 
3) Temporary identification by Name&DOB alone 

Option 2 offers no advantage over option 1 and is less informative

I worry that 3 is problematic and risks duplication - as it lacks a true unique identifier 

Whatever we do we need to think about how the hospital number will later be appended - may impact / be impacted on by #38

**Comment by davidmiller** [comment]
As of recently - e.g. the Tropical Liaison list we now have an active strategy for handling active identifiers, so I'm closing this as done !
