### ISSUE TITLE
make lists declarative

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#901]

**Comment by davidmiller** [comment]
I think there are still some kinks remaining with this - e.g. how we build the dropdown, permissions & ordering... but enough for this ticket. 

We're also still not entirely declarative - we're split between code & DB with references by magic strings.

As @fredkingham that was the case before this ticket anyway with schema.py - all that's happened is that the balance between code/DB has shifted in favour of code.

As such, it's a plausible atomic unit towards being fully declarative
