### ISSUE TITLE
Unable to add clinical advice

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#915]
PLUS "+" button missing

**Comment by GabPoll** [comment]
still an issue on pt details view.

**Comment by davidmiller** [comment]
@fredkingham Have you looked at this one ? 

Doesn't seem to be deployed to Heroku...

**Comment by fredkingham** [comment]
sorry, I thought this was the fact that the form was missing on the haem view, so I added that in and marked it as closed, I'm moving it back

**Comment by davidmiller** [comment]
Deployed to http://elcid-uch-test.openhealthcare.org.uk/

**Comment by GabPoll** [comment]
They're back, thank you
