### ISSUE TITLE
Edit demographics button / click (the pencil) does not work in patient detail view

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#917]

**Comment by fredkingham** [comment]
should be fixed as part of pull request #398

**Comment by GabPoll** [comment]
still not working

**Comment by davidmiller** [comment]
This has ben deployed to http://elcid-uch-test.openhealthcare.org.uk/ . 

See #995 for the outstanding "not a datepicker" issue

**Comment by GabPoll** [comment]
thx

**Comment by fredkingham** [comment]
not actually fixed (well a different issue was fixed), 

I think the problem here is we pull the demographics off the patient model and update it on a different instance hanging off the episode, not sure what the clean fix is

**Comment by GabPoll** [comment]
so this works, and opens up the demographics modal - but is now read only - presumably deliberately because data is fed in, rather than added in elCID? Is this correct @fredkingham ?

**Comment by fredkingham** [comment]
if the data has come from uclh then its uneditable, otherwise it is editable. That may have to change as place of birth is going to be an elcid only field, but for the time being this makes sense.

(I think!)

**Comment by GabPoll** [comment]
yes, and i've tested that it works exactly that way. Issue slammed shut!
