### ISSUE TITLE
Make microscopy and culture subfield heading appear

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#93]
In django the tests in: micro_test_mcs/

Make “Microscopy” and “Culture" subfield heading appear on list if something is written in them

So if the fields are left blank you would get:
Sputum AFB

then when microscopy available:
Sputum AFB: Microscopy Positive

then when culture available:
Sputum AFB: Microscopy positive, Culture: MTB - 5 Days

**Comment by davidmiller** [comment]
Deployed to elcid04 server

**Comment by michaeledwardmarks** [comment]
Fantastic
