### ISSUE TITLE
Full screen modals make poor use of full screen

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#932]
At the moment, the amount of actionable stuff on a full screen modal is the same as when it was floating on top of the list. For example, if we have the whole screen to add a new patient, I shouldn't need to scroll down to select teams and hit save.

In its current iteration, i think full screen modals are a regression, as there doesn't appear to be any gain over the loss of orientation relative to where one was working before.

**Comment by michaeledwardmarks** [comment]
Agree currently not optimal use of the screen.
I also find for some things that I like to be able to see the stuff in the background when i'm adding information
e.g I am adding PMH, I can't see the existing PMH on the list

**Comment by fredkingham** [comment]
we've backed it out

**Comment by GabPoll** [comment]
thx @fredkingham - i still see them in v0.6 tho
