### ISSUE TITLE
haem view timeline should display date & time

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#933]
currently only date.

**Comment by davidmiller** [comment]
I think not all of the fixes that went into 0.5.x were forward ported to 0.6.0 - we should do a total feature review of the two versions before going live!

**Comment by fredkingham** [comment]
I'm not sure we ever showed time did we? e.g. http://elcid052.herokuapp.com/#/patient/22 that said Mister Miller was right there's a whole bunch of stuff that hadn't been moved from 0.5.x. That *should* all now be there...

**Comment by fredkingham** [comment]
(do we want to be showing time?)

**Comment by GabPoll** [comment]
agree w/ @fredkingham - we never showed time. I think we want to show time now.

**Comment by davidmiller** [comment]
@GabPoll I think this is fixed and deployed to Heroku for elCID06

**Comment by GabPoll** [comment]
perfect, thank you
