### ISSUE TITLE
Confirm discharge button too big and overspills the width of the left sidebar.

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#935]
Checkout some of the patients on virology list.
Suggest reducing size of font.

**Comment by GabPoll** [comment]
thx for fixing this

**Comment by GabPoll** [comment]
actually, just looked again - this is entirely page zoom related. If page zoomed too much, then spills over. I.e. the confirm discharge button doesn't scale to same degree as left hand column. Re-opening just to get a reply, but if you like, can close again. This is in general a rare and unimportant occurrence.

**Comment by davidmiller** [comment]
I think that this is no longer really an issue...

The screen resolutions 1280*1024, 1600*1280, 1920*1536 make up 90% of our usage - it's fine for them

It's < 1.5% of users viewing at a resolution that's small enough for this to matter - and the answer for those people will be a thorough responsive design solution... I'm going to close for now.
