### ISSUE TITLE
Subscription in Gloss

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#938]
an elcid patient needs to be able to subscribe

**Comment by fredkingham** [comment]
- [ ] has a subscriptions end point that takes a hospital number and returns a gloss id
- [ ]  stores the subscription in a table with the end point to reply to
- [ ] has a concept of different types of roles/filters which at present is just core_demographics, all_information. That is the subscription type
- [ ] unit tests that cover all of the above

**Comment by davidmiller** [comment]
@fredkingham Where should I be looking for this ? Is it openhealthcare/glossolalia master? 
Do you think we meet all of the acceptance criteria ?

**Comment by fredkingham** [comment]
https://hackpad.com/Gloss-APIs-eQIqnwOxOkv
