### ISSUE TITLE
Deleting the last Character in the Hospital Number/Name Filter boxes causes the Page to reload

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#945]
On elCID live - reported by Walk-In Doc.

Recreated on 0.5.2 heroku
On list ID-Inaptients
Filter list by Name:
Type: Lisa
List filters to just show Lisa
Use backspace to delete LISA one letter at a time.
When you delete the L the list page reloads.

If you select the Name with mouse and delete all in one go it is ok.

**Comment by GabPoll** [comment]
I've seen this before. Thought I'd reported already. Sorry for not githubbing sooner. 

Amazing anyone using the filter boxes. Didn't think they did.

**Comment by michaeledwardmarks** [comment]
Popular in walk-in review I imagine because they get called about people they saw earlier in the week and previously impossible to find without filtering

**Comment by michaeledwardmarks** [comment]
Closed in view of #601
