### ISSUE TITLE
Add haem-related audit tick boxes in CA modal

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#949]
In v0.6 these are still present for clinical advice modal in ID liaison. Not present in Walkin doctor CA. Unable to test in patient details view due to #915.

Ideally we would have checkboxes appear (e.g "neutropaenic today" - Y/N) only if select "Micro haem ward round" or "Micro-haem telephone"). Is this trivial? I have no idea. In practice though, if the "neutropaenic?" tick box was present for all patients would not be a problem - it's just that only vanya would tick it.

This is an idea (with some merit) from VG to replace #948.

**Comment by GabPoll** [comment]
of all the VG suggestions, this seems the least complicated as a short term data capture exercise (replacing #948) prior to integration of neutrophil counts from winpath. I wonder whether this is easy / achievable for v0.6.

Given that checkboxes appear in some but not all CAs, I don't know how simple this is. Would be acceptable for this to be a checkbox visible in all CA, I'd think, not just if select haem consult.

Question is to @fredkingham & @davidmiller . Thoughts from @michaeledwardmarks always welcome but not absolutely required!

**Comment by davidmiller** [comment]
I think we've shelved this permanently after further conversation with VG & RH !
