### ISSUE TITLE
Add Markdown documentation inline where available.

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#95]
Nobody will use if they aren't aware it exists.

**Comment by davidmiller** [comment]
This looks super ! 

Now maybe people might actually use it more :)

**Comment by GabPoll** [comment]
will have to provide some form of prompt / tutorial to let people know this exists though

**Comment by davidmiller** [comment]
@GabPoll That's what this ticket is :) Open a TODO entry - you get a prompt like you do at the bottom of the GH comment box...

**Comment by GabPoll** [comment]
i get it - not a massively user friendly link, but it might catch on - oooh you did that in bold, how did you do that? etc... Good work crew.
