### ISSUE TITLE
Going back to the Ward Round Page gives a hidden error

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#951]
- I'm in consultant review ward round
- I click the Ward Round button
- No actual error seen BUT
- Debugging shows:

Error: getTranslators: detection is already running at chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/zotero/translation/translate.js:1023logError @ zotero.js:144detect @ inject.js:214(anonymous function) @ inject.js:234(anonymous function) @ messaging_inject.js:93target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:387target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94EventImpl.dispatch_ @ extensions::event_bindings:371EventImpl.dispatch @ extensions::event_bindings:393target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94messageListener @ extensions::messaging:179target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:387target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94EventImpl.dispatch_ @ extensions::event_bindings:371EventImpl.dispatch @ extensions::event_bindings:393target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94dispatchOnMessage @ extensions::messaging:310

**Comment by davidmiller** [comment]
Not happening any more... we did lots of work with Wardrounds last year - presume @fredkingham fixed it in passing as part of that...
