### ISSUE TITLE
Make user complete First/Last Name on login 

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#962]
Consider this if
- [ ] We dont hold their real name (clear back log)
- [ ] First time user logs in (future users)
- Imagined to work in a similar fashion to Password Change on first login
- Because reality of current adding of users is that we dont capture this >70% of the time
- Because otherwise Name stamped fields like clinical advice are frequently unidentifiable.

**Comment by davidmiller** [comment]
Perhaps we'd be better off making it required in the Admin.

**Comment by michaeledwardmarks** [comment]
Currently its a two step process in Admin.
You have to create a new user name, save and only then do the fields appear for first and last name.

**Comment by GabPoll** [comment]
I'd raised this before, but can't seem to find. That is exactly the issue - the page where you generate username and password does NOT ask for first name and surname. Admin clicks save and then page reloads with those fields offered. I suspect Maggie usually just moves onto something else at this stage.

Simplest solution is to put it all on the same page. Making it a required field also good suggestion.

**Comment by davidmiller** [comment]
We've since changed the admin form so that it includes these - should help lots !
Will deploy with ? elCID 0.6.4
