### ISSUE TITLE
Search Box weirdly disappearing

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#969]
Noticed by Rob Lever
The Search Box isn't there for him.
Made a new username and it worked for that name but not for his actual username.
Search here for me.
So probably linked to his account.

**Comment by davidmiller** [comment]
Interesting.
We'll investigate...

Paging @fredkingham

**Comment by michaeledwardmarks** [comment]
I fixed this by removing "researcher" status from his profile - not sure why he had that turned on.

**Comment by davidmiller** [comment]
This is a feature of the RidRTI stuff... don't give people that status  !
