### ISSUE TITLE
Time mismatch on haem clinical advice view

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#971]
I'm entering advice @21:55.  Displays that in the fields above the clinical advice, but once save and add it to timeline, displays 21:02. The fault appears to be with the minutes bit of the time. No matter what time i set the time of clinical advice, after saving, the minute in the timeline always displays :02. The hour is always correct.

Probably ping @fredkingham

**Comment by davidmiller** [comment]
Yep, it's displaying the month not the minute.

**Comment by davidmiller** [comment]
Deployed to elcid-uch-test. 

Note: We seem to have issues with Haem view for patients with > 1 episode - so try to avoid. (#1006)

**Comment by GabPoll** [comment]
yep, confirm this is fixed. I also can reproduce #1006, FYI.
