### ISSUE TITLE
"Download this data" should be "Download these data"

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#978]
Grammatical correction

**Comment by davidmiller** [comment]
Meh.

I think that train left the station already.

http://www.oxforddictionaries.com/definition/english/data#m_en_gb0205520
http://blogs.wsj.com/economics/2012/07/05/is-data-is-or-is-data-aint-a-plural/
http://www.theguardian.com/news/datablog/2010/jul/16/data-plural-singular

**Comment by davidmiller** [comment]
I mean, if it's widely irritating people we could re-open and think about re-phrasing but you know... deeply unlikely to pluralise it ;)

**Comment by GabPoll** [comment]
well, if i wrote that in a piece of work for Maddy, he'd change it 100% of the time. But perhaps I mix in overly neurotic circles about these things!
