### ISSUE TITLE
Opening lists view transiently (1 sec) shows a page saying "sorry couldn't find this page"

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#999]
then list opens.

Not a bug per se, but not elegant

**Comment by davidmiller** [comment]
I can't reproduce this one :(
You shouldn't see that during the course of normal operations though
What do we mean by "opening transiently" ?

**Comment by GabPoll** [comment]
In FF - this is happens for 1 sec just after clicking ward rounds. Then it goes away.
![image](https://cloud.githubusercontent.com/assets/4605661/13908053/0c941ec2-eef3-11e5-80f4-9e3c64f41077.png)

**Comment by davidmiller** [comment]
There are definitely paths through the application that end up rendering the 404.html template when they shouldn't.

**Comment by GabPoll** [comment]
incidentally, i'm still seeing this on FF

**Comment by fredkingham** [comment]
weirdly I can't reproduce on Chrome but I can in firefox, on it

**Comment by fredkingham** [comment]
so the issue is resolved the first time you log in you get a blank grey rectangle while angular initialises which isn't perfect. Also I sped up initial log in and removed load time by moving the options load into the controller.

**Comment by GabPoll** [comment]
confirmed it's fixed. Thank you. The grey rectangle is fine - just looks like a loading screen - much better than an error message.
